### ISSUE TITLE
Lidarr not adding new artist

### ISSUE THREAD

**Issue by spencerskinner99** [Ombi-app/Ombi#2668]
#### Ombi build Version:

V 3.0.3945

#### Update Branch:

master

#### Media Sever:

Plex

#### Operating System:

Docker - Linux Server IO container

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

fail: Ombi.Api.Api[1000]

      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.2.13:8686/lidarr/api/v1/artist

fail: Ombi.ErrorHandlingMiddleware[0]

      Something bad happened, ErrorMiddleware caught this

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

Path '', line 1, position 1.

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77

   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 76

   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 31

   at Ombi.Core.Engine.MusicRequestEngine.ApproveAlbum(AlbumRequest request) in C:\projects\requestplex\src\Ombi.Core\Engine\MusicRequestEngine.cs:line 348

   at Ombi.Core.Engine.MusicRequestEngine.RequestAlbum(MusicAlbumRequestViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\MusicRequestEngine.cs:line 107

   at Ombi.Controllers.MusicRequestController.RequestAlbum(MusicAlbumRequestViewModel album) in C:\projects\requestplex\src\Ombi\Controllers\MusicRequestController.cs:line 78

   at lambda_method(Closure , Object )

   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()

   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)

   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 50

   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24


```

#### Problem Description:

Ombi doesnt seem to be passing my album requests through to Lidarr, not sure why its having the issue but I have some container logs as shown above

#### Reproduction Steps:

Connected it to Lidrarr and tried to request Neuropol and it didnt work basically ahaha

**Comment by tidusjar** [comment]
You sure the API key is correct and all the settings are correct?

**Comment by JTT-JustTheTip** [comment]
Yep double checked the API key and made sure the URL base was correct, when I hit test it seems to work fine too

**Comment by DejaVu** [comment]
I'm having the same, although I do not even have an 'Add Artist' button. View Albums, but not artist. Clicking the artist name sends me back to the Ombi home page. 

![0x0](https://user-images.githubusercontent.com/481679/50649310-703ac200-0f75-11e9-9903-640cd640dec9.png)

**Comment by arcidias** [comment]
I got the same issue running Ombi 3.0.4036 and Lidarr 0.5.0.583
When trying to request an album of an artist that's new to Lidarr, the request fails.
When adding a new album of an artist that's already added to Lidarr, the request passes properly
I do not have an option to "Add artist" in Ombi

**Comment by goldenpipes** [comment]
i just tried this with Lacuna Coil and it worked. /shrug

**Comment by tcwatson** [comment]
I'm on Lidarr Version 0.5.0.583 and Ombi Version 3.0.4036, if that helps

**Comment by tcwatson** [comment]
After updating Ombi to 3.0.4119, I am able to add albums that did not exist in Lidarr before, but I do not have an "Add Artist" button. 

![image](https://user-images.githubusercontent.com/10892630/50939277-c4e0b000-1441-11e9-9a54-276dae25aa50.png)

**Comment by goldenpipes** [comment]
Add artist just happens in lidarr when you add an album from a non existing artist.

**Comment by arcidias** [comment]
I still have the same issue as originally reported. 
running Ombi 3.0.4036 and Lidarr 0.5.0.583
Here's the logfile after trying to add an album of a new artist (used Lacuna Coil this time, props for reminding me of them!) :
`2019-01-10 17:30:11.526 +02:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.0.156:38081/lidarr/api/v1/artist
2019-01-10 17:30:11.543 +02:00 [Error] Exception thrown when sending a music to DVR app, added to the request queue
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Lidarr.Models.ArtistResult' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 77
   at Ombi.Core.Senders.MusicSender.SendToLidarr(AlbumRequest model, LidarrSettings settings) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 114
   at Ombi.Core.Senders.MusicSender.Send(AlbumRequest model) in C:\projects\requestplex\src\Ombi.Core\Senders\MusicSender.cs:line 42
2019-01-10 17:30:11.655 +02:00 [Warning] Tried auto sending album but failed. Message: "Something went wrong!"
2019-01-10 17:30:11.655 +02:00 [Warning] Tried auto sending Album but failed. Message: "Something went wrong!"
`

**Comment by computerguy951** [comment]
Just a heads up, I was able to resolve this same issue by adding my metadata profile in the lidarr settings. It would not add the artist when making an album request until this was added....

**Comment by arcidias** [comment]
@computerguy951 ah yes, that did it! Thanks!

**Comment by neiliid** [comment]
Could you provide more detail on what "adding my metadata" to the lidarr settings involved?

Thanks in advance,

**Comment by computerguy951** [comment]
@neiliid under the settings in ombi for lidarr you need to pick a metadata profile from the drop down menu. These options are set from within lidarr settings/quality profiles/metadata profiles I'm just using the standard profile but you can create custom ones in lidarr

**Comment by rsgabriel** [comment]
@computerguy951 

I am also running 0.5.0.583 but do not seem options name "Quality Profiles"  or "Metadata Profiles"

In the sidebar, under "Settings", there are options called "Quality" and "Metadata".

"Quality" contains a list of size parameters for each corresponding quality type. There is no mentioned of metadata on this page, nor is there a combobox control.

"Metadata" contains a list of consumers which are modified by clicking on them, and selecting checkboxes. I have enabled all three. There is no combobox control on this page.

Can you be more specific about what you are referring to?

**Comment by rsgabriel** [comment]
@tidusjar - A trace shows the following responses in the Bad Request reply:

Hypertext Transfer Protocol
    HTTP/1.1 400 Bad Request\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 400 Bad Request\r\n]
            [HTTP/1.1 400 Bad Request\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Response Version: HTTP/1.1
        Status Code: 400
        [Status Code Description: Bad Request]
        Response Phrase: Bad Request
    Cache-Control: no-cache, no-store, must-revalidate\r\n
    Pragma: no-cache\r\n
    Transfer-Encoding: chunked\r\n
    Content-Type: application/json; charset=utf-8\r\n
    Expires: 0\r\n
    Server: Microsoft-HTTPAPI/2.0\r\n
    X-ApplicationVersion: 0.5.0.583\r\n
    Date: Fri, 22 Mar 2019 15:14:26 GMT\r\n
    \r\n
    [HTTP response 4/4]
    [Time since request: 0.013879000 seconds]
    [Prev request in frame: 5552]
    [Prev response in frame: 5584]
    [Request in frame: 5586]
    [Request URI: http://[removed]:8686/api/v1/artist]
    HTTP chunked response
        Data chunk (721 octets)
            Chunk size: 721 octets
            Data (721 bytes)
                Data: 5b0d0a20207b0d0a202020202270726f70657274794e616d…
                [Length: 721]
            Chunk boundary: 0d0a
        End of chunked encoding
            Chunk size: 0 octets
        \r\n
    File Data: 721 bytes
JavaScript Object Notation: application/json
    Array
        Object
            Member Key: propertyName
                String value: MetadataProfileId
                Key: propertyName
            Member Key: errorMessage
                String value: 'Metadata Profile Id' must be greater than '0'.
                Key: errorMessage
            Member Key: attemptedValue
                Number value: 0
                Key: attemptedValue
            Member Key: errorCode
                String value: greaterthan_error
                Key: errorCode
            Member Key: formattedMessageArguments
                Array
                Key: formattedMessageArguments
            Member Key: formattedMessagePlaceholderValues
                Object
                    Member Key: propertyName
                        String value: Metadata Profile Id
                        Key: propertyName
                    Member Key: propertyValue
                        Number value: 0
                        Key: propertyValue
                    Member Key: comparisonValue
                        Number value: 0
                        Key: comparisonValue
                Key: formattedMessagePlaceholderValues
            Member Key: resourceName
                String value: greaterthan_error
                Key: resourceName
        Object
            Member Key: propertyName
                String value: MetadataProfileId
                Key: propertyName
            Member Key: errorMessage
                String value: Metadata profile does not exist
                Key: errorMessage
            Member Key: attemptedValue
                Number value: 0
                Key: attemptedValue
            Member Key: formattedMessageArguments
                Array
                Key: formattedMessageArguments
            Member Key: formattedMessagePlaceholderValues
                Object
                    Member Key: propertyName
                        String value: Metadata Profile Id
                        Key: propertyName
                    Member Key: propertyValue
                        Number value: 0
                        Key: propertyValue
                Key: formattedMessagePlaceholderValues

**Comment by rsgabriel** [comment]
@tidusjar This error was occurring (for me) because "Metadata Profile" setting was blank in Ombi.

**Comment by 3urningChrome** [comment]
not obvious, but adding metadata did the trick for me too. 
Thanks for sharing people.

**Comment by projx** [comment]
> Just a heads up, I was able to resolve this same issue by adding my metadata profile in the lidarr settings. It would not add the artist when making an album request until this was added....

Great thanks, this worked. 

For others, in Lidarr goto Settings -> Meta Data .. I found 2 things I needed to do:

1) Enable Tag Audio Files
2) Enable a Metadata Consumer, for me, I enabled the Kodi/Emby

Then it, started working... awesome, thank you!
