### ISSUE TITLE
User Importer failing with NullReferenceException

### ISSUE THREAD

**Issue by doweaver** [Ombi-app/Ombi#3232]
**Describe the bug**
When I run the user importer manually to attempt to import Plex users, nothing happens in the WebUI. If I look at the logs, I see a NullReferenceException being thrown

**To Reproduce**
1. Go to 'Configuration -> User Importer
2. Click on 'Run Importer'

**Expected behavior**
Plex users to be imported

**Logs (Logs directory where Ombi is located)**
[log-20191029.txt](https://github.com/tidusjar/Ombi/files/3784248/log-20191029.txt)

2019-10-29 00:00:00.840 -07:00 [Error] StatusCode: UnprocessableEntity, Reason: Unprocessable Entity, RequestUri: https://plex.tv/users/account.json
2019-10-29 00:00:00.841 -07:00 [Error] Job Plex.IPlexUserImporter threw an unhandled Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass7_0.<ImportAdmin>b__0(OmbiUser x) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 137

**Desktop (please complete the following information):**
Linux 4.19.56-Unraid #1 SMP Tue Jun 25 10:19:34 PDT 2019

**Ombi Version (please complete the following information):**
3.0.4817

- Media Server [e.g. Plex]
Plex

**Comment by PowerShellCrack** [comment]
**Describe the bug**
Running the user importer manually to attempt to import Plex NEW usersdoes nothing. The log is erroring: 

```
[Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/friends/all/
[Error] Job Plex.IPlexUserImporter threw an unhandled Exception: 
```
**Checks**
I went to Media Server-->Plex and logged in successfully. all movies/tv are sync'd.
Users that are still loaded can login in just fine

**To Reproduce**
If I got the link: _https://plex.tv/pms/friends/all/_
Is says:
```
<errors>
<error>Please sign in.</error>
</errors>
```

**Steps to reproduce the behavior:**

Go to 'Configuration -> User Importer
Click on 'Run Importer'
**Expected behavior**
Plex users to be imported

Logs c:\ombi\logs\log-20191222.txt
[](2019-12-22 01:07:31.963 -05:00 [Debug] Batch acquisition of 1 triggers
2019-12-22 01:07:31.965 -05:00 [Debug] Batch acquisition of 0 triggers
2019-12-22 01:07:31.965 -05:00 [Debug] Calling Execute on job Plex.IPlexUserImporter
2019-12-22 01:07:31.965 -05:00 [Debug] Batch acquisition of 1 triggers
2019-12-22 01:07:31.965 -05:00 [Debug] Batch acquisition of 0 triggers
2019-12-22 01:07:31.965 -05:00 [Debug] Calling Execute on job Emby.IEmbyUserImporter
2019-12-22 01:07:31.968 -05:00 [Debug] Trigger instruction : DeleteTrigger
2019-12-22 01:07:31.968 -05:00 [Debug] Deleting trigger
2019-12-22 01:07:36.987 -05:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/pms/friends/all/
2019-12-22 01:07:36.989 -05:00 [Error] Job Plex.IPlexUserImporter threw an unhandled Exception: 
System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 93
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 63
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-12-22 01:07:36.990 -05:00 [Error] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 93
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 63
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <errors xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 93
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 84
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexUserImporter.cs:line 63
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
)


**Desktop (please complete the following information):**
Windows 10 Pro (1903) 

**Ombi Version (please complete the following information):**
3.0.4892

**Media Server**
Plex Version 1.18.3.2156

**Bypass question**
Can I just load the user in manually? Do I leave thier password blank? will they be able to OAuth sign in?

**Comment by Popupkiller** [comment]
I also get this error when trying to manually start a user import.
```
fail: Ombi.Api.Api[1000]
      StatusCode: UnprocessableEntity, Reason: Unprocessable Entity, RequestUri: https://plex.tv/users/account.json
```

**Comment by twanariens** [comment]
Fixed with latest Ombi version and latest Plex version
