### ISSUE TITLE
Can't open the "failed requests" page

### ISSUE THREAD

**Issue by Numynum** [Ombi-app/Ombi#3327]
first off: I'm loving Ombi so far, keep up the good work!

**Describe the bug**
When I go to the failed requests list in the web interface (URL/Settings/FailedRequests); I don't see anything, and I get an error in the error log
There was an issue between Radarr and Ombi (I missed the baseurl setting), which caused a few movies to go to the retry queue according to email notifications. But I can't see anything in the queue.

**Expected behavior**
I'm expecting to see about 4 movies in the failed requests list

**Screenshots**
![image](https://user-images.githubusercontent.com/17293527/71644198-bfb8e880-2cc4-11ea-99b8-2e903844885f.png)

**Logs (Logs directory where Ombi is located)**
`[Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.RequestRetryController.GetFailedRequests() in C:\projects\requestplex\src\Ombi\Controllers\RequestRetryController.cs:line 75
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24`

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2

**Ombi Version (please complete the following information):**
 - Version 3.0.4892 
- Media Server: Plex

**Comment by rafael-maia09** [comment]
Any workaround for this issue ?
Sometimes I have failed requests that I want to retry or take some action, but I don't see them. Found the same error at the log today.
I'm using the 4.0.739.0 version ( docker ) that was upgraded from other versions.
Thank you.

**Comment by Numynum** [comment]
I've not found any workaround, but never looked for one either to be honest

**Comment by rafael-maia09** [comment]
I'm using the discord notifications to find if there errors. When I do, I delete the old request and make a new one. This usually works, but I have to always keep an eye at the notifications.

**Comment by twanariens** [comment]
This has been fixed in the latest Ombi V4 version
