### ISSUE TITLE
User login with Emby authentication gives "Incorrect username or password"

### ISSUE THREAD

**Issue by IvanWaterman** [Ombi-app/Ombi#3763]
**Describe the bug**
I am running Ombi in Docker using the 'linuxserver/ombi:v4-preview' Docker image.
Besides that I am also running Emby in a Docker container.

Since a month I am not able to have user loging with their Emby account to Ombi.
It returns a "Incorrect username or password" from the Ombi login page.
I can login using a Ombi (admin) account, and with that I can see that the connection to Emby is working.
When pressing the "Test connectivity" button it passes!

**To Reproduce**
1. Go to 'Ombi login page'
2. Fill in'Emby user credentials'
3. Type enter
4. See error 'Incorrect username or password'

**Expected behavior**
Login successful

**Screenshots**
N.A.

**Logs (Logs directory where Ombi is located)**
```
2020-09-14T18:26:25.038702368Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2020-09-14T18:26:25.071850189Z [s6-init] ensuring user provided files have correct perms...exited 0.
2020-09-14T18:26:25.072723227Z [fix-attrs.d] applying ownership & permissions fixes...
2020-09-14T18:26:25.073485724Z [fix-attrs.d] done.
2020-09-14T18:26:25.073878559Z [cont-init.d] executing container initialization scripts...
2020-09-14T18:26:25.074650660Z [cont-init.d] 01-envfile: executing...
2020-09-14T18:26:25.078690942Z [cont-init.d] 01-envfile: exited 0.
2020-09-14T18:26:25.079192361Z [cont-init.d] 10-adduser: executing...
2020-09-14T18:26:25.134939411Z
2020-09-14T18:26:25.134952495Z -------------------------------------
2020-09-14T18:26:25.134955570Z           _         ()
2020-09-14T18:26:25.134957941Z          | |  ___   _    __
2020-09-14T18:26:25.134960010Z          | | / __| | |  /  \
2020-09-14T18:26:25.134962172Z          | | \__ \ | | | () |
2020-09-14T18:26:25.134964470Z          |_| |___/ |_|  \__/
2020-09-14T18:26:25.134966624Z
2020-09-14T18:26:25.134968609Z
2020-09-14T18:26:25.134970612Z Brought to you by linuxserver.io
2020-09-14T18:26:25.134972695Z -------------------------------------
2020-09-14T18:26:25.134974798Z
2020-09-14T18:26:25.134976834Z To support the app dev(s) visit:
2020-09-14T18:26:25.135471886Z Ombi - Patreon: https://patreon.com/tidusjar
2020-09-14T18:26:25.135479646Z Ombi - PayPal: https://paypal.me/PlexRequestsNet
2020-09-14T18:26:25.135594988Z
2020-09-14T18:26:25.135602487Z To support LSIO projects visit:
2020-09-14T18:26:25.135605313Z https://www.linuxserver.io/donate/
2020-09-14T18:26:25.135607527Z -------------------------------------
2020-09-14T18:26:25.135609654Z GID/UID
2020-09-14T18:26:25.135611725Z -------------------------------------
2020-09-14T18:26:25.138067899Z
2020-09-14T18:26:25.138075616Z User uid:    500
2020-09-14T18:26:25.138078318Z User gid:    100
2020-09-14T18:26:25.138080522Z -------------------------------------
2020-09-14T18:26:25.138082702Z
2020-09-14T18:26:25.141339716Z [cont-init.d] 10-adduser: exited 0.
2020-09-14T18:26:25.141948023Z [cont-init.d] 30-config: executing...
2020-09-14T18:26:25.146175592Z [cont-init.d] 30-config: exited 0.
2020-09-14T18:26:25.146793118Z [cont-init.d] 99-custom-scripts: executing...
2020-09-14T18:26:25.151958999Z [custom-init] no custom files found exiting...
2020-09-14T18:26:25.152397128Z [cont-init.d] 99-custom-scripts: exited 0.
2020-09-14T18:26:25.152843054Z [cont-init.d] done.
2020-09-14T18:26:25.153356806Z [services.d] starting services
2020-09-14T18:26:25.160190957Z [services.d] done.
2020-09-14T18:26:25.320741680Z �]0;Ombi�Hello, welcome to Ombi
2020-09-14T18:26:25.320759162Z Valid options are:
2020-09-14T18:26:25.320762165Z Ombi 4.0.477
2020-09-14T18:26:25.320764330Z Copyright (C) 2020 Ombi
2020-09-14T18:26:25.320766471Z
2020-09-14T18:26:25.320768573Z   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
2020-09-14T18:26:25.320770758Z                URL prefixes to which the server should respond. For example,
2020-09-14T18:26:25.320772898Z                http://localhost:123. Use "localhost" to indicate that the server
2020-09-14T18:26:25.320775199Z                should listen for requests on any IP address or hostname using
2020-09-14T18:26:25.320777526Z                the specified port and protocol (for example,
2020-09-14T18:26:25.320779694Z                http://localhost:5000). The protocol (http:// or https://) must
2020-09-14T18:26:25.320781841Z                be included with each URL. Supported formats vary between
2020-09-14T18:26:25.320783971Z                servers.
2020-09-14T18:26:25.320785990Z
2020-09-14T18:26:25.320787989Z   --storage    Storage path, where we save the logs and database
2020-09-14T18:26:25.320790163Z
2020-09-14T18:26:25.320792227Z   --baseurl    The base URL for reverse proxy scenarios
2020-09-14T18:26:25.320794321Z
2020-09-14T18:26:25.320796339Z   --demo       Demo mode, you will never need to use this, fuck that fruit
2020-09-14T18:26:25.320798585Z                company...
2020-09-14T18:26:25.320800683Z
2020-09-14T18:26:25.320802689Z   --help       Display this help screen.
2020-09-14T18:26:25.320804765Z
2020-09-14T18:26:25.320806781Z   --version    Display version information.
2020-09-14T18:26:25.320808905Z
2020-09-14T18:26:25.320810882Z
2020-09-14T18:26:25.320812863Z
2020-09-14T18:26:25.913619848Z We are running on
2020-09-14T18:26:25.953352030Z /opt/ombi
2020-09-14T18:26:55.957499104Z fail: Ombi.Api.Api[1000]
2020-09-14T18:26:55.957517597Z       StatusCode: NotFound, Reason: Not Found, RequestUri: https://connect.emby.media/service/user/authenticate
2020-09-14T18:26:55.979057475Z fail: Ombi.ErrorHandlingMiddleware[0]
2020-09-14T18:26:55.979073377Z       Something bad happened, ErrorMiddleware caught this
2020-09-14T18:26:55.979076384Z System.NullReferenceException: Object reference not set to an instance of an object.
2020-09-14T18:26:55.979087142Z    at Ombi.Core.Authentication.OmbiUserManager.CheckEmbyPasswordAsync(OmbiUser user, String password) in /home/vsts/work/1/s/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 154
2020-09-14T18:26:55.979090954Z    at Ombi.Core.Authentication.OmbiUserManager.CheckPasswordAsync(OmbiUser user, String password) in /home/vsts/work/1/s/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 84
2020-09-14T18:26:55.979093452Z    at Ombi.Controllers.V1.TokenController.GetToken(UserAuthModel model) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/TokenController.cs:line 68
2020-09-14T18:26:55.979095757Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2020-09-14T18:26:55.979098223Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2020-09-14T18:26:55.979100913Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-14T18:26:55.979106545Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2020-09-14T18:26:55.979109098Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2020-09-14T18:26:55.979111660Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-14T18:26:55.979114273Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-14T18:26:55.979117425Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2020-09-14T18:26:55.979119718Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2020-09-14T18:26:55.979122105Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-14T18:26:55.979124653Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2020-09-14T18:26:55.979127414Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2020-09-14T18:26:55.979129795Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2020-09-14T18:26:55.979132028Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2020-09-14T18:26:55.979136175Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2020-09-14T18:26:55.979138514Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2020-09-14T18:26:55.979140727Z    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
2020-09-14T18:26:55.979143051Z    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Linux 4.19.143-flatcar, Docker container

**Ombi Version (please complete the following information):**
 - Version 4.0.477.0
- Media Server Emby (in Docker) 4.4.3.0.
- Database Type: default, no (external) database configured

**Additional context**
Also did a clean setup where I reconfigured Ombi from scratch but still it doesn't work. 

I am curious how the 'https://connect.emby.media/service/user/authenticate' url is used, I do have an Emby connect account but I do not use it. I would expect that Ombi and Emby communicate directly with each other using the Emby API.

**Comment by tidusjar** [comment]
That is calling out to authenticate you with an Emby Connect, so your Emby account must be an emby connect account and not just a local account?

**Comment by IvanWaterman** [comment]
Currently I have these accounts:

- Ombi admin account
- Emby (local) admin account (this is not an EmbyConnect account nor is it linked to EmbyConnect)
- Emby (local) user account (this is not an EmbyConnect account nor is it linked to EmbyConnect)
- EmbyConnect account

Until now I could login to Ombi with the 'Ombi admin account', 'Emby (local) admin account' and 'Emby (local) user account'
I never had to setup or use the 'EmbyConnect account' (therefor my suprise why Ombi is reaching out to EmbyConnect).

I do see that i 'can' link my local emby account(s) to an EmbyConnect account (from the Emby user manager).
But I have not done so.

**Comment by IvanWaterman** [comment]
@tidusjar with either emby connect or emby local users. 
This should just work. What can I try to figure out where the problem is?

**Comment by tidusjar** [comment]
Sorry been real busy with IRL recently. 

Ok can you please inspect the Ombi.db file (sqlite) and check the User type column in the AspNetUsers table for the users in question and post it on here?

**Comment by IvanWaterman** [comment]
`sqlite> select Id, Username, UserType from AspNetUsers;`
```
Api|0
admin|1
xxxx|4
yyyy|4
yyyy|4
yyyy|4
yyyy|4
yyyy|4
yyyy|4
yyyy|4
yyyy|4
|4
```

I replaced the usernames here, xxxx is an Emby Connect user, yyyy is an Emby local user and the last one is blank..?
But I have recently played with configuring Emby Connect for an Emby local user (which might now be the xxxx user)

**Comment by IvanWaterman** [comment]
Oke I fixed my problem thanks to your help to inspect the Ombi.db.

When manually removing an user from the `AspNetUsers` table and importing it again, the user was able to login again.

I did for all users:
`delete from AspUserNet where Username="yyyy";`
or
`delete from AspUserNet where Alias="yyyy";`

Then went to Ombi webinterface and logged in as admin.
`Settings -> Configuration -> User Management -> Run Importer (Button)`
_Note: Make sure "Import Emby Users" check mark is checked, and of course an Emby Server is configured_

Result:
`select Username, UserType, Alias from AspNetUsers;`
```
Api|0|
admin|1|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
yyyy|3|
```
The UserType changed for all Emby local users (yyyy) to '3' and no Aliases are filled in anymore.

**Comment by rob1998** [comment]
I've got some local Emby users who can't login anymore after updating to v4.
If I look at the network log I can see 2 requests:
First a post request to "api/v1/token/requirePassword", which has `true` as response text with code 200
Then a post request to "api/v1/token/", which has `{"error":"Object reference not set to an instance of an object."}` as response text with code 500
This results in a `Incorrect username or password` error for the user.

In the backend log I see the following:

```2020-11-01 18:02:19.112 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://connect.emby.media/service/user/authenticate
2020-11-01 18:02:19.115 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Authentication.OmbiUserManager.CheckEmbyPasswordAsync(OmbiUser user, String password) in /home/vsts/work/1/s/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 154
   at Ombi.Core.Authentication.OmbiUserManager.CheckPasswordAsync(OmbiUser user, String password) in /home/vsts/work/1/s/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 84
   at Ombi.Controllers.V1.TokenController.GetToken(UserAuthModel model) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/TokenController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30```
   
I tried manually changing the user's type to 3 instead of 4, but that didn't help. Kinda don't wanna delete the users.

**Comment by rob1998** [comment]
nvm I was stupid, manually changing user type to 3 worked

**Comment by acollierr17** [comment]
> nvm I was stupid, manually changing user type to 3 worked

Would like to also confirm that changing the user type to `3` in the Ombi users table for a local Emby user account login does work.

**Comment by SosthenG** [comment]
> > nvm I was stupid, manually changing user type to 3 worked
> 
> Would like to also confirm that changing the user type to `3` in the Ombi users table for a local Emby user account login does work.

For Jellyfin, I tried to change the user type to `5` and it didn't worked. I tried 3 also (it was 4 before the migration).
I just deleted the few users I had and imported them again, but someone might want to know a better way.

**Comment by samuelmcconnell** [comment]
I'm seeing the same thing on 4.0.1342 after updating from 3.x. All of my Emby users were imported as EmbyConnect, but they're all local Emby users and can no longer log in.

How do I change the user type in the Ombi users table?

**Comment by samuelmcconnell** [comment]
I was able to figure out how to change the user type from '4' to '3' in my Ombi.db. This restored access to all my imported Emby users.

To reiterate, this happened at the time of upgrade from 3.x to 4.0.1342.

**Comment by gtxr23** [comment]
Another thing to look out for which took me a while to notice, is make sure you haven't locked the emby users devices/limit as it wont allow you to log into ombi an your phone for eg

**Comment by sho-87** [comment]
Im having the same issue

Is there a way to fix this without manually altering the database?

**Comment by SKELLETON** [comment]
My local emby users were also converted to emby connect users after updating from the old v3 Debian repository to the v4 develop one.
Manually editing the user type in the database fixed the issue.
