### ISSUE TITLE
not able to connect to sickchill

### ISSUE THREAD

**Issue by godofjesters** [Ombi-app/Ombi#3810]
**Describe the bug**
i'm using the docker container for both ombi and sickchill. it was working until a recent update to sickchill. i noticed my tv requests were not getting through so when i attempted to test the connection i got nothing but a message saying cannot connect to sickrage

**To Reproduce**
1. Go to Settings in ombi
2. Select Sickrage from the TV menu
3. Enter in your info and click on Test Connectivity
4. Get message: We Could Not Connect to Sickrage

**Expected behavior**
When a tv series is requested, i should get a notice via pushbullet and it should go through to sickchill (fork of sickrage).

**Screenshots**

**Logs (Logs directory where Ombi is located)**

fail: Ombi.Controllers.External.TesterController[1000]
      Could not test SickRage
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.SickRage.SickRageApi.Ping(String apiKey, String baseUrl) in C:\projects\requestplex\src\Ombi.Api.SickRage\SickRageApi.cs:line 87
   at Ombi.Controllers.External.TesterController.SickRage(SickRageSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 425

**Desktop (please complete the following information):**
 - OS: Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) (inside a Docker Container)

**Ombi Version (please complete the following information):**
 - Version 3.0.5202
- Media Server [Plex]
- Database Type: 

Ombi Database | Sqlite - Data Source=/config/Ombi.db
-- | --
External Database | Sqlite - Data Source=/config/OmbiExternal.db
Settings Database | Sqlite - Data Source=/config/OmbiSettings.db

**Comment by tidusjar** [comment]
My only assumption is that SickChill has made an API change that now has rendered Ombi incompatible, can you just double check the settings in Ombi to ensure it's all correct including the baseurl if present?

**Comment by godofjesters** [comment]
only setting change i made was to the API key because i thought that was what was causing it. i copied over the new key and everything else should be working as usual. is there any other information i can get for you? i love using ombi and sickchill. i tried to switch to sonarr and it is confusing and not able to grab box sets of shows instead of one at a time which is highly annoying.

**Comment by tidusjar** [comment]
You sure the host/port/baseurl are all correct? re-looking at the stacktrace it's the Ping request failing, that's the basic check we do to check if we can successfully connect

**Comment by godofjesters** [comment]
honestly i've never had to set up a base url so i don't know what to add in there for that but everything else have not been changed, still points to the local ip, and correct port. what info can i show you to verify?

**Comment by godofjesters** [comment]
ok, can close this as the apparently i had the api key incorrect. i fixed that and now it shows it can connect to sickrage. it was user error :) my bad and thank you for helping me! now i just need to figure out why it's not submitting shows, i'm getting a different error:

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.Int32]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'data', line 1, position 11.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.SickRage.SickRageApi.GetSeasonList(Int32 tvdbId, String apikey, String baseurl) in C:\projects\requestplex\src\Ombi.Api.SickRage\SickRageApi.cs:line 115
   at Ombi.Schedule.Jobs.SickRage.SickRageSync.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\SickRage\SickRageSync.cs:line 63

**Comment by janmatias** [comment]
I have an issue with sickchill as well.
When I test the connection Omni says it is successful. It is also able to send the request it seems. But in the sickchill logs I then get an exception (see bellow) and nothing happens.
Maybe this is actually an issue with sickchill?

‘’’ 
2020-10-17 08:20:54 INFO :: WEBSERVER :: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
    cur_out_dict = to_call.run()  # call function and get response
  File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
    raise ApiError("Invalid Status")
sickchill.views.api.webapi.ApiError: Invalid Status
‘’’

**Comment by tstormgit** [comment]
Same issue as janmatias over here

**Comment by himpich** [comment]
While that should be opened as a new issue, I have the same problem as JanMatias when adding a new show via an ombi Request
Sickchill Version v2020.10.22-2
Ombi Version 4.0.681.0

```
AA sickchill.views.api.webapi.ApiError: Invalid Status
AA raise ApiError("Invalid Status")
AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
2020-11-08 18:36:03 INFO :: WEBSERVER :: Traceback (most recent call last):
AA sickchill.views.api.webapi.ApiError: Invalid Status
AA raise ApiError("Invalid Status")
AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
```

**Comment by gsuave** [comment]
I am having the same problem as himpich 

AA sickchill.views.api.webapi.ApiError: Invalid Status
AA raise ApiError("Invalid Status")
AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher

**Comment by jeanpaulrh** [comment]
> I have an issue with sickchill as well.
> When I test the connection Omni says it is successful. It is also able to send the request it seems. But in the sickchill logs I then get an exception (see bellow) and nothing happens.
> Maybe this is actually an issue with sickchill?
> 
> ‘’’
> 2020-10-17 08:20:54 INFO :: WEBSERVER :: Traceback (most recent call last):
> File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
> cur_out_dict = to_call.run() # call function and get response
> File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
> raise ApiError("Invalid Status")
> sickchill.views.api.webapi.ApiError: Invalid Status
> ‘’’

Same here.

**Comment by jimmielightner** [comment]
> While that should be opened as a new issue, I have the same problem as JanMatias when adding a new show via an ombi Request
> Sickchill Version v2020.10.22-2
> Ombi Version 4.0.681.0
> 
> ```
> AA sickchill.views.api.webapi.ApiError: Invalid Status
> AA raise ApiError("Invalid Status")
> AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
> AA cur_out_dict = to_call.run() # call function and get response
> AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
> 2020-11-08 18:36:03 INFO :: WEBSERVER :: Traceback (most recent call last):
> AA sickchill.views.api.webapi.ApiError: Invalid Status
> AA raise ApiError("Invalid Status")
> AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2181, in run
> AA cur_out_dict = to_call.run() # call function and get response
> AA File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
> ```
> 
> I debugged a bit further, I think it's a sickchill bug: [SickChill/SickChill#6892](https://github.com/SickChill/SickChill/issues/6892)

I tried upgrading from V3 to V4 because of this issue. Sadly, it occurs in both versions of Ombi. The bug referenced appears to be closed, and I'm testing with the "fixed" SickChill Version that includes it: v2020.11.24-1.

**Comment by twanariens** [comment]
Seems like SickChill changed their API which renders Ombi unable to communicate correctly with SickChill

**Comment by sephrat** [comment]
Ombi does not officially support SickChill. Use another supported app.

**Comment by godofjesters** [comment]
how difficult would it be to add in support for sickchill?

**Comment by sephrat** [comment]
Given the recent activity on this issue, there doesn't seem to be a lot of traction for this app. 
We recommend using Sonarr instead which has a much larger user base.

**Comment by godofjesters** [comment]
> Given the recent activity on this issue, there doesn't seem to be a lot of traction for this app. We recommend using Sonarr instead which has a much larger user base.

sadly i agree. i'm not going to switch due to how use to sickchill i am. was able to get some kind of requests up and running using a discord bot for now so that's the best i can do. thank you for looking into it for me though!
