### ISSUE TITLE
V4 - Cannot delete failed requests from queue V4.0.681

### ISSUE THREAD

**Issue by escservices** [Ombi-app/Ombi#3870]
**Describe the bug**
A user requested a TV show, it added to Sonarr but ended up in the Failed Requests part of Ombi.  When you hit the remove button in failed requests it doesn't delete and throws console errors. 

**To Reproduce**
1. Click on Failed Requests
2. Click Remove under the queued item

**Expected behavior**
It removes the item from the queue.

**Screenshots**
![image](https://user-images.githubusercontent.com/1287511/99160749-42b61800-26b8-11eb-85d3-53c7e1803335.png)
![image](https://user-images.githubusercontent.com/1287511/99160750-477acc00-26b8-11eb-9e77-e8754f0226d3.png)

**Logs (Logs directory where Ombi is located)**

 

2020-11-14 20:17:39.426 -05:00 [Error] Something bad happened, ErrorMiddleware caught this

 System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func1 next)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/vsts/work/1/s/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2020-11-14 20:17:42.711 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:18:10.098 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:18:37.576 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:19:05.293 -05:00 [Information] Start processing HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md
2020-11-14 20:19:05.293 -05:00 [Information] Sending HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md
2020-11-14 20:19:05.305 -05:00 [Information] Received HTTP response after 12.2522ms - OK
2020-11-14 20:19:05.305 -05:00 [Information] End processing HTTP request after 12.911ms - OK
2020-11-14 20:19:07.045 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:19:33.761 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:20:03.175 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:20:32.979 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:21:02.146 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:21:31.109 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:22:00.904 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:22:24.756 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:22:51.821 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:23:17.281 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:23:40.943 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:24:04.940 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:24:30.016 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:24:56.102 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:25:21.232 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:25:45.739 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:26:08.954 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:26:33.605 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:26:38.373 -05:00 [Information] Start processing HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md
2020-11-14 20:26:38.373 -05:00 [Information] Sending HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md
2020-11-14 20:26:38.524 -05:00 [Information] Received HTTP response after 150.4086ms - OK
2020-11-14 20:26:38.524 -05:00 [Information] End processing HTTP request after 151.3535ms - OK
2020-11-14 20:27:01.389 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:27:25.002 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:27:51.539 -05:00 [Debug] Batch acquisition of 0 triggers
2020-11-14 20:28:15.251 -05:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
 - OS: Windows Server 2019

**Ombi Version (please complete the following information):**
 - Version: 4.0.681
- Media Server: Plex
- Database Type: MySQL

**Additional context**
Not sure if this helps, but this is the error associated with the request.  I'm not sure why it's even in there considering it did get added to Sonarr successfully. 
![image](https://user-images.githubusercontent.com/1287511/99160783-c7089b00-26b8-11eb-882d-ec55274ac54f.png)

**Comment by danopia** [comment]
The problem with the remove button not working is because of the `//` in the URL, it should be `/`. You can remove the record by manually sending a tweaked request. I just cleaned out my list with a script for this reason :/
