### ISSUE TITLE
Exception when attempting to send an email

### ISSUE THREAD

**Issue by palmfighter** [Ombi-app/Ombi#3897]
**Describe the bug**
Configured my mail settings, but getting an error message in the log files, no mail is send. 
Mail is configured to use Google SMTP, created a specific app password for Gmail. 

**To Reproduce**
1. Go to Settings / Notifications / Email
2. configure settings

- email enable
- enable smtp authentication
- smtp host: smtp.google.com
- smtp port: 587 (tested also 465)
- defined sender name
- configured email addresses + added password

3. Click TEST

**Expected behavior**
Test email should be received, I don't see any feedback, after a while I see this in the logs:

**Logs (Logs directory where Ombi is located)**
`2020-11-29 00:02:04.085 +01:00 [Error] Exception when attempting to send email
System.TimeoutException: The operation has timed out.
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings)
2020-11-29 00:02:04.175 +01:00 [Error] Failed to notify for notification: EmailNotification { NotificationName: "EmailNotification" }
System.TimeoutException: The operation has timed out.
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings)
   at Ombi.Notifications.GenericEmailProvider.Send(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Notifications.Agents.EmailNotification.Send(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Notifications.Agents.EmailNotification.AvailableRequest(NotificationOptions model, EmailNotificationSettings settings)
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings)
   at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model)
   at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model)`

**Desktop (please complete the following information):**
 - OS: MacOS - Safari browser

**Ombi Version (please complete the following information):**
 - Version 4.0.731.0
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Running on Docker image from Linuxserver.io.

**Comment by natephysics** [comment]
I have the exact same error.

**Describe the bug**
Set the app up to use Google SMTP. When I click test I get no feedback from Ombi and the email is never sent. An error appears in the logs. 

**To Reproduce**
Steps to reproduce the behavior:
I set up my google account with 2fa and set up an app password for email. I set up this google account for this purpose, so everything else is default.

Installed a fresh copy of Ombi 4.0.731.0 on Ubuntu 20.04.1 LTS using an Nginx reverse proxy. 

Notifications > Email Notifications
Enable [on]
Enable SMTP Authentication [on]
Disable TLS/SSL [off] (also tested with [on])
Disable Centifitaion Checking [on] (also tested with [off])

**SMTP Host:** smtp.gmail.com
**SMTP Port** 587 (also tried 465)
**Email Sender** myemailaddress@gmail.com
**Sender Name** My name
**Admin Email** My personal email address
**Username** myemailaddress@gmail.com
**Password** the google app password I made for Ombi

Hit submit to save, then Test. 

**Expected behavior**
Some feedback? Email should be sent to (I assume) the admin email address. 

**I see the following error in the logs:**
2020-11-29 10:37:09.335 +00:00 [Warning] Exception when testing Email Notifications
System.TimeoutException: The operation has timed out.
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings)

**Desktop (please complete the following information):**

**OS:** I'm accessing Ombi over the web using Google Chrome Version 87.0.4280.66 (Official Build) (64-bit) on Windows 10 Pro Version 2004 (Build 12041.630)


Ombi Version (please complete the following information):
Version 4.0.731.0
Media Server Plex (but I doubt it's relevant)

**Database Type:** 
SQLite

**Additional context**
Server is linode VPS running Ubuntu 20.04.1 LTS using an Nginx reverse proxy.

**Comment by palmfighter** [comment]
Answering my own one ;) Perhaps need to change Gmail setting to accept lower security clients. I however changed to a different SMTP server and working fine now.

**Comment by natephysics** [comment]
> Answering my own one ;) Perhaps need to change Gmail setting to accept lower security clients. I however changed to a different SMTP server and working fine now.

What SMTP server are you using that worked?

**Comment by palmfighter** [comment]
Hi,

I used my provider one, it is called freedom.nl ;)

But as mentioned, you might need to change your gmail security settings. this is mentioned in the Ombi Wiki. 

good luck!

**Comment by PredatorVI** [comment]
Running Ombi 4.0.779.0:

I don't know if this is the same issue, but I have SMTP configured and test emails are being sent to my GMail account.  However, when I go to send a password reset link from the User Management->Details section nothing happens (no obvious error, no email received).  In the log I see the error below. 

If I hover over the send password reset email button I do see, but I don't know if that is a generic message or I missed something in the SMTP setup or if there is an error:

![image](https://user-images.githubusercontent.com/1933277/103434920-1f422080-4bc5-11eb-90ef-eb55bc2d00a6.png)

> 2020-12-31 23:57:34.861 -07:00 [Error] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Ombi.Controllers.V1.IdentityController.SubmitResetPassword(SubmitPasswordReset email)
   at lambda_method1379(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)

**Comment by 3rdStng** [comment]
Similar issue happening with me. I setup the SMTP setting within Ombi v3 and everything tested OK. I upgraded to v4 and the SMTP notifications stopped working.

**Comment by tidusjar** [comment]
@3rdStng your error looks like it's due to a base application URL set. 

Check your application URL in your customisation settings. 

For using Gmail, I am currently using Gmail with 2fa for all of my notifications and it's working correctly with no issues

**Comment by 3rdStng** [comment]
> @3rdStng your error looks like it's due to a base application URL set.
> 
> Check your application URL in your customisation settings.
> 
> For using Gmail, I am currently using Gmail with 2fa for all of my notifications and it's working correctly with no issues

Thanks. I ended up blowing my docker away and starting over from scratch with v3. I backed up my docker settings and then upgraded to v4 and the email worked this time. Not sure how or what happened the first time. I don't believe I ever set a base URL on my first attempt. But maybe it was pulled in during the upgrade? Again, don't know and it works now. Thanks again for the reply.
