### ISSUE TITLE
V4 - User Permissions randomly changing

### ISSUE THREAD

**Issue by CanonCan** [Ombi-app/Ombi#3922]
**Describe the bug**
I have all of my Plex users imported and set for Request TV, Movies and Music, Auto Approve TV, Movies and Music and Manage own requests. occasionally about every few days i get a message from a user they cant request anything or something like a movie or tv show. when i log into Ombi I see many permissions are missing from multiple users

**Expected behavior**
I expect when using bulk edit or manual edit of a user that it sticks and does revert to some seemly random set of permissions

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: unRAID

**Ombi Version (please complete the following information):**
 - Version 4.0.739.0 (docker)

- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
sorry unable to grab logs at this time

**Comment by tidusjar** [comment]
Not sure how this would happen,

do you have any accurate repro steps?

**Comment by CanonCan** [comment]
Hi

sorry it seesm so random i think its the bulk edit tool only mapping some permissions to some user and removing permissions to others...I went through and manually fixed all 79 users one by one this morning and so far it stable

i am checking back on it from time to time but noticed sometimes its it takes days to revert

**Comment by tidusjar** [comment]
Still an issue?

**Comment by CanonCan** [comment]
I will have to test it again by doing an all user change.

The problem is I have about 80 users so if it locks up it takes a while to fix, doing one at a time

**Comment by jpartain89** [comment]
I'm having this same issue, with this being the error output:
(NOTE: I am using a MariaDB setup for the database)

```
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]: fail: Ombi.ErrorHandlingMiddleware[0]
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:       Something bad happened, ErrorMiddleware caught this
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:       System.NullReferenceException: Object reference not set to an instance of an object.
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Ombi.Controllers.V1.IdentityController.UpdateUser(UserViewModel ui)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at lambda_method730(Closure , Object )
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
Jan 10 21:02:36 rpi35.home.jpcdi.com Ombi[17321]:          at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]: fail: Ombi.ErrorHandlingMiddleware[0]
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:       Something bad happened, ErrorMiddleware caught this
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:       System.NullReferenceException: Object reference not set to an instance of an object.
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Ombi.Controllers.V1.IdentityController.UpdateUser(UserViewModel ui)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at lambda_method730(Closure , Object )
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
Jan 10 21:02:38 rpi35.home.jpcdi.com Ombi[17321]:          at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)

**Comment by tidusjar** [comment]
What were you doing to get that error?

**Comment by CanonCan** [comment]
Hi Jaime just tested bulk edit again and see many users that I set to request and auto approve no longer get request access

Sincerely,
Michael
