### ISSUE TITLE
Cannot login with Emby anymore

### ISSUE THREAD

**Issue by francescocarzaniga** [Ombi-app/Ombi#3943]
**Describe the bug**
The feature to login with Emby does not work anymore.

**To Reproduce**
1. Setup Emby in the settings
2. Setup user importer and import users
3. Try to log in with an Emby user
4. Get incorrect username or password

**Expected behavior**
The user should be logged in

**Logs (Logs directory where Ombi is located)**

```
2020-12-26 11:52:25.777 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://connect.emby.media/service/user/authenticate
2020-12-26 11:52:25.780 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Authentication.OmbiUserManager.CheckEmbyPasswordAsync(OmbiUser user, String password)
   at Ombi.Core.Authentication.OmbiUserManager.CheckPasswordAsync(OmbiUser user, String password)
   at Ombi.Controllers.V1.TokenController.GetToken(UserAuthModel model)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version: v4.0.779
- Media Server: Emby
- Database Type: SQLite

**Additional context**
The feature was working correctly in Ombi v3. It seems that now Ombi always uses Emby Connect and ignores the actual Emby server url.

**Comment by tidusjar** [comment]
If the user is an emby connect user, it will attempt to authenticate via emby connect. What is your user type on the user management screen?
