### ISSUE TITLE
unable to send mail SSL/TLS

### ISSUE THREAD

**Issue by fred-gb** [Ombi-app/Ombi#3948]
Hello,

**Describe the bug**
Unable to configure SSL/TLS. 

**To Reproduce**
Settings > Notifications > Emails notifications
And fill forms.

**Expected behavior**
Sending mails with SSL/TLS.

**Logs (Logs directory where Ombi is located)**
```
warn: Ombi.Controllers.External.TesterController[0]
      Exception when testing Email Notifications
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi.Notifications\GenericEmailProvider.cs:line 87
   at Ombi.Controllers.External.TesterController.Email(EmailNotificationSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 277
```

**Desktop (please complete the following information):**
Client: Any OS

**Ombi Version (please complete the following information):**
 - Version: 3.0.5223 (docker-compose network_mode: host)
- Media Server: Plex
- Database Type: SQLite

**Additional context**
When I check:
Disable TLS/SSL
Disable Certificate Checking

It's work, but my mails are rejected, detection spam from server.

I know in logs there are:
```
The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.
```

But my mails configuration works with other client mails like Thunderbird?

Certainly somthing I misunderstood from docker.

Thanks

**Comment by tidusjar** [comment]
The error comes back when the main server does not support SSL on your specified port

**Comment by fred-gb** [comment]
Thanks,
ok, my mail hoster doesn't support SSL, only STARTTLS.

**Comment by zotflix** [comment]
Version: 
4.0.1040.0

I seem to be having the same issue. Verified with my provider that they support SSL and was able to test successfully in other applications (Outlook). 

Thank you for your time. 

Logs attached
[log-20210129.txt](https://github.com/Ombi-app/Ombi/files/5897358/log-20210129.txt)

**Comment by Berjou** [comment]
I can confirm this problem too. I have the same SSL error, trying to send email with TLS support on port 465 or 587. Sending emails to these ports works as expected with my other services (radarr/sonarr/etc...).

**Comment by sifotes** [comment]
Still an issue. Also trying with a mail host that only supports SMTP on STARTTLS, can only get it to work after disabling certificate checking. Cert is confirmed to be valid.

**Comment by Berjou** [comment]
The docker image I'm using (linuxserver/ombi) recently updated to version 4 (currently 4.0.1342), and that fixed the issue for me.

**Comment by sifotes** [comment]
Thank you @Berjou , can confirm v4 has fixed this for me as well.
