### ISSUE TITLE
Error using forgot password function

### ISSUE THREAD

**Issue by halorrr** [Ombi-app/Ombi#3979]
**Describe the bug**
Out of no where my password stopped working for my account, when I try to reset it by entering in my email an error is thrown.

**To Reproduce**
1. Go to login page and click `Forgot your password?`
2. Enter in a valid email for password reset
3. Get no visual feedback on page. Error is displayed in logs though

**Expected behavior**
Be able to reset my password

**Screenshots**
Console error:
![image](https://user-images.githubusercontent.com/1358708/104832500-83b8dd00-585f-11eb-914b-cc5e1ebc8a8e.png)

**Logs (Logs directory where Ombi is located)**
```
[41m[30mfail[39m[22m[49m: Ombi.Notifications.GenericEmailProvider[0]
Exception when attempting to send an email
System.InvalidOperationException: This operation is not supported for a relative URI.
at System.Uri.get_IdnHost()
at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
[41m[30mfail[39m[22m[49m: Ombi.ErrorHandlingMiddleware[0]
Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: This operation is not supported for a relative URI.
at System.Uri.get_IdnHost()
at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
at Ombi.Controllers.V1.IdentityController.SubmitResetPassword(SubmitPasswordReset email)
at lambda_method710(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
```

**Desktop (please complete the following information):**
 - OS: macOS 11.1 (Big Sur)

**Ombi Version (please complete the following information):**
 - Version: 4.0.975
- Media Server: Plex
- Database Type: SQLite

**Additional context**
There shouldn't have been any issues with my password to begin with so this is all quite strange.

**Comment by tidusjar** [comment]
Your application URL is probably not set correctly

**Comment by halorrr** [comment]
Is there a way I can fix/check that if that is the case? I can't get past the login screen and haven't changed any settings.

**Comment by tidusjar** [comment]
The only way would be to manually edit your database and set the application URL.

If you have the capability to do this, It's in the `OmbiSettings.db` database under the `GlobalSettings` table with the SettingsName of `Customization Settings`

**Comment by halorrr** [comment]
Hmmm confirmed my ApplicationUrl was correct in the DB, I even tried adding the https:// in front to see if that will help but I'm still getting the same error

**Comment by halorrr** [comment]
Figured it out! It was this https://github.com/Ombi-app/Ombi/issues/3894

Apparently v3 wasn't working well with my 2FA on my Plex account. I had to enter the password as pass2FAcode like in that issue and I was able to log in again. I'm guessing it was also what was causing the password reset to fail.

**Comment by jj-uk** [comment]
Does password reset work for you? I get this error:

https://github.com/Ombi-app/Ombi/issues/3915

**Comment by halorrr** [comment]
@jj-uk it does not, but once I figured out the way to get my actually password to work it ended up not being relevant for me
