### ISSUE TITLE
Fresh install, search isnt working

### ISSUE THREAD

**Issue by Clickbaitcake** [Ombi-app/Ombi#3983]
**Describe the bug**
My ombi instance stopped working randomly, I thought I broke it somehow so decided to do fresh install. I deleted the entire folder where Ombi lived and started fresh. Now searching returns no results. How can this happen with a fresh install?

**To Reproduce**
1. Go to search
2. Type title
3. Nothing

**Expected behavior**
Search should bring back a list of movies fitting the title that was typed.

**Logs (Logs directory where Ombi is located)**
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
2021-01-18 20:00:00.014 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:00:00.049 +00:00 [Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
2021-01-18 20:00:00.081 +00:00 [Information] Starting Plex Content Cacher Recently Added Scan
2021-01-18 20:00:00.086 +00:00 [Information] Starting to cache the content on server "OSCAR"
2021-01-18 20:00:01.527 +00:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: True
2021-01-18 20:00:01.535 +00:00 [Debug] Trigger instruction : NoInstruction
2021-01-18 20:00:26.710 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:00:54.020 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:01:20.249 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:01:49.224 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:02:14.744 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:02:38.518 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Ombi.Api.OmbiHttpClient.GetStringAsync(Uri requestUri) in C:\projects\requestplex\src\Ombi.Api\OmbiHttpClient.cs:line 67
   at Ombi.Schedule.Processor.ChangeLogProcessor.Process(String branch) in C:\projects\requestplex\src\Ombi.Schedule\Processor\ChangeLogProcessor.cs:line 36
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.UpdateAvailable(String branch, String currentVersion) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.cs:line 55
   at Ombi.Controllers.JobController.<CheckForUpdateCached>b__5_0() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 72
   at Ombi.Helpers.CacheService.GetOrAdd[T](String cacheKey, Func`1 factory, DateTime absoluteExpiration) in C:\projects\requestplex\src\Ombi.Helpers\CacheService.cs:line 36
   at Ombi.Controllers.JobController.CheckForUpdateCached() in C:\projects\requestplex\src\Ombi\Controllers\JobController.cs:line 67
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
2021-01-18 20:02:40.947 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:03:06.741 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:03:31.391 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:03:55.507 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:04:23.487 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:04:48.395 +00:00 [Debug] Batch acquisition of 1 triggers
2021-01-18 20:05:00.001 +00:00 [Debug] Batch acquisition of 0 triggers
2021-01-18 20:05:00.001 +00:00 [Debug] Calling Execute on job Emby.IEmbyContentSync
2021-01-18 20:05:00.011 +00:00 [Debug] Trigger instruction : NoInstruction
2021-01-18 20:05:28.628 +00:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
 - OS: Windows Server 2020

**Ombi Version (please complete the following information):**
 - Version 	3.0.5223
- Media Server Plex
- Database Type: SQLite 

**Additional context**
Ive got nothing else.

**Comment by tidusjar** [comment]
Please update to v4
