### ISSUE TITLE
Upgrade from  4.0.489.0 to v4.0.994 or v4.0.999 Ombi stops working

### ISSUE THREAD

**Issue by Jahner** [Ombi-app/Ombi#3995]
**Describe the bug**

**To Reproduce**
1. Copy new files to Ombi folder
2. Download new version
3. Copy to folder overwriting existing

**Expected behavior**
Expect Ombi to not crash after starting

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Including tail end of log file. See no entries after upgrading.

2021-01-22 12:45:00.038 -06:00 [Error] Job System.IResendFailedRequests threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.FirstOrDefaultAsync(Expression`1 predicate) in /home/vsts/work/1/s/src/Ombi.Store/Repository/BaseRepository.cs:line 39
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 139
   at Ombi.Schedule.Jobs.Ombi.ResendFailedRequests.Execute(IJobExecutionContext job) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/ResendFailedRequests.cs:line 56
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/vsts/work/1/s/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.FirstOrDefaultAsync(Expression`1 predicate) in /home/vsts/work/1/s/src/Ombi.Store/Repository/BaseRepository.cs:line 39
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 139
   at Ombi.Schedule.Jobs.Ombi.ResendFailedRequests.Execute(IJobExecutionContext job) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/ResendFailedRequests.cs:line 56
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/vsts/work/1/s/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2021-01-22 12:45:00.039 -06:00 [Debug] Trigger instruction : NoInstruction
2021-01-22 12:45:28.943 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:45:52.094 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:46:15.427 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:46:42.438 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:47:09.511 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:47:37.059 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:48:02.854 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:48:29.161 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:48:53.092 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:49:22.902 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:49:49.115 -06:00 [Debug] Batch acquisition of 1 triggers
2021-01-22 12:50:00.000 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 12:50:00.000 -06:00 [Debug] Calling Execute on job System.IResendFailedRequests
2021-01-22 12:50:00.035 -06:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 277
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 139
2021-01-22 12:50:00.037 -06:00 [Error] Job System.IResendFailedRequests threw an unhandled Exception: 
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.FirstOrDefaultAsync(Expression`1 predicate) in /home/vsts/work/1/s/src/Ombi.Store/Repository/BaseRepository.cs:line 39
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 139
   at Ombi.Schedule.Jobs.Ombi.ResendFailedRequests.Execute(IJobExecutionContext job) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/ResendFailedRequests.cs:line 56
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/vsts/work/1/s/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2021-01-22 12:50:00.038 -06:00 [Error] Job System.IResendFailedRequests threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.FirstOrDefaultAsync(Expression`1 predicate) in /home/vsts/work/1/s/src/Ombi.Store/Repository/BaseRepository.cs:line 39
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 139
   at Ombi.Schedule.Jobs.Ombi.ResendFailedRequests.Execute(IJobExecutionContext job) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/ResendFailedRequests.cs:line 56
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/vsts/work/1/s/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. To show additional information call EnableSensitiveDataLogging() when overriding DbContext.OnConfiguring.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.GetValue(Expression expression, String& parameterName)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Evaluate(Expression expression, Boolean generateParameter)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.FirstOrDefaultAsync(Expression`1 predicate) in /home/vsts/work/1/s/src/Ombi.Store/Repository/BaseRepository.cs:line 39
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/vsts/work/1/s/src/Ombi.Core/Senders/TvSender.cs:line 139
   at Ombi.Schedule.Jobs.Ombi.ResendFailedRequests.Execute(IJobExecutionContext job) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/ResendFailedRequests.cs:line 56
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/vsts/work/1/s/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2021-01-22 12:50:00.039 -06:00 [Debug] Trigger instruction : NoInstruction
2021-01-22 12:50:28.992 -06:00 [Debug] Batch acquisition of 0 triggers
2021-01-22 13:34:36.275 -06:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2021-01-22 13:34:36.442 -06:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2021-01-22 13:34:36.477 -06:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2021-01-22 13:34:36.480 -06:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2021-01-22 13:34:36.481 -06:00 [Information] RAMJobStore initialized.
2021-01-22 13:34:36.486 -06:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-01-22 13:34:36.487 -06:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2021-01-22 13:34:36.487 -06:00 [Information] Quartz scheduler version: 3.1.0.0
2021-01-22 13:34:36.488 -06:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2021-01-22 13:34:36.598 -06:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2021-01-22 13:34:36.606 -06:00 [Debug] Batch acquisition of 1 triggers

**Desktop (please complete the following information):**
 - OS: Server 2019

**Ombi Version (please complete the following information):**
 - Version 4.0.489.0
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by Jahner** [comment]
Cleared out folder, extracyed new version, copied over just db and web config. Working fine now.
