### ISSUE TITLE
Discord Notifications fail with MySQL

### ISSUE THREAD

**Issue by Berserkir-Wolf** [Ombi-app/Ombi#4015]
**Describe the bug**
When attempting to configure Discord notifications and using MySQL, they fail.  
A notification on screen pops up saying "test notification sent to Discord successfully", but no notification arrives and an error is logged with a failure.

**To Reproduce**
1. Use Ombi with all databases in MySQL.
2. Go to 'Settings/Notifications/Discord'
3. Configure webhook as per usual
4. Click on 'enable'
5. Click on 'submit'
6. See error

A blank install was set up using a windows host, moving all settings from docker container. The same error occurred.
Switching to a blank database produced the same results.
A blank install using all the same settings but with sqlite instead of mysql worked successfully, with all tested instances. 
Issue only occurs when using MySQL as a database.
Tested in:
- Windows 10
- Windows Server 2019
- Ubuntu Server (apt install)
- Docker on Ubuntu Server

**Expected behavior**
A notification should appear in the nominated discord server/channel.

**Logs**
- Location: in config directory

```
    2021-01-31 22:02:15.635 +13:00 [Error] Failed to send Discord Notification
    System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
    Object name: 'SettingsMySqlContext'.
       at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
       at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
       at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
       at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
       at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
       at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
       at Ombi.Store.Repository.SettingsJsonRepository.GetAsync(String settingsName)
       at Ombi.Settings.Settings.SettingsService`1.<GetSettingsAsync>b__11_0()
       at Ombi.Settings.Settings.SettingsService`1.GetSettingsAsync()
       at Ombi.Api.OmbiHttpClient.<GetHandler>b__10_0()
       at Ombi.Api.OmbiHttpClient.GetHandler()
       at Ombi.Api.OmbiHttpClient.Setup()
       at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at Ombi.Api.Api.Request(Request request, CancellationToken token)
       at Ombi.Api.Discord.DiscordApi.SendMessage(DiscordWebhookBody body, String webhookId, String webhookToken)
       at Ombi.Notifications.Agents.DiscordNotification.Send(NotificationMessage model, DiscordNotificationSettings settings)
```

**Environment:**
 - OS: Multiple. Tested with Windows 10, Windows Server 2019, Ubuntu Server (apt install), and docker on Ubuntu Server.

**Ombi Version (please complete the following information):**
 - Version: 4.0.1040.0
- Media Server: Plex
- Database Type: MySQL (tested with live and blank databases)

**Comment by Berserkir-Wolf** [comment]
Going to test further by creating a completely fresh database instance this weekend.

**Comment by Berserkir-Wolf** [comment]
Blank version on entirely different host made no difference - still no discord notification. 

Ombi testing done on:

- docker-ce (not a snap install)
- Ubuntu 18.04.5 (LTS)
- Ubuntu 20.04 (LTS)
- Windows Server 2019
- Windows 10 Pro (x64)

Proxy tested on:

- IIS
- Apache2

MySQL tested on:

- Ubuntu 18.04
- Ubuntu 20.04
- Windows Server 2019

Network environment tested both with and without PiHole active to eliminate filtering issues.

**Comment by tidusjar** [comment]
Still same exception?

**Comment by Berserkir-Wolf** [comment]
Doesn't appear to throw an exception that I can see in the logs. At all. It just doesn't send a notification at all.

**Comment by Berserkir-Wolf** [comment]
Notification appears to be hit/miss for some, but tinkering with docker settings seems to have made it work more (tm). Still not 100%, but I only use it for testing anyway.
