### ISSUE TITLE
Can't import new users 4.0.1067.0, 4.0.991 or 4.0.975 running in Kubernetes/docker..has worked in the past.

### ISSUE THREAD

**Issue by evanrich** [Ombi-app/Ombi#4027]
**Describe the bug**

**To Reproduce**
1.) Go to Settings
2.) Click Configureation->User Managemnt
3.) Run importer
4.) Importer succeeds, but users dont get added and logs show error  below

**Expected behavior**
New Users get added to Ombi

**Logs (Logs directory where Ombi is located)**
```
 Job Plex.IPlexUserImporter threw an unhandled Exception:
System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job)
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2021-02-02 22:32:15.854 -08:00 [Error] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job)
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job)
```

**Desktop (please complete the following information):**
 - OS: docker container

**Ombi Version (please complete the following information):**
 - Version 4.0.991 or 4.0.975
- Media Server :Plex 
- Database Type: MariaDB

The last time this worked AFAIK was in October, but I may have added new users since.

**Comment by tidusjar** [comment]
Is the email address already in use?

**Comment by evanrich** [comment]
already in use in Ombi, or plex?  The user I'm trying to import is not in ombi.

**Comment by tidusjar** [comment]
The API user is needed for any one using the API key.

The error above basically means that the user being imported from Plex, there is already an account with that email address in Ombi.

**Comment by evanrich** [comment]
there definately isn't... 

users email address is ma...ng24@gmail..com, my AspNetUsers table has these:
```
**MariaDB [ombi]> select Email from AspNetUsers;
+---------------------------------+
| Email                           |
+---------------------------------+
| mo........12@gmail.com          |
| K........3@yahoo.com                 |
| ch........a@hotmail.com         |
| le........n@yahoo.com             |
| tr........d@gmail.com         |
| t.i.......n@le.org                      |
| Da........h@gmail.com     |
| ev........1@gmail.com            |
| tt........2@yahoo.com              |
| 2j........x@gmail.com               |
| er........o@gmail.com |
| ac........7@gmail.com             |
| jo........a@gmail.com          |
| ja..........n@gmail.com              |
| ac.........7@gmail.com             |
| sh.........z@gmail.com                |
| testuser@evan.com               |
| 8......ruz@gmail.com            |
| NULL                            |
+---------------------------------+
**
```

However i just noticed that I have two existing local users with the same email (one account stopped working for some reason so i created a second).  these are the ac.....7@gmail.com ones.    After that, import worked.

Thanks @tidusjar  not sure why it was working in the past, but this threw me off..  will close
