### ISSUE TITLE
Ombi runs into error after "autoupdate" on win 10

### ISSUE THREAD

**Issue by stumpyofpain** [Ombi-app/Ombi#4037]
**Describe the bug**
i did write myself an autoupdate powershell script for ombi on windows 10.
it runs every day at 1:30 am and downloads the newest version of ombi, saves the database, deletes the old ombi, unzips ombi and replaces the databases.
Everything works fine and i can access ombi and i see that it updated succesfully

after a while, i get the error message while accessing ombi, that the index is missing (see screenshot below)

**To Reproduce**
1. let the ps script run
2. wait time x (several hours?)
3. try to access ombi

**Expected behavior**
That ombi works the same as if i update it manually.

**Screenshots**
![ombi_update_error](https://user-images.githubusercontent.com/63201947/107124471-61394300-68a4-11eb-942e-c348fed2c6fe.jpg)

**Logs (Logs directory where Ombi is located)**
didnt save the log the last time.
did update it with the script right now.
as soon as i get the error, i will look into the log file.

log of the start after the autoupdate.

[startlog_ombi_autoupdate.txt](https://github.com/Ombi-app/Ombi/files/5937240/startlog_ombi_autoupdate.txt)

**Desktop (please complete the following information):**
 - OS: win 10 64 bit

**Ombi Version (please complete the following information):**
 - Version any 4 , using 4.0.1090.0 after the update right now
- Media Server emby, jellyfin, plex
- Database Type: SQLite

**Additional context**
my powershell script to autoupdate on windows 10.
Warning, make a backup of your database and change the path corresponding to your paths.

[ombi_update.txt](https://github.com/Ombi-app/Ombi/files/5937234/ombi_update.txt)

**Comment by tidusjar** [comment]
Just eyeballing the script it looks ok,

Version 1090 is currently running on app.ombi.io and working completely fine, i've checked the release artefacts and it also looks good.

You might want to check your ombi install location to see if it mirrors the zip file in the release

**Comment by stumpyofpain** [comment]
hey, i got the error again.


`2021-02-09 15:23:26.840 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_2.<Use>b__2()
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)`
