### ISSUE TITLE
Error when trying to connect to Jellyfin

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Ombi-app/Ombi#4045]
**Describe the bug**

Just extracted and launched Ombi on Raspberry Pi 4. Launches correctly, but when trying to connect to my Jellyfin server at initial setup, nothing happens on screen and I have an error in the console. (see logs below)

**To Reproduce**
Have a local Jellyfin server on Raspberry
Extract Ombi
Launch Ombi
Run Initial Setup
See bug when connecting to the media server

**Expected behavior**

Ombi should connect to my Jellyfin server without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/64923542/107196276-b97e5b00-69f2-11eb-8e1c-689b28eab603.png)
Nothing happens when clicking "next"

**Logs (Logs directory where Ombi is located)**

fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Emby.EmbyApi.GetUsers(String baseUri, String apiKey) in C:\projects\requestplex\src\Ombi.Api.Emby\EmbyApi.cs:line 33
   at Ombi.Controllers.External.EmbyController.SignIn(EmbySettings request) in C:\projects\requestplex\src\Ombi\Controllers\External\EmbyController.cs:line 52
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24

**Desktop (please complete the following information):**
 - DietPi on Raspberry Pi 4

**Ombi Version (please complete the following information):**
 - Version 3.0.5223
- Media Server Jellyfin

**Comment by jaycedk** [comment]
Try with IP address instead of localhost.

**Comment by tidusjar** [comment]
Use V4 too, Jellyfin has now split out
