### ISSUE TITLE
Request New Movie results in automatic download failure when communicating with Radarr.

### ISSUE THREAD

**Issue by mike10010100** [Ombi-app/Ombi#4048]
**Describe the bug**
Requesting a movie via Radarr results in automatic failure, which puts all movie requests into a perpetual failed request state.

In addition, I am unable to remove these failures from the retry queue.

**To Reproduce**
1. Request a movie.
2. Receive an email saying the movie has been placed in retry queue.
3. Go to system -> Failed Requests
4. Try and remove one of them, nothing happens.

**Expected behavior**
Movies to be added and requested properly from Radarr.

**Screenshots**
![image](https://user-images.githubusercontent.com/3506604/107388339-bd2de280-6ac3-11eb-888a-7b2b95affb5a.png)

**Logs (Logs directory where Ombi is located)**
```
2021-02-09 10:00:00.113 -05:00 [Error] Exception when adding new Movie "The Beach House"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 3820.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264
```

**Desktop (please complete the following information):**
 - Ombi: Docker installation on Ubuntu 20.04
 - Radarr: Synology installation via package manager

**Ombi Version (please complete the following information):**
 - Version: 3.0.5223
- Media Server: Plex
- Database Type: SQLite
- Radarr Version: 3.0.2.4369

**Additional context**
Ombi is able to communicate properly with Radarr in the connection settings and pulls up the profile list properly.

**Comment by tidusjar** [comment]
Upgrade to v4

**Comment by mike10010100** [comment]
@tidusjar, out of curiosity, is there a stable branch for that update?

**Comment by mike10010100** [comment]
In any case, I updated and this worked! Thank you so much!
