### ISSUE TITLE
Empty discover, Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by xelfer** [Ombi-app/Ombi#4056]
**Describe the bug**
My discover page is empty after my 3 to 4 upgrade. Requests and search seems to work fine. 

**To Reproduce**
1. Go to http://192.168.0.5:5000/discover
2. Result: https://i.imgur.com/zBXlnmZ.png

**Expected behavior**
A list of suggested movies.

**Screenshots**
See above

**Logs (Logs directory where Ombi is located)**
I appear to get this 3 times, I assume once for Popular, Trending and Upcoming

`2021-02-17 12:34:32.020 +11:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.Dispose()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Ombi.Store.Repository.Requests.TvRequestRepository.GetRequest(Int32 tvDbId)
   at Ombi.Core.Rule.Rules.Search.ExistingRule.Execute(SearchViewModel obj)
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj)
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model)
   at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item, Boolean includeImages)
   at Ombi.Core.Engine.TvSearchEngine.ProcessResult[T](T tvMazeSearch, Boolean includeImages)
   at Ombi.Core.Engine.TvSearchEngine.ProcessResults[T](IEnumerable`1 items, Boolean includeImages)
   at Ombi.Core.Engine.TvSearchEngine.Trending(Int32 currentlyLoaded, Int32 amountToLoad)
   at Ombi.Controllers.V2.SearchController.Trending(Int32 currentPosition, Int32 amountToLoad)
   at lambda_method696(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)`

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.7 LTS (native, not docker)

**Ombi Version (please complete the following information):**
- Version 4.0.1112.0
- Media Server Plex
- Database Type: SQLite 

**Additional context**
I recently moved from v3 to v4, I had to run `sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'` to fix a different issue where I had no images at all in search and that seems to be fixed. This seems to be my last issue after the migration. 

Thanks!

**Comment by tidusjar** [comment]
Can you try this on the latest version please?

**Comment by xelfer** [comment]
I ended up having to completely re-install. My database just wouldn't work no matter how many other suggestions I tried. 

Latest version is working from a fresh install, thanks!
