### ISSUE TITLE
V4 - Plex initial full sync does not fetch TV Shows

### ISSUE THREAD

**Issue by dinner95** [Ombi-app/Ombi#4064]
**Describe the bug**
Plex initial full sync does not fetch TV Shows.
The avability of the show is not visable on discover.

**To Reproduce**
1. Install V4 on Windows 10
2. Run Ombi as Windows service and do the initial setup without Plex
3. Connect to Plex Server and Start full sync
4. After sync is finished, movie avability is shown, but tv show avability not.

**Expected behavior**
Available TV shows should be marked as available on discover (ended TV shows with all episodes available).

**Screenshots**
![image](https://user-images.githubusercontent.com/26787776/108636025-08140680-7483-11eb-9f91-e807a657e448.png)

The Big Bang Theory is available but not marked as available.

**Log**

!Last row of the log says, that Ombi is not able to find the parent series for the episode.!
!This will repeat for every episode located on the server.!

2021-02-21 19:59:29.425 +01:00 [Information] Starting Plex Content Cacher
2021-02-21 19:59:29.425 +01:00 [Information] Starting to cache the content on server "MovieStream"
2021-02-21 19:59:56.451 +01:00 [Debug] Batch acquisition of 1 triggers
2021-02-21 20:00:00.000 +01:00 [Debug] Batch acquisition of 0 triggers
2021-02-21 20:00:00.002 +01:00 [Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
2021-02-21 20:00:00.009 +01:00 [Information] Starting Plex Content Cacher Recently Added Scan
2021-02-21 20:00:00.010 +01:00 [Information] Starting to cache the content on server "MovieStream"
2021-02-21 20:00:04.317 +01:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "MovieStream"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges()
   at Ombi.Store.Repository.BaseRepository`2.AddRange(IEnumerable`1 content, Boolean save)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)
2021-02-21 20:00:04.319 +01:00 [Information] Starting EP Cacher
2021-02-21 20:00:04.320 +01:00 [Debug] Batch acquisition of 1 triggers
2021-02-21 20:00:04.320 +01:00 [Debug] Batch acquisition of 0 triggers
2021-02-21 20:00:04.320 +01:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: False
2021-02-21 20:00:04.321 +01:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2021-02-21 20:00:04.321 +01:00 [Debug] Trigger instruction : DeleteTrigger
2021-02-21 20:00:04.322 +01:00 [Debug] Deleting trigger
2021-02-21 20:00:05.343 +01:00 [Information] Total Epsiodes found for TV-Serien = 30530
2021-02-21 20:00:05.360 +01:00 [Warning] The episode title "Reboot in Brooklyn" we cannot find the parent series. The episode grandparentKey = 25327, grandparentTitle = "2 Broke Girls"

**KVM Virtuozzo VM:**
 - 16 Core AMD EPYC 2,5 ghz
 - 48 GB RAM
 - 1500 GB SSD
 - OS: Windows 10 Pro 20H2 19042.80
 - Fix external IP

**Ombi Version:**
 - Version 4.0.1116.0
- Media Server: Plex 1.21.4.4054
- Database Type: SQLite

**Comment by tidusjar** [comment]
Something strange has happened whilst trying to sync. Can you delete your ombiexternal.db and restart ombi and kick off another sync?

**Comment by dinner95** [comment]
After deleting the externaldb twice and readding pms it works!
Thank you very much!
