### ISSUE TITLE
Email Not Working Due To Missing MimeKit

### ISSUE THREAD

**Issue by thebmw** [Ombi-app/Ombi#4066]
**Describe the bug**
I can't send mail due to what appears to be a missing library

**To Reproduce**
1. Go to 'Settings > Notification > Email'
2. Configure email
2. Click on 'Test'

**Expected behavior**
A test email should send

**Logs (Logs directory where Ombi is located)**
```
2021-02-22 01:36:01.118 -05:00 [Warning] Exception when testing Email Notifications
System.BadImageFormatException: Could not load file or assembly 'MimeKit, Version=2.5.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'. The module was expected to contain an assembly manifest.
File name: 'MimeKit, Version=2.5.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Ombi Version (please complete the following information):**
 - Version 4.0.1036.0 
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
How did you install v4

**Comment by thebmw** [comment]
I installed using the Debian/Ubuntu repo in the docs.

**Comment by tidusjar** [comment]
Is this still an issue after upgrading?

**Comment by thebmw** [comment]
After updating to the latest version it appears to be working.
