### ISSUE TITLE
Ombi V4 Baseurl on windows not working

### ISSUE THREAD

**Issue by goober2186** [Ombi-app/Ombi#4070]
**Describe the bug**
When running ombi-v4 on windows it doesn't respect that baseurl setting and will always just use the root directory.

**To Reproduce**
1. created databases using the commands in the wiki
2. run ombi
3. change baseurl
4. restart ombi
5. ombi still loads from the root directory and doesn't work through caddy at the new baserul

**Expected behavior**
Change the baseurl and allow access through caddy at the new baseurl

**Screenshots**
![image](https://user-images.githubusercontent.com/40781066/109340632-e0c88b00-782e-11eb-80a2-bc27ce3306e8.png)

**Logs (Logs directory where Ombi is located)**
This was the only section in the log that had any errors

`System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

 ---> System.TimeoutException: The operation was canceled.

 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.

 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.

   --- End of inner exception stack trace ---

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)

   at System.Net.Http.HttpConnection.FillAsync(Boolean async)

   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)

   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)

   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost)

   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch)

   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)

   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)`

**Desktop (please complete the following information):**
 - Windows Server 2019

**Ombi Version (please complete the following information):**
 - Version 4.0.1122
- Media Server Plex
- Database Type: MySQL

**Additional context**

**Comment by JaxonWright** [comment]
This is basically the same issue as #3483

**Comment by goober2186** [comment]
Thank you, for pointing me in the right direction, that looked different than my issue from the issue name, but it does appear to be related/the same thing.

**Comment by goober2186** [comment]
Same as #3483
