### ISSUE TITLE
Mobile app not searching tv shows

### ISSUE THREAD

**Issue by roborick** [Ombi-app/Ombi#4119]
**Describe the bug**
Webpage works fine but mobile app is giving me internalservererror
image
![image](https://user-images.githubusercontent.com/6352485/112749364-e3ceac80-8f8f-11eb-8b1f-ebcb5a841385.png)

See log:
Mapping types:
Object -> SearchTvShowViewModel
System.Object -> Ombi.Core.Models.Search.SearchTvShowViewModel
at lambda_method3576(Closure , Object , SearchTvShowViewModel , ResolutionContext )
at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(String theMovieDbId, CancellationToken token)
at Ombi.Controllers.V1.SearchController.GetShowInfo(String tvdbId)
at lambda_method3571(Closure , Object )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Ombi.ApiKeyMiddlewear.ValidateUserAccessToken(HttpContext context, RequestDelegate next, String key)
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
2021-03-28 06:24:18.560 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/176941?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en&append_to_response=videos,credits,similar,recommendations,external_ids,keywords,images
2021-03-28 06:24:18.562 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

**Ombi Version (please complete the following information):**
 - Version 4.0.1277.0
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Fixed in latest version of ombi
