### ISSUE TITLE
Ombi can't connect to plex with SSL despite "ignore certificate errors" being enabled

### ISSUE THREAD

**Issue by weirdcrap** [Ombi-app/Ombi#4129]
**Describe the bug**
Ombi can no longer connect to my local plex instance over SSL with a "Certificate Name Mismatch error". I have "Ignore Certificate Errors" enabled in Configuration > General and this was working in previous versions of Ombi with no other changes.  

Disabling SSL allows me to connect for the time being but this is not desired behavior.

**To Reproduce**
1. Go to Settings > Media Server > Plex 
2. Setup plex connection with SSL enabled.
3. Test and fails.

**Expected behavior**
I expect Ombi to respect the ignore certificate errors toggle and connect to plex locally over SSL despite the certificate name mismatch. Turning off SSL allows it to connect but this was never required before.

**Screenshots**
![image](https://user-images.githubusercontent.com/22824785/113154583-c1da6180-91fd-11eb-8362-85876004e9b5.png)
![image](https://user-images.githubusercontent.com/22824785/113154733-ec2c1f00-91fd-11eb-9266-5b3315ae5548.png)

**Logs (Logs directory where Ombi is located)**
```
2021-03-31 08:40:00.187 -05:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
   at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri)
   at Ombi.Controllers.V1.External.TesterController.Plex(PlexServers settings)
```

**Desktop (please complete the following information):**
 - OS: Debian 10, installed as a systemd service.

**Ombi Version (please complete the following information):**
 - Version 4.0.1292.0
- Media Server Plex
- Database Type: MySQL

**Additional context**
I'm going to try to downgrade a version or two and see if the issue goes away. I wish I had paid more attention to what version I was on when this last worked before I updated.

**Comment by tidusjar** [comment]
Now you have gone down to a previous version, can you please upgrade to the latest again just to ensure it's a versioning issue?

**Comment by weirdcrap** [comment]
> Now you have gone down to a previous version, can you please upgrade to the latest again just to ensure it's a versioning issue?
Upgraded to latest (1309) and now it seems to be working! I guess I did something wrong with my upgrade yesterday? Not sure what it would have been but unless you changed something I guess it was me after all.
