### ISSUE TITLE
MySql usage growth after update

### ISSUE THREAD

**Issue by jendru214** [Ombi-app/Ombi#4135]
**Describe the bug**
Hi,
I am almost always on the newest version of Ombi recently and had no issues with it before. I use MySql and it used to work way better than standard database. After updating to the newest version today 4.0.1299.0 I see big spikes of mysql usage when trying to even use menu links.
![image](https://user-images.githubusercontent.com/67014283/113257523-067ffe80-92cb-11eb-97a4-45b0dc1b3004.png)
This is under almost no load and just one user using ombi. 
![image](https://user-images.githubusercontent.com/67014283/113257592-1dbeec00-92cb-11eb-9657-10eb36fb4e21.png)
Also I am sure its ombi as its the only application that currently uses mysql.

**To Reproduce**
I guess run ombi on windows server with mysql

**Expected behavior**
A lot more responsiveness like before the update.

**Screenshots**
Above

**Logs (Logs directory where Ombi is located)**
[Logs.zip](https://github.com/Ombi-app/Ombi/files/6241726/Logs.zip)

**Desktop (please complete the following information):**
 - OS: Windows server 2016

**Ombi Version (please complete the following information):**
 - Version 4.0.1299.0, just few versions before this was working fine but cant remember which version exactly. (not further than a month old)
- Media Server Plex
- Database Type: mysql

**Comment by tidusjar** [comment]
Hi, 

what would be really useful is if you could pin down the update that you think maybe causing this.

Also, what CPU do you have in your server?

**Comment by jendru214** [comment]
That would be the newest one 4.0.1299.0
The cpu is nothing special but it should be able to handle mysql easy 
![image](https://user-images.githubusercontent.com/67014283/113324230-2b9a5e80-9317-11eb-82b2-083703774300.png)

**Comment by jendru214** [comment]
And I think I moved from 1257 but cant be sure.

**Comment by tidusjar** [comment]
Are you able to downgrade and try and find the offending build?

**Comment by jendru214** [comment]
Not sure how to downgrade? Should I overwrite the files I have with older version files?

**Comment by jendru214** [comment]
Ok so I tried various things. Downgrading didnt help, creating a new db didnt help, running ombi through new folder didnt help. There is some issue with ombi running now on mariadb... fresh install and the process jumps like it never did to 70-100%, has some weird issue where it does not import all plex users on a fresh install (might be my plex servers fault idk)

**Comment by jendru214** [comment]
one more thing, it started to freeze completely not even showing the contents of discovery page. But can be "pushed" by pressing enter in the console window...

**Comment by tidusjar** [comment]
Sounds like something is freezing the console window, if you are pressing enter to move it along then something is 'pausing' it

**Comment by jendru214** [comment]
Any idea what to look for that might be pausing it? I had a similar issue that made me make a jump to mysql in the first place.

**Comment by jendru214** [comment]
I even scanned my whole system for viruses/malware thinking it might be infected since this behavior is weird

**Comment by jendru214** [comment]
@tidusjar I have figured it out, it turns out Ombi V4 does not like having mfa turned on plex.tv. I have disabled mfa and now it sync and cpu usage is down for mysql as well 
![image](https://user-images.githubusercontent.com/67014283/116209555-54f5b100-a742-11eb-8214-60e7738e6910.png)

**Comment by tidusjar** [comment]
Interesting, how are you logging in to Ombi?

Can you turn it back on and you sure that's the case?

**Comment by jendru214** [comment]
I am logging in with plex admin through plex oauth, I have removed all local users. And yes after turning it back on it didnt pull any shared users to ombi through the importer except the home users .

**Comment by jendru214** [comment]
Also if you are going to be fixing this issue you might want to add a feature to the plex server config tab to support mfa when asked for Plex.tv credentials ^^

**Comment by tidusjar** [comment]
@jendru214 You can still use MFA by passing the OTA PIN at the end of your password.

So once you reenabled the Plex OAuth your MySQL jumped up again?

**Comment by jendru214** [comment]
Yes with mfa turned on ombi goes crazy and causes mysql to use 100% of processor resources.
However I am unsure if thats just mfa or if disabling mfa didnt kickstart something else since I see plex does not sync all the shows I have. I ran a full sync and cleaning previous data and I see few shows as approved but not as available? However its at least responsive now.

**Comment by jendru214** [comment]
ok so mysql usage went down, thats still true but it still can hang. I saw now at least in the console window it displayed this on freeze but again unfroze when i pressed enter:
` Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj)
         at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj)
         at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model)
         at Ombi.Core.Engine.V2.TvSearchEngineV2.ProcessResult[T](T tvMazeSearch)
         at Ombi.Core.Engine.V2.TvSearchEngineV2.ProcessResults(List`1 items)
         at Ombi.Core.Engine.V2.TvSearchEngineV2.Anticipated(Int32 currentlyLoaded, Int32 amountToLoad)
         at Ombi.Controllers.V2.SearchController.AnticipatedTv(Int32 currentPosition, Int32 amountToLoad)
         at lambda_method2656(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
         at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj)
         at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj)
         at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model)
         at Ombi.Core.Engine.V2.TvSearchEngineV2.ProcessResult[T](T tvMazeSearch)
         at Ombi.Core.Engine.V2.TvSearchEngineV2.ProcessResults(List`1 items)
         at Ombi.Core.Engine.V2.TvSearchEngineV2.Popular(Int32 currentlyLoaded, Int32 amountToLoad, String langCustomCode)
         at Ombi.Controllers.V2.SearchController.PopularTv(Int32 currentPosition, Int32 amountToLoad)
         at lambda_method1734(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
         at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
`

**Comment by jendru214** [comment]
Since there is nothing new here and those issues come and go one after another in Ombi I decided to jump to Overseerr and give it a try.
You can close this issue, hopefully somewhere in the future you will resolve it.
