### ISSUE TITLE
V4 - Email URI issues 

### ISSUE THREAD

**Issue by JamesGannon-Comp** [Ombi-app/Ombi#4145]
**Describe the bug**
In V4 adding SMTP email service fails.

**To Reproduce**
1. Go to Email Notifications
2. Add email provider details
3. Click test

**Expected behavior**
Email test passes

**Screenshots**
![image](https://user-images.githubusercontent.com/68957383/114169963-26966a00-992a-11eb-9b92-76789c3fd369.png)

**Logs (Logs directory where Ombi is located)**

2021-04-09 12:48:46.216 +02:00 [Error] Exception when attempting to send an email
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_IdnHost()
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
2021-04-09 12:48:46.216 +02:00 [Warning] Exception when testing Email Notifications
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_IdnHost()
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Ombi Version (please complete the following information):**
 - Version 4.0.1328 
- Media Server Plex
- Database Type: MYSQL

**Additional context**
Base URL is /ombi

**Comment by tidusjar** [comment]
What's your application URL set to?

**Comment by JamesGannon-Comp** [comment]
hostname.tld/ombi

**Comment by JamesGannon-Comp** [comment]
And pre-emoting your next message yup adding https fixes it. Might be good to add this to a FAQ if possible as people start migrating to V4
