### ISSUE TITLE
Tv requests fail and do not pass request to Sonarr

### ISSUE THREAD

**Issue by HMpugh** [Ombi-app/Ombi#4162]
**Describe the bug**
TV requests fail every time for both series and individual episodes and results in 'Something went wrong!' message. Request shows up under processing but does not pass through to Sonarr. Ombi successfully connects to Sonarr when using 'Test Connectivity' in the Sonarr settings page. Issue started after updating from V3 to V4. 

**To Reproduce**
1. Request any TV series

**Expected behavior**
Should send requests to Sonarr. 

**Logs (Logs directory where Ombi is located)**
2021-04-27 10:36:23.180 -04:00 [Information] Start processing HTTP request "GET" http://api.themoviedb.org/3/tv/63646?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en&append_to_response=videos,credits,similar,recommendations,external_ids,keywords,images
2021-04-27 10:36:23.180 -04:00 [Information] Sending HTTP request "GET" http://api.themoviedb.org/3/tv/63646?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en&append_to_response=videos,credits,similar,recommendations,external_ids,keywords,images
2021-04-27 10:36:23.204 -04:00 [Information] Received HTTP response headers after 23.8695ms - 200
2021-04-27 10:36:23.204 -04:00 [Information] End processing HTTP request after 24.0035ms - 200
2021-04-27 10:36:23.210 -04:00 [Information] Start processing HTTP request "GET" http://api.themoviedb.org/3/tv/63646/season/1?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en
2021-04-27 10:36:23.210 -04:00 [Information] Sending HTTP request "GET" http://api.themoviedb.org/3/tv/63646/season/1?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en
2021-04-27 10:36:23.218 -04:00 [Information] Received HTTP response headers after 7.1085ms - 200
2021-04-27 10:36:23.218 -04:00 [Information] End processing HTTP request after 7.2093ms - 200
2021-04-27 10:36:23.219 -04:00 [Information] Start processing HTTP request "GET" http://api.themoviedb.org/3/tv/63646/season/2?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en
2021-04-27 10:36:23.219 -04:00 [Information] Sending HTTP request "GET" http://api.themoviedb.org/3/tv/63646/season/2?api_key=b8eabaf5608b88d0298aa189dd90bf00&language=en
2021-04-27 10:36:23.224 -04:00 [Information] Received HTTP response headers after 4.6111ms - 200
2021-04-27 10:36:23.224 -04:00 [Information] End processing HTTP request after 4.7074ms - 200
2021-04-27 10:36:23.255 -04:00 [Debug] Batch acquisition of 1 triggers
2021-04-27 10:36:23.255 -04:00 [Debug] Batch acquisition of 0 triggers
2021-04-27 10:36:23.255 -04:00 [Debug] Calling Execute on job Notifications.INotificationService
2021-04-27 10:36:23.257 -04:00 [Information] Start processing HTTP request "GET" http://*********/api/rootfolder
2021-04-27 10:36:23.257 -04:00 [Information] Sending HTTP request "GET" http://*********/api/rootfolder
2021-04-27 10:36:23.262 -04:00 [Information] Template RequestApproved is disabled for Email
2021-04-27 10:36:23.266 -04:00 [Information] Received HTTP response headers after 9.0417ms - 200
2021-04-27 10:36:23.266 -04:00 [Information] End processing HTTP request after 9.1581ms - 200
2021-04-27 10:36:23.266 -04:00 [Information] Start processing HTTP request "GET" http://*********/api/rootfolder
2021-04-27 10:36:23.266 -04:00 [Information] Sending HTTP request "GET" http://*********/api/rootfolder
2021-04-27 10:36:23.270 -04:00 [Information] Start processing HTTP request "POST" https://onesignal.com/api/v1/notifications/
2021-04-27 10:36:23.270 -04:00 [Information] Sending HTTP request "POST" https://onesignal.com/api/v1/notifications/
2021-04-27 10:36:23.274 -04:00 [Information] Received HTTP response headers after 8.4842ms - 200
2021-04-27 10:36:23.274 -04:00 [Information] End processing HTTP request after 8.5583ms - 200
2021-04-27 10:36:23.275 -04:00 [Information] Start processing HTTP request "GET" http://*********/api/series
2021-04-27 10:36:23.275 -04:00 [Information] Sending HTTP request "GET" http://*********/api/series
2021-04-27 10:36:23.453 -04:00 [Information] Received HTTP response headers after 183.8027ms - 200
2021-04-27 10:36:23.454 -04:00 [Information] End processing HTTP request after 183.9324ms - 200
2021-04-27 10:36:23.460 -04:00 [Information] Start processing HTTP request "POST" https://ombinotifications.azurewebsites.net/api/MobileNotification
2021-04-27 10:36:23.460 -04:00 [Information] Sending HTTP request "POST" https://ombinotifications.azurewebsites.net/api/MobileNotification
2021-04-27 10:36:23.489 -04:00 [Information] Received HTTP response headers after 213.4706ms - 200
2021-04-27 10:36:23.489 -04:00 [Information] End processing HTTP request after 213.5653ms - 200
2021-04-27 10:36:23.705 -04:00 [Information] Start processing HTTP request "POST" http://*********/api/series/
2021-04-27 10:36:23.705 -04:00 [Information] Sending HTTP request "POST" http://*********/api/series/
2021-04-27 10:36:23.739 -04:00 [Information] Received HTTP response headers after 33.2234ms - 400
2021-04-27 10:36:23.739 -04:00 [Information] End processing HTTP request after 33.3699ms - 400
2021-04-27 10:36:23.739 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://*********/api/series/
2021-04-27 10:36:23.739 -04:00 [Information] Start processing HTTP request "POST" http://*********/api/series/
2021-04-27 10:36:23.739 -04:00 [Information] Sending HTTP request "POST" http://*********/api/series/
2021-04-27 10:36:23.771 -04:00 [Information] Received HTTP response headers after 31.6772ms - 400
2021-04-27 10:36:23.771 -04:00 [Information] End processing HTTP request after 31.8356ms - 400
2021-04-27 10:36:23.771 -04:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://*********/api/series/
2021-04-27 10:36:23.771 -04:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.Exception: Invalid Path,Invalid Path
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
2021-04-27 10:36:23.772 -04:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: Invalid Path,Invalid Path
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model)
2021-04-27 10:36:23.912 -04:00 [Information] Received HTTP response headers after 451.1298ms - 200
2021-04-27 10:36:23.912 -04:00 [Information] End processing HTTP request after 451.2701ms - 200
2021-04-27 10:36:23.916 -04:00 [Debug] Trigger instruction : DeleteTrigger
2021-04-27 10:36:23.916 -04:00 [Debug] Deleting trigger

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1342 (issue also exists on 4.0.1344)
- Sonarr 3.0.6.1196

**Additional context**
Movie requests work as intended and are successfully added to Radarr.

**Comment by tidusjar** [comment]
> System.Exception: Invalid Path,Invalid Path

Can you check your Root Folders and Quality profiles in your sonarr settings please!

**Comment by HMpugh** [comment]
![image](https://user-images.githubusercontent.com/83290776/116267407-604cda80-a74a-11eb-93ce-1ae5f0f5f840.png)

I also receive a 'Successfully retrieved the Root Folders' and 'Successfully retrieved the Quality Profiles' messages when 'Load Folders' and 'Load Qualities' are selected.

**Comment by tidusjar** [comment]
Out of curiosity, 

can you press the Load for each and then re-save? 

Also does the user who is requesting these have any qualities or profiles in their user?

**Comment by HMpugh** [comment]
Already had loaded and re-saved each of those.

I believe the issue was not noticing that the qualities and profiles were reset when moving from v3 to v4. I hadn't though of checking as I was testing with admin privileges and was setting those when making the request. Works perfectly now.

Thanks!
