### ISSUE TITLE
Stuck on Processing Request using latest Radarr 3.1.1.4954 and latest Ombi 4.0.1351

### ISSUE THREAD

**Issue by chaosclarity84** [Ombi-app/Ombi#4181]
**Describe the bug**
Using latest Radarr and Ombi version, requesting a movie is stuck on "Processing Request". Did not happen on February build of Radarr, updated to May 4th build of Radarr and now it's broken.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by Jopinder** [comment]
I'm seeing the same issue, on both Radarr 3.1.1.4954 and Sonarr 3.0.6.1196. Looks like the requests are never sent to either programs.

**Comment by tidusjar** [comment]
You sure you have the enabled switch turned on in the ombi settings?

**Comment by chaosclarity84** [comment]
Yea, it’s enabled. I tried to also toggle it off/on.

**Comment by tidusjar** [comment]
So are the requests being sent to radarr? Just not being marked as available?

**Comment by chaosclarity84** [comment]
> So are the requests being sent to radarr? Just not being marked as available?

My ombi configuration is setup to send requests to Radarr, but if someone requests a movie item, it stays on Processing Request, and I never see the item requested in the Radarr activity queue.

**Comment by tidusjar** [comment]
So the processing request state means that we have sent it and the request is "processing" 

If the media is now in radarr and monitored, ombi has done it's job

**Comment by chaosclarity84** [comment]
I get that, but maybe radarr changed something in the May update that broke
how you’re sending the request. It seems illogical that you would
automatically assume that since you’ve fired off a request in to a black
hole, you just assume it’s going to get where it needs to go and be handled
properly.
Imagine if I opened up the issue on the radarr side, and they’re pointing
the finger at Ombi devs. The street goes both ways in my opinion.
Oh well, I tried, thanks.

**Comment by tidusjar** [comment]
Yeah that's fine, I get where you are coming from. I just wanted to fully understand what your issue was as I originally thought it was to do with availablity. 

I'll take a look tonight

**Comment by tidusjar** [comment]
So i'm using latest Ombi, version `3.2.0.4994` of Radarr and I was able to add a movie successfully, it added it to Radarr as monitored and triggered a search.

Here's my Ombi Radarr Settings:
![image](https://user-images.githubusercontent.com/6642220/117583120-5a1d0d80-b0fd-11eb-9265-9a04c77bae0e.png)


One thing might be worth doing is checking your Root Folders and quality profiles assigned to your user (if there are any) to see if they still are valid?

If still no luck, can you request a movie and attach an Ombi log file so I can investigate further

**Comment by skydivercactus** [comment]
I have similar issue, here is log:

For some reason it seem to be Radarr update issue, so I assume it Radarr issue? It prompt me to upgrade Net Code but i haven't got time to upgrade it as Radarr seem to work fine. 

Radarr Version: 3.1.1.4954
Ombi : 4.0.1342

Ombi side:

`2021-05-15 12:33:38.551 +00:00 [Error] Failed caching queued items from Radarr
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
   at Ombi.Api.Radarr.RadarrApi.GetMovies(String apiKey, String baseUrl)
   at Ombi.Schedule.Jobs.Radarr.RadarrSync.Execute(IJobExecutionContext job)`

Radarr Side

`System.Net.Sockets.SocketException (0x80004005): Message too long
  at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0 (System.Net.Sockets.SocketError e) [0x00006] in <3f98ad8e4c9149cba3f8d2ecf644b718>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult () [0x00015] in <3f98ad8e4c9149cba3f8d2ecf644b718>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessSends () [0x0011b] in <3f98ad8e4c9149cba3f8d2ecf644b718>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoSend () [0x00077] in <3f98ad8e4c9149cba3f8d2ecf644b718>:0 
  at System.IO.Pipelines.PipeCompletion.ThrowLatchedException () [0x00000] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.IO.Pipelines.Pipe.GetFlushResult (System.IO.Pipelines.FlushResult& result) [0x00018] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.IO.Pipelines.Pipe.GetFlushAsyncResult () [0x0002b] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.IO.Pipelines.Pipe+DefaultPipeWriter.GetResult (System.Int16 token) [0x00000] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.Threading.Tasks.ValueTask`1+ValueTaskSourceAsTask+<>c[TResult].<.cctor>b__4_0 (System.Object state) [0x0002f] in <bc890e4ea34f463c8fd960f43c8beb88>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TimingPipeFlusher.TimeFlushAsync (Microsoft.AspNetCore.Server.Kestrel.Core.MinDataRate minRate, System.Int64 count, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpOutputAborter outputAborter, System.Threading.CancellationToken cancellationToken) [0x0007c] in <708a61b06ae647a09457b7bb52b351ad>:0 
  at System.IO.Pipelines.PipeCompletion.ThrowLatchedException () [0x00000] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.IO.Pipelines.Pipe.GetReadResult (System.IO.Pipelines.ReadResult& result) [0x00000] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.IO.Pipelines.Pipe.ReadAsync (System.Threading.CancellationToken token) [0x0004b] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at System.IO.Pipelines.Pipe+DefaultPipeReader.ReadAsync (System.Threading.CancellationToken cancellationToken) [0x00000] in <285d42c15ab1455ca31b0389730dcae1>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.BeginRead (System.Threading.Tasks.ValueTask`1[System.IO.Pipelines.ReadResult]& awaitable) [0x00007] in <708a61b06ae647a09457b7bb52b351ad>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext] (Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1[TContext] application) [0x00045] in <708a61b06ae647a09457b7bb52b351ad>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext] (Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1[TContext] application) [0x00087] in <708a61b06ae647a09457b7bb52b351ad>:0 `

**Comment by chaosclarity84** [comment]
Yea, I've noticed the issue is hit or miss. Sometimes the request goes through, sometimes it doesn't.

**Comment by tidusjar** [comment]
I'll take another look, I'd there any specific movies you think this is happening on?

**Comment by skydivercactus** [comment]
> 
> 
> I'll take another look, I'd there any specific movies you think this is happening on?

Nope, seem to be all movies for me.

**Comment by tidusjar** [comment]
And for yuuraeld, mind providing some more information eg. Log files and ombi version, radarr version and a image of your settings (feel free to remove the API key)

**Comment by skydivercactus** [comment]
> 
> 
> And for yourself, mind providing some more information eg. Log files and ombi version, radarr version and a image of your settings (feel free to remove the API key)

Hey, still have same issue once updating to latest dev. running 4.0.1361 ombi and 3.1.1.4954 radarr. Where did you get "version 3.2.0.4994 of Radarr" did you mistaken the version of radarr? The latest even for dev seem be 3.1.1.4954, is that 3.2.0.4994 a nightly build? 

My setting is essentially the same apart from no base URL but seem able fetch correct info such as profiles/location. On radarr side still get message too long error when clicking on load profile etc. 
![image](https://user-images.githubusercontent.com/49363576/118445862-493e4e80-b732-11eb-83b2-b4832a7ab750.png)


Error when requesting. 

> System.Net.Http.HttpRequestException: An error occurred while sending the request.
>  ---> System.IO.IOException: The response ended prematurely.
>    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
>    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>    at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
>    at Ombi.Api.Radarr.RadarrV3Api.GetMovies(String apiKey, String baseUrl)
>    at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings)
>    at Ombi.Core.Senders.MovieSender.Send(MovieRequests model)

**Comment by tidusjar** [comment]
Ok looks like there are two different issues in this thread. One of them has been fixed

**Comment by skydivercactus** [comment]
> 
> 
> Ok looks like there are two different issues in this thread. One of them has been fixed

Oh ok. Should I make a new issue? Happy to provide more log and info if required.

**Comment by tidusjar** [comment]
Try now, I've stopped using the Legacy endpoints
