### ISSUE TITLE
Plex Content Sync Exception when adding movie

### ISSUE THREAD

**Issue by Subtixx** [Ombi-app/Ombi#4183]
**Describe the bug**
Plex Content Sync exception while running "Manually Run Full Sync", happened after update to v3

**To Reproduce**
1. Go to MediaServer -> Pley
2. Click "Manually Run Full Sync"
4. See error in log

**Expected behavior**
Adding the movies from my plex library

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20743379/117567699-8a44bc00-b0bd-11eb-99a5-5f4683f787d7.png)

**Logs (Logs directory where Ombi is located)**
Goes on and on for alot of movies.
```
2021-05-09 00:00:00.151 +00:00 [Error] Exception when adding new Movie "Walt Disney Kostbarkeiten: Micky Maus im Glanz der Farbe 1"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Guid', line 1, position 3249.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request) in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 78
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId) in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 159
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 264
``` 

**Desktop (please complete the following information):**
 - OS: Docker (linuxserver/ombi:latest)

**Ombi Version (please complete the following information):**
 - Version 4.0.1342
- Media Server Plex (1.22.3.4392)
- Database Type: SQLite

**Comment by tidusjar** [comment]
What metadata agent are you using for that library?

**Comment by Subtixx** [comment]
Plex Movie

**Comment by tidusjar** [comment]
For the movie that's mentioned on the first link of the log,

Can you please press the Get Info button in Plex and then press View XML and paste that here please?

**Comment by Subtixx** [comment]
Sure. Here you go:

```
<html>
<body>
<!--StartFragment-->

Zeilenumbruch
--
  | <?xml version="1.0" encoding="UTF-8"?>
  | <MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="1" librarySectionTitle="Filme" librarySectionUUID="7e364bd3-e219-41bf-aea9-1b273a887242" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1618841647">
  | <Video ratingKey="3684" key="/library/metadata/3684" guid="plex://movie/5d776fa4594b2b001e73ff06" studio="Walt Disney Productions" type="movie" title="Walt Disney Kostbarkeiten: Micky Maus im Glanz der Farbe 1" librarySectionTitle="Filme" librarySectionID="1" librarySectionKey="/library/sections/1" originalTitle="Mickey Mouse in Living Color" summary="Wenn das kein Grund zum Feiern ist: 25 kostbare Micky Maus Kurzfilme, die in der Zeit zwischen 1935 und 1938 ver&#246;ffentlicht wurden - eine zeitlose Sammlung, die Micky bei seinen ersten ungest&#252;men Schritten in die Welt der Farbe und eine neue &#196;ra der Animation zeigt! Diese klassische Sammlung enth&#228;lt jede Menge Besonderheiten und wunderbare Extras: So kann man den K&#252;nstlern beim Anfertigen von Bleistiftskizzen &#252;ber die Schulter schauen und kommt in den Genuss der ersten Audiotracks. In der Galerie gibt es unter anderem Original-Entw&#252;rfe und die nostalgischen Kinoposter von damals zu bewundern. Interviews mit den Zeichnern und historische Fernsehaufzeichnungen von Walt Disney pers&#246;nlich lassen die Maus, mit der alles begann farbenfroh hochleben!" audienceRating="8.5" year="2001" tagline="1935 - 1938" thumb="/library/metadata/3684/thumb/1620406450" art="/library/metadata/3684/art/1620406450" duration="5658200" originallyAvailableAt="2001-12-04" addedAt="1620404283" updatedAt="1620406450" audienceRatingImage="themoviedb://image.rating">
  | <Media id="6041" duration="5658200" bitrate="1023" width="640" height="480" aspectRatio="1.33" audioChannels="2" audioCodec="mp3" videoCodec="mpeg4" videoResolution="480" container="avi" videoFrameRate="PAL" videoProfile="advanced simple">
  | <Part accessible="1" exists="1" id="6756" key="/library/parts/6756/1354907957/file.avi" duration="5658200" file="/mnt/movies/Walt Disney/Kostbarkeiten Micky Maus im Glanz der Farbe/movie2.avi" size="732993536" container="avi" deepAnalysisVersion="4" requiredBandwidths="1553,1197,1097,1097,1097,1097,1097,1097" videoProfile="advanced simple">
  | <Stream id="16378" streamType="1" codec="mpeg4" index="0" bitrate="919" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" codecID="XVID" codedHeight="480" codedWidth="640" frameRate="25.000" height="480" level="5" profile="advanced simple" refFrames="1" requiredBandwidths="1443,1088,994,994,994,994,994,994" width="640" displayTitle="480p (MPEG4)" extendedDisplayTitle="480p (MPEG4)">
  | </Stream>
  | <Stream id="16379" streamType="2" selected="1" codec="mp3" index="1" channels="2" bitrate="104" audioChannelLayout="stereo" requiredBandwidths="105,105,105,105,105,105,105,105" samplingRate="48000" streamIdentifier="1" displayTitle="Unbekannt (MP3 Stereo)" extendedDisplayTitle="Unbekannt (MP3 Stereo)">
  | </Stream>
  | </Part>
  | </Media>
  | <Genre id="8564" filter="genre=8564" tag="Dokumentarfilm" />
  | <Genre id="20902" filter="genre=20902" tag="Short" />
  | <Writer id="20905" filter="writer=20905" tag="Leonard Maltin" />
  | <Producer id="20906" filter="producer=20906" tag="Clare Baren" />
  | <Producer id="20907" filter="producer=20907" tag="Leonard Maltin" />
  | <Country id="11077" filter="country=11077" tag="United States of America" />
  | <Guid id="imdb://tt0356885" />
  | <Guid id="tmdb://371654" />
  | <Collection id="10140" filter="collection=10140" tag="Walt Disney" />
  | <Role id="20903" filter="actor=20903" tag="Ward Kimball" role="Self" thumb="https://image.tmdb.org/t/p/original/wEzFPqgY2YcccyanoRmb0pBDlkK.jpg" />
  | <Role id="20904" filter="actor=20904" tag="Leonard Maltin" role="Self - Host" thumb="https://metadata-static.plex.tv/people/5d7768285af944001f1f71d5.jpg" />
  | <Field locked="1" name="collection" />
  | <Preferences>
  | <Setting id="languageOverride" label="Metadata language" summary="Language to use for item metadata such as synopsis and title." type="text" default="" value="" hidden="0" advanced="0" group="" enumValues=":Mediathek-Standard\|ar-SA:&#1575;&#1604;&#1593;&#1585;&#1576;&#1610;&#1577;\|ca-ES:Catal&#224;\|cs-CZ:&#268;esky\|da-DK:Dansk\|de-DE:Deutsch\|el-GR:&#917;&#955;&#955;&#951;&#957;&#953;&#954;&#940;\|en-AU:English (Australia)\|en-CA:English (Canada)\|en-GB:English (United Kingdom)\|en-US:English (United States)\|es-ES:Espa&#241;ol\|es-MX:Espa&#241;ol Mexicano\|et-EE:Eesti Keele\|fa-IR:&#1601;&#1575;&#1585;&#1587;&#1740;\|fi-FI:Suomi\|fr-CA:Fran&#231;ais Canadien\|fr-FR:Fran&#231;ais\|he-IL:&#1506;&#1489;&#1512;&#1497;&#1514;\|hi-IN:&#2361;&#2367;&#2344;&#2381;&#2342;&#2368;, &#2361;&#2367;&#2306;&#2342;&#2368;\|hu-HU:Magyar\|id-ID:Bahasa Indonesia\|it-IT:Italiano\|ja-JP:&#26085;&#26412;&#35486;\|ko-KR:&#54620;&#44397;&#50612;\|lt-LT:Lietuvi&#371; kalba\|lv-LV:Latvie&#353;u valoda\|nb-NO:Norsk bokm&#229;l\|nl-NL:Nederlands\|pl-PL:Polski\|pt-BR:Portugu&#234;s Brasileiro\|pt-PT:Portugu&#234;s\|ro-RO:Rom&#226;n&#259;\|ru-RU:&#1088;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081; &#1103;&#1079;&#1099;&#1082;\|sk-SK:Sloven&#269;ina\|sv-SE:Svenska\|th-TH:&#3652;&#3607;&#3618;\|tr-TR:T&#252;rk&#231;e\|uk-UA:&#1091;&#1082;&#1088;&#1072;&#1111;&#1085;&#1089;&#1100;&#1082;&#1072;\|vi-VN:Ti&#7871;ng Vi&#7879;t\|zh-CN:&#20013;&#25991;\|zh-HK:&#39321;&#28207;\|zh-TW:&#27491;&#39636;&#20013;&#25991;" />
  | <Setting id="useOriginalTitle" label="Use original title" summary="Use the original title for this item regardless of the library language." type="int" default="-1" value="-1" hidden="0" advanced="0" group="" enumValues="-1:Mediathek-Standard\|0:No\|1:Yes" />
  | </Preferences>
  | <Extras size="0">
  | </Extras>
  | <Related>
  | <Hub hubKey="/library/metadata/3062" key="/library/sections/1/all?type=1&amp;collection=10140&amp;sort=originallyAvailableAt,year:nullsLast" title="Walt Disney Sammlung" type="movie" hubIdentifier="collection.related.1.1" context="hub.collection.related" size="1" more="1" style="shelf">
  | <Video ratingKey="3062" key="/library/metadata/3062" guid="plex://movie/5d776826eb5d26001f1dd404" studio="Walt Disney Productions" type="movie" title="Schneewittchen und die sieben Zwerge" originalTitle="Snow White and the Seven Dwarfs" contentRating="de/0" summary="Schneewittchen ist eine kleine Prinzessin, deren b&#246;se Stiefmutter sie in Lumpen h&#252;llen und als Magd schuften lie&#223;. Warum? Weil sie Angst hatte, dass das M&#228;dchen eines Tages sch&#246;ner sein k&#246;nnte als sie selbst. Als diese Bef&#252;rchtung der eitlen K&#246;nigin durch ihren magischen Spiegel als wahr best&#228;tigt wird, beauftragt sie einen J&#228;ger, Schneewittchen im Wald zu t&#246;ten. Doch der bringt den Mord nicht &#252;bers Herz und l&#228;sst das M&#228;dchen entkommen. Schneewittchen entdeckt auf einer Lichtung ein leer stehendes Haus, in dem sie gemeinsam mit den Tieren des Waldes f&#252;r Ordnung und Sauberkeit sorgt. Als die sieben Zwerge von der Arbeit heimkehren, sind sie von ihrem Hausgast schnell entz&#252;ckt und nehmen Schneewittchen bei sich auf. Als die K&#246;nigin erf&#228;hrt, dass ihre Stieftochter noch lebt, ist sie au&#223;er sich: Mit Zauberkr&#228;ften verwandelt sie sich in eine Hexe und macht sich auf den Weg in den Wald, um die b&#246;se Tat mit Hilfe eines giftigen Apfels selbst zu vollenden..." audienceRating="7.1" year="1937" tagline="The Happiest, Dopiest, Grumpiest, Sneeziest movie of the year." thumb="/library/metadata/3062/thumb/1620406392" art="/library/metadata/3062/art/1620406392" duration="4807848" originallyAvailableAt="1937-12-21" addedAt="1620326764" updatedAt="1620406392" audienceRatingImage="themoviedb://image.rating" hasPremiumPrimaryExtra="1">
  | <Media id="4717" duration="4807848" bitrate="1208" width="576" height="432" aspectRatio="1.33" audioChannels="2" audioCodec="mp3" videoCodec="mpeg4" videoResolution="sd" container="avi" videoFrameRate="PAL" videoProfile="advanced simple">
  | <Part id="5497" key="/library/parts/5497/1354908102/file.avi" duration="4807848" file="/mnt/movies/Walt Disney/Schneewittchen und die sieben Zwerge/Schneewittchen.und.die.sieben.Zwerge/movie.avi" size="733634560" container="avi" deepAnalysisVersion="4" requiredBandwidths="2205,1797,1386,1216,1216,1216,1216,1216" videoProfile="advanced simple" />
  | </Media>
  | <Genre tag="Familie" />
  | <Genre tag="Animation" />
  | <Director tag="David Hand" />
  | <Writer tag="Jacob Grimm" />
  | <Writer tag="Wilhelm Grimm" />
  | <Country tag="United States of America" />
  | <Collection tag="Walt Disney" />
  | <Role tag="Adriana Caselotti" />
  | <Role tag="Lucille La Verne" />
  | <Role tag="Harry Stockwell" />
  | </Video>
  | </Hub>
  | </Related>
  | </Video>
  | </MediaContainer>
  |  

<!--EndFragment-->
</body>
</html>
```

**Comment by tidusjar** [comment]
Odd,

Can do do the following in the browser for me using cURL?

```
curl --location --request GET 'http://YOURPLEXIP:32400/library/metadata/3684?X-Plex-Token=YOURPLEXTOKEN' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json'
```

**Comment by Subtixx** [comment]
```
{"MediaContainer":{"size":1,"allowSync":true,"identifier":"com.plexapp.plugins.library","librarySectionID":1,"librarySectionTitle":"Filme","librarySectionUUID":"7e364bd3-e219-41bf-aea9-1b273a887242","mediaTagPrefix":"/system/bundle/media/flags/","mediaTagVersion":1618841647,"Metadata":[{"ratingKey":"3684","key":"/library/metadata/3684","guid":"plex://movie/5d776fa4594b2b001e73ff06","studio":"Walt Disney Productions","type":"movie","title":"Walt Disney Kostbarkeiten: Micky Maus im Glanz der Farbe 1","librarySectionTitle":"Filme","librarySectionID":1,"librarySectionKey":"/library/sections/1","originalTitle":"Mickey Mouse in Living Color","summary":"Wenn das kein Grund zum Feiern ist: 25 kostbare Micky Maus Kurzfilme, die in der Zeit zwischen 1935 und 1938 veröffentlicht wurden - eine zeitlose Sammlung, die Micky bei seinen ersten ungestümen Schritten in die Welt der Farbe und eine neue Ära der Animation zeigt! Diese klassische Sammlung enthält jede Menge Besonderheiten und wunderbare Extras: So kann man den Künstlern beim Anfertigen von Bleistiftskizzen über die Schulter schauen und kommt in den Genuss der ersten Audiotracks. In der Galerie gibt es unter anderem Original-Entwürfe und die nostalgischen Kinoposter von damals zu bewundern. Interviews mit den Zeichnern und historische Fernsehaufzeichnungen von Walt Disney persönlich lassen die Maus, mit der alles begann farbenfroh hochleben!","audienceRating":8.5,"year":2001,"tagline":"1935 - 1938","thumb":"/library/metadata/3684/thumb/1620406450","art":"/library/metadata/3684/art/1620406450","duration":5658200,"originallyAvailableAt":"2001-12-04","addedAt":1620404283,"updatedAt":1620406450,"audienceRatingImage":"themoviedb://image.rating","Media":[{"id":6041,"duration":5658200,"bitrate":1023,"width":640,"height":480,"aspectRatio":1.33,"audioChannels":2,"audioCodec":"mp3","videoCodec":"mpeg4","videoResolution":"480","container":"avi","videoFrameRate":"PAL","videoProfile":"advanced simple","Part":[{"id":6756,"key":"/library/parts/6756/1354907957/file.avi","duration":5658200,"file":"/mnt/movies/Walt Disney/Kostbarkeiten Micky Maus im Glanz der Farbe/file.avi","size":732993536,"container":"avi","videoProfile":"advanced simple","Stream":[{"id":16378,"streamType":1,"codec":"mpeg4","index":0,"bitrate":919,"bitDepth":8,"chromaLocation":"left","chromaSubsampling":"4:2:0","codecID":"XVID","codedHeight":480,"codedWidth":640,"frameRate":25.0,"height":480,"level":5,"profile":"advanced simple","refFrames":1,"width":640,"displayTitle":"480p (MPEG4)","extendedDisplayTitle":"480p (MPEG4)"},{"id":16379,"streamType":2,"selected":true,"codec":"mp3","index":1,"channels":2,"bitrate":104,"audioChannelLayout":"stereo","samplingRate":48000,"streamIdentifier":"1","displayTitle":"Unknown (MP3 Stereo)","extendedDisplayTitle":"Unknown (MP3 Stereo)"}]}]}],"Genre":[{"id":8564,"filter":"genre=8564","tag":"Dokumentarfilm"},{"id":20902,"filter":"genre=20902","tag":"Short"}],"Writer":[{"id":20905,"filter":"writer=20905","tag":"Leonard Maltin"}],"Producer":[{"id":20906,"filter":"producer=20906","tag":"Clare Baren"},{"id":20907,"filter":"producer=20907","tag":"Leonard Maltin"}],"Country":[{"id":11077,"filter":"country=11077","tag":"United States of America"}],"Guid":[{"id":"imdb://tt0356885"},{"id":"tmdb://371654"}],"Collection":[{"id":10140,"filter":"collection=10140","tag":"Walt Disney"}],"Role":[{"id":20903,"filter":"actor=20903","tag":"Ward Kimball","role":"Self","thumb":"https://image.tmdb.org/t/p/original/wEzFPqgY2YcccyanoRmb0pBDlkK.jpg"},{"id":20904,"filter":"actor=20904","tag":"Leonard Maltin","role":"Self - Host","thumb":"https://metadata-static.plex.tv/people/5d7768285af944001f1f71d5.jpg"}],"Field":[{"locked":true,"name":"collection"}]}]}}
```

**Comment by tidusjar** [comment]
So I see no issue here from the Plex end, everything looks good and Ombi should be able to parse that with no issues.

Are you 100% that your plex settings in Ombi is correct?

**Comment by twanariens** [comment]
Closed due to inactivity
