### ISSUE TITLE
Discord webhools failing

### ISSUE THREAD

**Issue by TheGOAngel** [Ombi-app/Ombi#4196]
**Describe the bug**

**To Reproduce**
1. Send test(or other) discord notification
**Expected behavior**
The UI will announce that the discord notification was sent successfully when it errored out.

**Logs (Logs directory where Ombi is located)**
```
2021-05-18 21:34:42.024 +00:00 [Debug] Batch acquisition of 1 triggers
2021-05-18 21:34:59.017 +00:00 [Error] Failed to send Discord Notification
System.Net.Http.HttpRequestException: Connection refused (discordapp.com:443)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Ombi.Api.OmbiHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ombi.Api.Api.Request(Request request, CancellationToken token)
   at Ombi.Api.Discord.DiscordApi.SendMessage(DiscordWebhookBody body, String webhookId, String webhookToken)
   at Ombi.Notifications.Agents.DiscordNotification.Send(NotificationMessage model, DiscordNotificationSettings settings)
2021-05-18 21:35:00.001 +00:00 [Debug] Batch acquisition of 0 triggers
2021-05-18 21:35:00.001 +00:00 [Debug] Calling Execute on job DVR.ISickRageSync
2021-05-18 21:35:00.016 +00:00 [Debug] Trigger instruction : NoInstruction
```
**Desktop (please complete the following information):**
 - OS: windows 10

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]
- Media Server Plex
- Database Type: SQLite
**Additional context**
Migrating from 3.0.5223 to 4.0.991.0. 3.0.5223. Was not an issue before migrating. Same error with clean install.
ombi is running on Linux 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019.

**Comment by tidusjar** [comment]
Just want to confirm you are using the correct token right?

**Comment by TheGOAngel** [comment]
Yes, directly copying and pasting it from the v3 to v4 site & tried copying it directly from discord and creating a new webhook.

**Comment by sephrat** [comment]
Are you still facing this issue?
Cannot reproduce on my side
