### ISSUE TITLE
Cannot connect to Radarr- JSON decode error

### ISSUE THREAD

**Issue by AbstractUmbra** [Ombi-app/Ombi#4215]
**Describe the bug**

My Radarr connection has started failing since updating Radarr to v4+.

**To Reproduce**
1. Add a connection to a Radarr v4+ instance.
2. Attempt to connect with correct details.
3. Error should happen.

**Expected behavior**
I expect the connection to happen and for the quality profiles etc to be populated.

**Screenshots**
https://images.abstractumbra.xyz/BB_eGVPzj27smw.png (not very helpful, sorry)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

```log
2021-06-07 20:46:58.306 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-07 20:46:58.306 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-07 20:46:58.306 +01:00 [Information] Received HTTP response headers after 0.4938ms - 404
2021-06-07 20:46:58.306 +01:00 [Information] End processing HTTP request after 0.603ms - 404
2021-06-07 20:46:58.307 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/radarr/api/system/status
2021-06-07 20:47:04.295 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-07 20:47:04.295 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-07 20:47:04.296 +01:00 [Information] Received HTTP response headers after 0.483ms - 404
2021-06-07 20:47:04.296 +01:00 [Information] End processing HTTP request after 0.5806ms - 404
2021-06-07 20:47:04.296 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/radarr/api/system/status
2021-06-07 20:47:05.221 +01:00 [Debug] Batch acquisition of 1 triggers
2021-06-07 20:47:05.221 +01:00 [Debug] Batch acquisition of 0 triggers
2021-06-07 20:47:05.221 +01:00 [Debug] Calling Execute on job DVR.IRadarrSync
2021-06-07 20:47:05.224 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/movie
2021-06-07 20:47:05.224 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/movie
2021-06-07 20:47:05.225 +01:00 [Information] Received HTTP response headers after 0.56ms - 404
2021-06-07 20:47:05.225 +01:00 [Information] End processing HTTP request after 0.6719ms - 404
2021-06-07 20:47:05.225 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/radarr/api/movie
2021-06-07 20:47:05.225 +01:00 [Error] Failed caching queued items from Radarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Radarr.Models.MovieResponse]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'message', line 2, position 12.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
   at Ombi.Api.Radarr.RadarrApi.GetMovies(String apiKey, String baseUrl)
   at Ombi.Schedule.Jobs.Radarr.RadarrSync.Execute(IJobExecutionContext job)
```

It seems there is a HTTP 404 (?) and a JSON decode error from `/api/movie`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version: 4.0.1403
- Media Server: Plex
- Database Type: SQLite

**Additional context**
Unsure if more is needed. Happy to provide if so.

**Comment by tidusjar** [comment]
What happens when you switch the v3 switch on first?

**Comment by AbstractUmbra** [comment]
With `V3` enabled, the following error logs occur:

```log
2021-06-08 08:49:38.501 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/v3/rootfolder
2021-06-08 08:49:38.501 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/v3/rootfolder
2021-06-08 08:49:38.541 +01:00 [Information] Received HTTP response headers after 40.6544ms - 200
2021-06-08 08:49:38.541 +01:00 [Information] End processing HTTP request after 40.8119ms - 200
2021-06-08 08:49:38.582 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/v3/qualityProfile
2021-06-08 08:49:38.582 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/v3/qualityProfile
2021-06-08 08:49:38.584 +01:00 [Information] Received HTTP response headers after 1.5554ms - 200
2021-06-08 08:49:38.584 +01:00 [Information] End processing HTTP request after 1.7462ms - 200
2021-06-08 08:49:43.111 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-08 08:49:43.111 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-08 08:49:43.111 +01:00 [Information] Received HTTP response headers after 0.5194ms - 404
2021-06-08 08:49:43.111 +01:00 [Information] End processing HTTP request after 0.6194ms - 404
2021-06-08 08:49:43.112 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/radarr/api/system/status
2021-06-08 08:49:52.624 +01:00 [Debug] Batch acquisition of 0 triggers
2021-06-08 08:50:21.116 +01:00 [Information] Start processing HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-08 08:50:21.116 +01:00 [Information] Sending HTTP request "GET" http://localhost:7878/radarr/api/system/status
2021-06-08 08:50:21.117 +01:00 [Information] Received HTTP response headers after 0.6782ms - 404
2021-06-08 08:50:21.117 +01:00 [Information] End processing HTTP request after 0.8402ms - 404
2021-06-08 08:50:21.117 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/radarr/api/system/status
2021-06-08 08:50:22.372 +01:00 [Debug] Batch acquisition of 0 triggers
```

**Comment by tidusjar** [comment]
This has been resolved in the develop build
