### ISSUE TITLE
Username '' is invalid, can only contain letters or digits.

### ISSUE THREAD

**Issue by maxxoverclocker** [Ombi-app/Ombi#4238]
**Describe the bug**
Unable to use Emby users with a period in the username. I receive the message 'Username '' is invalid, can only contain letters or digits.' in the admin UI.

**To Reproduce**
1) Click 'Users'
2) Click 'Edit' on a user that exists in Emby with a period in the username
3) Fill out the 'Username' field (for example, first.last)
4) Click 'Update'

**Expected behavior**
I would expect to be able to update the username to reflect what is in Emby. This worked in 3.x, upon upgrading to 4.x about 75% of my Emby accounts cannot log into Ombi due to this issue.

**Logs**
N/A, nothing gets logged when I click the 'Update' button. This appears to be a UI issue.

**Ombi Version**

    Version: 4.0.1430
    Media Server: Emby
    Database Type: SQLite

**Additional context**
I was able to update the user 'userName' field via the Ombi API, however, the field is still blank when using the admin UI and the users are still unable to log in. The following gets logged when a user with a period in their username attempts to log in:

```
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
      System.ArgumentNullException: Value cannot be null. (Parameter 'value')
         at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
         at System.Security.Claims.Claim..ctor(String type, String value)
         at Ombi.Controllers.V1.TokenController.CreateToken(Boolean rememberMe, OmbiUser user)
         at Ombi.Controllers.V1.TokenController.GetToken(UserAuthModel model)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
         at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
```

**Comment by tidusjar** [comment]
So in Emby, the users have a period e.g. `john.doe` and they cannot log in and you cannot update the user?

In the user management grid, there's a User Type column, what does that state for this user, and does that look correct?

**Comment by tidusjar** [comment]
After re-reading the message and looking at your supplied log, looks like your users have lost their Username? Can you reach out to me on Discord and we can chat through this? Might be a quicker way to resolve

**Comment by maxxoverclocker** [comment]
@tidusjar sure thing that works for me! But this is a bit embarrassing... I don't use discord often. I don't see you as a member of the Ombi discord. Not sure how to message you there.

**Comment by maxxoverclocker** [comment]
**FIXED**

A huge shoutout to @tidusjar for help with this!!! It appears the problem was related to the upgrade from Ombi v3 to v4. Still not certain what caused the issue as I'm running a pretty odd implementation of LDAP sync'd Emby users and Ombi is running inside docker. This was a two fold problem:

1. In the Ombi sqlite Ombi.db file in the AspNetUsers table, the UserName column was NULL for the majority of my users
2. In the Ombi sqlite Ombi.db file in the AspNetUsers table, the UserType column was set to '4' (emby connect user) instead of '3' (local emby account)

Here's how the issue was resolved:
`# Stop the docker container
docker container stop ombi2

# Open the Ombi.db sqlite database
sqlite3 Ombi.db

# Show tables
.tables

# Show schema for the AspNetUsers table
.schema AspNetUsers

# SELECT all users where the UserName column is NULL
SELECT UserName,NormalizedUserName,Alias,UserType
FROM AspNetUsers
WHERE UserName is NULL;

# UPDATE the UserName column to mirror the Alias column for the user WHERE the UserName is NULL
UPDATE AspNetUsers
SET UserName = LOWER(Alias)
WHERE UserName is NULL;

# UPDATE the UserType to 3 (Local Emby User Account) WHERE the UserType is 4 (Emby Connect)
UPDATE AspNetUsers
SET UserType = 3
WHERE UserType = 4;

# Save a copy of the database
.save Ombi.db.new

.quit

# Move the new database copy in place of the old database copy
mv Ombi.db Ombi.db.old && mv Ombi.db.new Ombi.db

# Start the docker container
docker container start ombi2`

**Comment by artarya** [comment]
Maybe because of this, you defined another user name in your model
