### ISSUE TITLE
Unable to 'Load Libraries' for Jellyfin

### ISSUE THREAD

**Issue by psi5asp** [Ombi-app/Ombi#4266]
**Describe the bug**
Load Libraries does not work when adding a Jellyfin server

**To Reproduce**
1. Login as an admin user
2. Go to Settings menu - Media Server tab and select Jellyfin
3. Configure a valid Jellyfin server and test connection to confirm setup
4. Click on Load Libraries to see error

**Expected behavior**
Load Libraries should allow the selection of which Jellyfin libraries to include/exclude with Onbi.

**Screenshots**
![image](https://user-images.githubusercontent.com/41772110/126857735-2f568f70-ee93-4107-9561-83d674a1c570.png)

**Logs (Logs directory where Ombi is located)**
- Ombi Logs:
`..........[Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Api.Jellyfin.JellyfinApi.<>c.<GetLibraries>b__9_0(MediaFolders x)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at Ombi.Api.Jellyfin.JellyfinApi.GetLibraries(String apiKey, String baseUrl)
   at Ombi.Controllers.V1.External.JellyfinController.GetLibaries(JellyfinServers server)
   at lambda_method1847(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)`

- Jellyfin Logs (aroung the same time period, probably unrelated since these entries are rampant in Jellyfin logs):
` [WRN] [69] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.XXX:8096/users/*****************************/items?Recursive=True&IncludeItemTypes=Movie&Fields=ProviderIds,Overview,ParentId&startIndex=5801&limit=200&IsVirtualItem=False" to "192.168.0.XXX" in 0:00:23.272814 with Status Code 200
[WRN] [26] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.XXX:8096/users/*****************************/items?Recursive=True&IncludeItemTypes=Movie&Fields=ProviderIds,Overview,ParentId&startIndex=6001&limit=200&IsVirtualItem=False" to "192.168.0.XXX" in 0:00:23.2008483 with Status Code 200
...etc.
`

**Desktop (please complete the following information):**
OS: Linux 5.10.17-v8+ (Arm64)

**Ombi Version (please complete the following information):**
Version: 4.0.1448
Media Server : Emby or Jellyfin
Database Type: Sqlite
Additional context

**Additional context**
Using Opera Version:77.0.4054.277

**Comment by psi5asp** [comment]
new issue from https://github.com/Ombi-app/Ombi/issues/2389#issuecomment-882811597

**Comment by tidusjar** [comment]
I fixed this last night. It's currently in develop
