### ISSUE TITLE
Ombi isn't detecting any of my Anime

### ISSUE THREAD

**Issue by CubeComming** [Ombi-app/Ombi#4267]
**Describe the bug**
Ombi isn't detecting any of my Anime. Looks like an issue with the Plex scan.

**To Reproduce**
1. Go to Discovery
2. You can see that none Anime are marked as available
3. Go to Plex Settings
4. Try to "Manually Run Full Sync"
5. Nothing new is getting detected

**Expected behavior**
Marking Available Animes as Available

**Logs (Logs directory where Ombi is located)*

Docker:

```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.2.42:32400/library/metadata/77458


warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]


      Exception thrown when attempting to cache the Plex Content in server Lukas-Server


      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.


         at Newtonsoft.Json.JsonTextReader.ParseValue()


         at Newtonsoft.Json.JsonTextReader.Read()


         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)


         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)


         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)


         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)


         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)


         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)


         at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408


warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]


      Exception thrown when attempting to cache the Plex Content in server Lukas-Server


      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.


       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'.


         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)


         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()


         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)


         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)


         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)


         --- End of inner exception stack trace ---


         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)


         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)


         at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges()


         at Ombi.Store.Repository.BaseRepository`2.SaveChangesAsync()


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.2.42:32400/library/metadata/77458


warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]


      Exception thrown when attempting to cache the Plex Content in server Lukas-Server


      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.


         at Newtonsoft.Json.JsonTextReader.ParseValue()


         at Newtonsoft.Json.JsonTextReader.Read()


         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)


         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)


         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)


         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)


         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)


         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)


         at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)


         at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560


fail: Ombi.Api.Api[1000]


      StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408

```

File:
```
2021-07-25 21:10:46.225 +02:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "Lukas-Server"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges()
   at Ombi.Store.Repository.BaseRepository`2.SaveChangesAsync()
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)

2021-07-25 21:10:46.232 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:10:46.232 +02:00 [Debug] Deleting trigger
2021-07-25 21:10:46.234 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:10:46.240 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:10:46.240 +02:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2021-07-25 21:11:13.165 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:11:41.572 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:12:05.954 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:12:15.497 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:12:15.497 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:12:15.498 +02:00 [Debug] Calling Execute on job System.IRefreshMetadata
2021-07-25 21:12:15.498 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:12:15.503 +02:00 [Debug] Deleting trigger
2021-07-25 21:12:16.520 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560
2021-07-25 21:12:16.662 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408
2021-07-25 21:12:17.026 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:12:17.026 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:12:17.027 +02:00 [Debug] Deleting trigger
2021-07-25 21:12:17.027 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:12:17.031 +02:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2021-07-25 21:12:20.490 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:12:20.490 +02:00 [Debug] Deleting trigger
2021-07-25 21:12:41.896 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:13:08.110 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:13:31.728 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:13:59.819 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:14:28.127 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:14:57.609 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:15:00.000 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:15:02.194 +02:00 [Debug] Calling Execute on job DVR.IRadarrSync
2021-07-25 21:15:02.229 +02:00 [Debug] Trigger instruction : NoInstruction
2021-07-25 21:15:26.892 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:15:53.477 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:16:21.176 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:16:51.121 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:17:16.262 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:17:44.151 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:18:08.047 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:18:10.559 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.2.42:32400/library/metadata/77458
2021-07-25 21:18:10.567 +02:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "Lukas-Server"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, Int32 itemId)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)
2021-07-25 21:18:10.570 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:18:10.570 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:18:10.570 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:18:10.570 +02:00 [Debug] Deleting trigger
2021-07-25 21:18:10.571 +02:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2021-07-25 21:18:37.537 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:19:06.521 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:19:30.133 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:19:30.134 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:19:30.134 +02:00 [Debug] Calling Execute on job System.IRefreshMetadata
2021-07-25 21:19:30.150 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:19:30.150 +02:00 [Debug] Deleting trigger
2021-07-25 21:19:31.032 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=287560
2021-07-25 21:19:31.156 +02:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=325408
2021-07-25 21:19:31.349 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:19:31.349 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:19:31.349 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:19:31.350 +02:00 [Debug] Deleting trigger
2021-07-25 21:19:31.350 +02:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
2021-07-25 21:19:34.219 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-07-25 21:19:34.219 +02:00 [Debug] Deleting trigger
2021-07-25 21:19:54.855 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:20:24.465 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:20:52.017 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:21:19.315 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:21:44.980 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:22:13.604 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:22:42.660 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:23:09.930 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:23:38.676 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:24:08.171 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:24:33.801 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:24:58.569 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:25:25.034 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:25:48.780 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:26:16.320 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:26:44.935 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:27:08.618 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:27:32.646 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:28:01.513 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:28:26.130 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:28:53.110 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:29:19.858 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:29:46.058 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:30:00.000 +02:00 [Debug] Calling Execute on job DVR.ICouchPotatoSync
2021-07-25 21:30:00.001 +02:00 [Debug] Batch acquisition of 1 triggers
2021-07-25 21:30:00.005 +02:00 [Debug] Batch acquisition of 0 triggers
2021-07-25 21:30:00.026 +02:00 [Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
2021-07-25 21:30:00.069 +02:00 [Debug] Trigger instruction : NoInstruction

```

**Desktop (please complete the following information):**
 - OS: Raspberry Pi (Debian)

**Ombi Version (please complete the following information):**
 - Version 4.0.1430
- Media Server  1.23.5.4862

**Comment by tidusjar** [comment]
That’s odd. Can you delete your ombiexternal.db and then restart ombi and kick off a manual sync?

**Comment by CubeComming** [comment]
Thank you very much for your quick answer.
He now seems to find some... (like 5% maybe..)

```

**Comment by psi5asp** [comment]
This may be related - as it may also be an Ombi episode searching issue.

Not sure where Ombi gets its seasons list from for Anime, but for example "Bleach" has 16 Seasons ([https://www.thetvdb.com/series/bleach](url) & [https://www.tvmaze.com/shows/1905/bleach/seasons](url)), yet Ombi shows only 1 season with all the episodes under Season 1 (as such, missing episodes 21+, because they're in Season's 2-3-4+, etc.)

![image](https://user-images.githubusercontent.com/41772110/126936177-e96ab7c8-8817-439e-95aa-2bf4ff8bdfd6.png)

**Comment by psi5asp** [comment]
Having an Ombi library export feature (video, folder location, title, season, source, etc.) would make it easy to identify issues with library imports - can then compare with Plex, etc. libraries to isolate which media has issues.

**Comment by tidusjar** [comment]
This is then due to a mismatch between TvDB and TheMovieDb. Ombi is using TheMovieDB for all of the TV Information.
There's not much I can do in this scenario other than:

* Write my own mapping between them
* Change TV Source

The second I'm not going to do, i've only just done it to move away from TvMaze due to the compatibility issues

**Comment by psi5asp** [comment]
Can admins be allowed to pick the sources to match their customised components? (eg diffferent packages use different sources, well let admins pick which source is used in Ombi to match their setups, etc.)

**Comment by psi5asp** [comment]
Anime's also not working for Jellyfin - I've deleted the db and restarted, rescanned (rebuild db), but still missing from Plex scan and Jellyfin scan....I get these errors, not sure if they're related or not

[Ombi-4267-log2.txt](https://github.com/Ombi-app/Ombi/files/6876814/Ombi-4267-log2.txt)
[Ombi-4267-log3.txt](https://github.com/Ombi-app/Ombi/files/6876815/Ombi-4267-log3.txt)
[Ombi-4267-log1.txt](https://github.com/Ombi-app/Ombi/files/6876816/Ombi-4267-log1.txt)

**Comment by CubeComming** [comment]
Can it use sonarr to detect my Anime?
There is a "Scan for Availability" button...
Do I have to enable Sonarr for it to do that? Cause I don't want him to add Series by himself...

**Comment by psi5asp** [comment]
I believe because Plex and Jellyfin are end user accessible media players/platforms, that is why Ombi uses their media - it makes sense to do it that way because Radarr/Sonnarr/etc. are admin tools to manage/control media - they're not media players for audiences.

ie Someone requests a Show/Movie in Ombi, they expect it to be in Plex/Jellyfin/Emby to play once completed....regardless of how Sonarr/Radarr are used.

**Comment by CubeComming** [comment]
So will i have to match them all by hand? Or is there gonna be a pach?

**Comment by tidusjar** [comment]
Thanks for your feedback, To allow different sources to be chose for different media types is something that I could consider doing in the future, but it's not going to be a short term thing.

With my other suggestions, again these are not short term fixes and will require a lot of upfront work and maintance. For now unfortunately I am not able to do anything in the short term

**Comment by CubeComming** [comment]
For anyone else having the problem, i moved to overseerr and that seems to work way better.
