### ISSUE TITLE
Requests for TV shows with different TVDB and TMDB IDs fail

### ISSUE THREAD

**Issue by MaleNurse** [Ombi-app/Ombi#4278]
**Describe the bug**
Requests for TV shows with different TVDB and TMDB IDs fail. This may be a continuation of #3717 

**To Reproduce**
Request and approve "The Problem with Jon Stewart". TVDB and TMDB have different IDs ([400756](https://www.thetvdb.com/series/the-problem-with-jon-stewart) and [123149](https://www.themoviedb.org/tv/123149-the-problem-with-jon-stewart), respectively).

**Expected behavior**
The request is successfully passed to Sonarr

**Logs**
```
2021-07-23 11:24:16.629 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/400756?api_key=[redacted]&language=en&append_to_response=videos,credits,similar,recommendations,external_ids,keywords,images

2021-07-23 11:34:27.387 -07:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
2021-07-23 11:34:27.387 -07:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model)
```

**Desktop (please complete the following information):**
 - OS: User running Windows 10 Pro x64, Vivaldi and Chrome browsers. Ombi running in Docker on Ubuntu 20.04.2 LTS

**Ombi Version (please complete the following information):**
 - Version 4.0.1458   
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
When testing with the same show I do not get this error, it is processed with the correct TvDbId and sent to Sonarr

![image](https://user-images.githubusercontent.com/6642220/127821181-36bc18a5-cd5a-4958-bd5c-763166ae7585.png)

**Comment by MaleNurse** [comment]
Weird. I tried deleting and re-adding the request, and this time it worked. I'd done that numerous times before, but without success. I'll close this and reopen if I come across this issue again. Thanks for the app and looking into this issue.

**Comment by joseph-cheung** [comment]
It is still relevant with **ID 130330 on TMDB**  and **ID 407897 on TVDB**.
