### ISSUE TITLE
Browser shows up blank when accessing the ombi app

### ISSUE THREAD

**Issue by vnl** [Ombi-app/Ombi#4290]
**Describe the bug**
I see a blank screen without any movies or TV shows showing up in all the tabs (discover, requests, ..)
Please note, the same connection through the mobile app (iOS) is working perfectly and currently managing the requests from there. 

**To Reproduce**
1. Go to the installed URL (in my case it is the IP address of the docker container and port)
2. You see blank screen in place of movies and TV shows. Only Menus of the app is shown

**Expected behavior**
It should show, movies and TV shows in the discover tab, it show any requested movie/TV show in the Requests tab. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1355466/129680829-62869902-49e8-4f12-8894-9f0042cc3cc1.png)
![image](https://user-images.githubusercontent.com/1355466/129680894-6c7a891b-73b9-4850-8903-d7b25849f7cb.png)

**Logs (Logs directory where Ombi is located)**
```
2021-08-17 08:02:45.974 +01:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Engine.BaseMediaEngine.DefaultLanguageCode(String currentCode)
   at Ombi.Core.Engine.V2.TvSearchEngineV2.Popular(Int32 currentlyLoaded, Int32 amountToLoad, String langCustomCode)
   at Ombi.Controllers.V2.SearchController.PopularTv(Int32 currentPosition, Int32 amountToLoad)
   at lambda_method586(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)
```

**Desktop (please complete the following information):**
 - OS: Linux 4.4.180+ #41890 SMP Fri Jun 25 02:37:14 CST 2021
 I am running Ombi as a docker container from the image: linuxserver/ombi:latest
URL: https://github.com/linuxserver/docker-ombi

**Ombi Version (please complete the following information):**
 - Version: 4.0.1430
- Media Server: Plex
- Database Type: SQLite

**Additional context**
The mobile app loads up everything correctly and I am currently managing requests from the mobile app. It is only the browser access that is causing an issue. 
I have tried in all the browsers I have installed (Safari, Chrome, Chromium Edge, Brave and Firefox) and it is the same blank screen. 

I am not sure if I need to open an issue within the docker image project.

**Comment by tidusjar** [comment]
Looks like it's not picking up your user correctly, I've just pushed a potential fix to the development branch, would be good if you could give that a go
