### ISSUE TITLE
Can't connect to Sonarr

### ISSUE THREAD

**Issue by yes2danny** [Ombi-app/Ombi#4292]
**Describe the bug**
Can't connect to Sonarr

Having issues linking Sonarr with OMBI, I can't seem to get past the profile quality area.  
It isn't letting me select anything and just says 

> A Default Quality Profile is required

When I try to click one it Loads forever.

**To Reproduce**
 I'm pretty sure no one else has this issue. So I don't know what to add.

**Expected behavior**
For Sonarr to connect to OMBI

**Screenshots**
https://imgur.com/jNsU00H

**Logs (Logs directory where Ombi is located)**
 Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
      System.UriFormatException: Invalid URI: The hostname could not be parsed.
         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
         at System.UriBuilder.get_Uri()
         at Ombi.Helpers.UriHelper.ReturnUri(String val, Int32 port, Boolean ssl)
         at Ombi.Settings.Settings.Models.External.ExternalSettings.get_FullUri()
         at Ombi.Controllers.V1.External.SonarrController.GetProfiles(SonarrSettings settings)
         at lambda_method2734(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context)
         at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context)

**Desktop (please complete the following information):**
Windows 10?

**Ombi Version (please complete the following information):**
 - Version 4.0.1466   
- Media Server Plex

**Comment by tidusjar** [comment]
The log states that your hostname cannot be parsed. So you sure it's a valid hostname?

**Comment by yes2danny** [comment]
localhost:8989 I have that. which opens Sonarr up.

**Comment by tidusjar** [comment]
try http://localhost8989/

This is assuming that you are running ombi on the same machine as you are running sonarr on?

**Comment by yes2danny** [comment]
Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server Netflix On Coke
      System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (192.168.0.236:28785)
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken)
         at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost)
         at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch)
         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch)
         at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch)



What does this mean?
ALso I tried it and It said 
"Please check your entered values"
which highlighted the "A Default Quality Profile is required"
and "A Default Root Folder is required" But they won't let me click or select any folder or anything.

**Comment by tidusjar** [comment]
It is possible that `192.168.0.236:28785` is not actually your Plex server address?

Because the original issue is about your sonarr connection and now the above is about plex?

**Comment by CalvoUTN** [comment]
I think I have same issue. I don't know the correct etiquette in these issues, so I'll tag @tidusjar and hope that's OK. This is my config:

![Screenshot_4](https://user-images.githubusercontent.com/49721926/142358391-41326aab-62bc-40cd-b737-268ed3780b5c.png)

When I click "Test Connection" I get a message that says _Please check your entered values_, The logs from the container say this:

```
2021-11-18T05:50:27.517710289Z          at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context),
2021-11-18T05:50:27.517703541Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context),
2021-11-18T05:50:27.517706922Z          at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context),
2021-11-18T05:50:27.517699922Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context),
2021-11-18T05:50:27.517693587Z          at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult),
2021-11-18T05:50:27.517690210Z          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider),
2021-11-18T05:50:27.517686802Z          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext),
2021-11-18T05:50:27.517683186Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger),
2021-11-18T05:50:27.517679490Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope),
2021-11-18T05:50:27.517671760Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted),
2021-11-18T05:50:27.517675409Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted),
2021-11-18T05:50:27.517668390Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context),
2021-11-18T05:50:27.517664720Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted),
2021-11-18T05:50:27.517661092Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted),
2021-11-18T05:50:27.517657426Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted),
2021-11-18T05:50:27.517653977Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context),
2021-11-18T05:50:27.517650315Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted),
2021-11-18T05:50:27.517643031Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments),
2021-11-18T05:50:27.517646652Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask),
2021-11-18T05:50:27.517639507Z          at Ombi.Controllers.V1.External.RadarrController.GetProfiles(RadarrSettings settings),
2021-11-18T05:50:27.517635901Z          at Ombi.Api.Radarr.RadarrV3Api.GetProfiles(String apiKey, String baseUrl),
2021-11-18T05:50:27.517631158Z          at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken),
2021-11-18T05:50:27.517618067Z          at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings),
2021-11-18T05:50:27.517610746Z          at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType),
2021-11-18T05:50:27.517614386Z          at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings),
2021-11-18T05:50:27.517606969Z          at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType),
2021-11-18T05:50:27.517603234Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent),
2021-11-18T05:50:27.517581912Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue),
2021-11-18T05:50:27.517585983Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue),
2021-11-18T05:50:27.517573547Z       To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.,
2021-11-18T05:50:27.517578000Z       Path 'message', line 2, position 12.,
2021-11-18T05:50:27.517568174Z       Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Radarr.Models.V3.RadarrV3QualityProfile]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.,
2021-11-18T05:50:27.517563548Z       Something bad happened, ErrorMiddleware caught this,
2021-11-18T05:50:27.503784450Z       StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.0.68:7878/192.168.0.68/api/v3/qualityProfile,
2021-11-18T05:50:27.517543395Z fail: Ombi.ErrorHandlingMiddleware[0],
2021-11-18T05:50:27.503746299Z fail: Ombi.Api.Api[1000]
```

I think this particular one was from trying add Radarr, but had the same issue with Sonarr.

**Comment by tidusjar** [comment]
In this error I can see that you has different config as the url that was being generated is this. 

http://192.168.0.68:7878/192.168.0.68

**Comment by shutchi2** [comment]
Just started getting this error also. Radarr and Lidarr still connect correctly, but Sonarr won't load the profile info. Can connect to Sonarr from the ombi server using a browser. Test connection from Ombi says connected OK, but still no profiles. Had been working for a few years prior to two weeks ago.

**Comment by tidusjar** [comment]
Sound like you have a different issue. Press the load folders and then upload a log file?

**Comment by shutchi2** [comment]
Fixed the issue. Target machine was set to public network, as opposed to private, and changing it back corrected the Sonarr issue. I did find it odd that Lidarr and Radarr were unaffected, but all are working now.
