### ISSUE TITLE
System.Exception with lots of commas when adding show to Sonarr

### ISSUE THREAD

**Issue by imchasingshadows** [Ombi-app/Ombi#4319]
**Describe the bug**
When adding shows via Ombi to sonarr i receive this very weird error. Adding movies via Radarr is working fine

**To Reproduce**
1. Add a sonarr connection
2. Search for a show
3. Request/add the show

**Logs (Logs directory where Ombi is located)**

```
at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
[41m[30mfail[39m[22m[49m: Ombi.Core.Senders.TvSender[0]
Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
at Ombi.Core.Senders.TvSender.Send(ChildRequests model)
```

**Desktop (please complete the following information):**
 - Unraid (Docker)

**Ombi Version (please complete the following information):**
 - 4.0.1506
- Database Type: SQLite

**Comment by tidusjar** [comment]
Are you sure your sonarr settings are correct?

**Comment by imchasingshadows** [comment]
Yes I'm pretty sure theyre correct as my Radarr/Sonarr settings don't differ that much. I tested with both anime and normal shows with the same result. Is there anything in particular you think i should check? Is there maybe to get more verbose logging with the docker image?

**Comment by tidusjar** [comment]
Can you double check on the exception, because it shouldn't output `,,,,,,,,,,,,,,` for example, the exception being thrown should also contain more information so can you please provide the full error?

**Comment by imchasingshadows** [comment]
When viewing logs in `Settings > System > Logs` this is realy all the information im getting :\

```
2021-10-01 13:33:50.145 +02:00 [Debug] Batch acquisition of 0 triggers
2021-10-01 13:34:07.865 +02:00 [Debug] Batch acquisition of 1 triggers
2021-10-01 13:34:07.865 +02:00 [Debug] Batch acquisition of 0 triggers
2021-10-01 13:34:07.865 +02:00 [Debug] Calling Execute on job Notifications.INotificationService
2021-10-01 13:34:07.899 +02:00 [Debug] Trigger instruction : DeleteTrigger
2021-10-01 13:34:07.899 +02:00 [Debug] Deleting trigger
2021-10-01 13:34:10.248 +02:00 [Error] Exception thrown when attempting to send series over to Sonarr
System.Exception: ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
2021-10-01 13:34:10.248 +02:00 [Error] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s)
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model)
2021-10-01 13:34:34.979 +02:00 [Debug] Batch acquisition of 1 triggers
2021-10-01 13:35:00.000 +02:00 [Debug] Batch acquisition of 0 triggers
2021-10-01 13:35:00.000 +02:00 [Debug] Calling Execute on job DVR.ISickRageSync
2021-10-01 13:35:00.004 +02:00 [Debug] Trigger instruction : NoInstruction
2021-10-01 13:35:24.014 +02:00 [Debug] Batch acquisition of 0 triggers
2021-10-01 13:35:53.872 +02:00 [Debug] Batch acquisition of 0 triggers
```

**Comment by tidusjar** [comment]
Can you get the log from the logs folder where you mapped your config folder?

**Comment by imchasingshadows** [comment]
Yes but that is the same file. I did make sure to check but there is no difference between the logs i posted above

**Comment by tidusjar** [comment]
For some reason your logs are not complete, which is going to make this a bit more difficult.

The user that made the request, do they have any quality profiles or root folders assigned to them?

What is the error in Sonarr when this happens?

**Comment by twanariens** [comment]
Closed due to inactivity
