### ISSUE TITLE
Email notifications are not working

### ISSUE THREAD

**Issue by mwgaillardetz** [Ombi-app/Ombi#4374]
**Describe the bug**
I am running into an issue sending email notifications. It worked great up until the beginning of this month on Windows 10. I first tried obtaining a new app specific password, but that did not fix it so I tried switching email providers. I tried gmail, icloud, yahoo, and microsoft - all using app specific passwords. Alas, no luck as they all receive the same error listed below. I am using port 587 with "Enable" & "Enable SMTP Authentication" turned on. I have also allowed for less secure apps in gmail and yahoo with no change in the error output. Any help is appreciated!

**To Reproduce**
1. Enable email notifications and smtp authentication
2. Set hostname for gmail: smtp.gmail.com
3. Generate and provide app specific password and allow less secure apps
4. Test - email will not go through

**Expected behavior**
Email notification should go through to the admin email account. 

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
2021-10-26 12:22:45.195 -04:00 [Error] Exception when attempting to send an email
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 52.96.111.98:25
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
2021-10-26 12:22:45.196 -04:00 [Warning] Exception when testing Email Notifications
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 52.96.111.98:25
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings)
at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings)

**Desktop (please complete the following information):**
 - OS: [Windows 10 19043.1288]

**Ombi Version (please complete the following information):**
 - Version [4.3]
- Media Server [Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by Raykazi** [comment]
I'm having a similar issue and it has been determined that my ISP is blocking inbound and outbound connections to port 25. I feel like that may be the culprit here as well.

**Comment by harrv** [comment]
@mwgaillardetz,  Here are the settings you need for gmail. I see you are using the correct port (587) but you haven't yet said what you have the toggle switches set to.

![image](https://user-images.githubusercontent.com/7154372/142584742-3d718609-ce83-4888-a646-48f61d196162.png)
