### ISSUE TITLE
Fresh Ombi install can't connect to JellyFin running on same machine

### ISSUE THREAD

**Issue by DuvelCorp** [Ombi-app/Ombi#4415]
### My Config

Ubuntu 20.04 server x64.
Ombi 4.7.1, Fresh and first install (I discover it) - still sqlite for now.
Jellyfin 10.7.7. Running sweet for months.

Both apps are running  on the same server, with their default ports.

First, its hard to know if I am really doing the right things, because this is the documentation : 
![image](https://user-images.githubusercontent.com/33682764/142866662-783b14f4-61b0-4576-8e7c-97530e429e76.png)
:-) (no worries)

### The bug

Connection to Jellyfin is refused.

Since there's nothing in the Ombi interface to specify a user/password for the connection to Jellyfin, I have supposed that  its done with API key. Thus I have generated this in Jellyfin:
![image](https://user-images.githubusercontent.com/33682764/142865838-07bf00f1-7b0e-4302-9c77-84784d1e6ae4.png)

I ended up with this config in Ombi:

![image](https://user-images.githubusercontent.com/33682764/142867207-2ef80831-01cc-493b-b9c0-8f00f1d24599.png)

And when I test, I receive the message 

> We could not connect to the Jellyfin server Test!

I have tried : 
- With server's IP instead of localhost (thus 192.168.2.4)
- With or Without API key
- With several API keys generated in Jellyfin (Ombi, ombi)
- With same Base URL as my Jellyfin, so for instance /netflix

Always the same issue.
Its unclear to me if I really have to specify a _Base URL_ and/or _External facing hostname_ but I dont see any reason for it at this point because we are on the same machine,  with no firewall or reverse proxy in between the 2 applications. 

### Ombi Logs

```
System.Net.Http.HttpRequestException: Connection refused (localhost:8096)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Jellyfin.JellyfinApi.GetUsers(String baseUri, String apiKey) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Jellyfin/JellyfinApi.cs:line 32
   at Ombi.Controllers.V1.External.TesterController.Jellyfin(JellyfinServers settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 352
2021-11-22 12:44:25.729 +00:00 [Debug] Batch acquisition of 0 triggers
```
I have checked logs on Jellyfin side and I don't see anything relevant.

###  On a Last Note

I have Sonarr, Radarr and Lidarr running on another Ubuntu server in the same subnet, and Ombi can connect to all of them !

So, is it just me that missed something big, or is there a bug somewhere ?

**Comment by sephrat** [comment]
This looks like a network issue. 
How did you install Ombi and Jellyfin? By any chance, did you install Ombi and/or Jellyfin on Docker or similar?

**Comment by redevening** [comment]
I have the same issue. I run both services in a docker compose file.

**Comment by sephrat** [comment]
> I have the same issue. I run both services in a docker compose file.

Assuming it's OP's case as well, please share your docker-compose file and screenshots of your Jellyfin config on Ombi (make sure you sanitize your API key) so we can troubleshoot the issue.

**Comment by redevening** [comment]
Thanks for the help.

The issue was with me running a kind of unique docker configuration inside the Windows WSL. Docker could not setup a valid network for the containers. I fixed it by using `network_mode:host`

After testing via curl from inside the Ombi container, I found out that the issue is indeed not with Ombi but rather a network issue. (`docker exec -it ombi /bin/bash; curl <JELLYFINURL>/web/index.html` also gives Connection refused)

### Working compose file:

```yaml
version: "3.4"
services:
  ombi:
    image: linuxserver/ombi:4.7.6
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=Europe/London
    volumes:
      - ${ROOT}/config/ombi:/config
    network_mode: "host"
    ports:
      - 3579:3579
    restart: unless-stopped

  media-server-jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${ROOT}/complete/movies:/data/movies
      - ${ROOT}/complete/tv:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/jellyfin:/config
    network_mode: "host"
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
```
