### ISSUE TITLE
Issue Comment Alias Bug

### ISSUE THREAD

**Issue by dpiper01** [Ombi-app/Ombi#4429]
**Describe the bug**
Whenever a comment is made on an issue, the server owners name is being used as the alias instead of the issue creators alias.

**To Reproduce**
1. Create an issue as an end user
2. Comment on the issue as the owner
3. End user receives the email with the comment but where it should say the end users name (Under Alias), it says the owners name.

**Expected behavior**
It should show the end users alias.

**Screenshots**

<img width="673" alt="Screenshot 2021-12-06 at 10 39 36 PM" src="https://user-images.githubusercontent.com/2280616/144962602-952a8259-f25a-4db6-8bc7-d154afde2f4c.png">

 _Note it should say Stef (End User) not Damien (Admin)_

**Logs (Logs directory where Ombi is located)**
`2021-12-06 22:28:03.978 -05:00 [Debug] Batch acquisition of 0 triggers
2021-12-06 22:28:30.538 -05:00 [Debug] Batch acquisition of 0 triggers
2021-12-06 22:28:37.643 -05:00 [Debug] Batch acquisition of 1 triggers
2021-12-06 22:28:37.643 -05:00 [Debug] Batch acquisition of 0 triggers
2021-12-06 22:28:37.643 -05:00 [Debug] Calling Execute on job Notifications.INotificationService
2021-12-06 22:28:40.838 -05:00 [Debug] Trigger instruction : DeleteTrigger
2021-12-06 22:28:40.838 -05:00 [Debug] Deleting trigger
2021-12-06 22:28:47.662 -05:00 [Debug] Batch acquisition of 1 triggers
2021-12-06 22:28:47.662 -05:00 [Debug] Batch acquisition of 0 triggers
2021-12-06 22:28:47.662 -05:00 [Debug] Calling Execute on job Notifications.INotificationService
2021-12-06 22:28:49.289 -05:00 [Debug] Trigger instruction : DeleteTrigger
2021-12-06 22:28:49.289 -05:00 [Debug] Deleting trigger`

**Desktop (please complete the following information):**
 - OS: Ubuntu Server (Docker)

**Ombi Version (please complete the following information):**
- Version: 4.30
- Media Server: Plex
- Database Type: MySQL

**Additional context**
The HTML code for the Issue Comment notification is below:

<p>Hi {Alias},</p>
<p>There is a new comment on your issue:<br /><br /><strong>{NewIssueComment}</strong></p>
<p>&nbsp;</p>
<p><em>A copy of your issue is stated below:</em></p>
<p><em>Category: {IssueCategory}</em></p>
<p><em>Subject: {IssueSubject}</em></p>
<p><em>Description: {IssueDescription}</em></p>
<p>&nbsp;</p>

**Comment by Firetop** [comment]
Just wanted to mention I have a similar issue with the MassEmail Notification feature.
it seems that everyone from the list is called the first user Alias; instead of each user being called their own Alias.

**Comment by twanariens** [comment]
Can you check if you still have these issues. I know some work has been done. We are currently on V4.15.2 (develop)

**Comment by Firetop** [comment]
> Can you check if you still have these issues. I know some work has been done. We are currently on V4.15.2 (develop)

I'm also on 4.15.2 and I just tried to send MassEmail using the Alias feature to myself and a select few people and I never even got the email this time; before I got it but my Alias was wrong.

Now I get nothing and checking the logs I see errors below:

`2022-03-23 21:24:57.692 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-23 21:25:24.148 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-23 21:25:45.372 -04:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
2022-03-23 21:25:45.480 -04:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
2022-03-23 21:25:46.239 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
   at Ombi.Core.Senders.MassEmailSender.DelayEmail(NotificationMessage msg, EmailNotificationSettings email) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MassEmailSender.cs:line 155
   at Ombi.Core.Senders.MassEmailSender.SendMassEmail(MassEmailModel model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MassEmailSender.cs:line 78
   at Ombi.Controllers.V1.NotificationsController.SendMassEmail(MassEmailModel model) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/NotificationsController.cs:line 52
   at lambda_method6369(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2022-03-23 21:25:53.117 -04:00 [Debug] Batch acquisition of 0 triggers`

**Comment by dpiper01** [comment]
> 4.3.2 Concurrent connections limit exceeded.

@Firetop I believe that error is an issue with Outlook and not Ombi. When I searched up the error, I found the following: `Under the new limit, up to three concurrent connections are allowed to send email messages at the same time` 

I also found this solution [1] not sure if it’s helpful!

[1] https://campus.barracuda.com/product/emailsecuritygateway/knowledgebase/501600000013uWLAAY/How+do+I+troubleshoot+421+4-3-2+The+maximum+number+of+concurrent+connections+has+exceeded+a+limit-+closing+transmission+channel%3F/

**Comment by Firetop** [comment]
> > 4.3.2 Concurrent connections limit exceeded.
> 
> @Firetop I believe that error is an issue with Outlook and not Ombi. When I searched up the error, I found the following: `Under the new limit, up to three concurrent connections are allowed to send email messages at the same time`
> 
> I also found this solution [1] not sure if it’s helpful!
> 
> [1] https://campus.barracuda.com/product/emailsecuritygateway/knowledgebase/501600000013uWLAAY/How+do+I+troubleshoot+421+4-3-2+The+maximum+number+of+concurrent+connections+has+exceeded+a+limit-+closing+transmission+channel%3F/

Yeah... I think you'll need to clarify a bit lol. Ombi does not tie into Outlook to send emails. Outlook could be completely closed.
Do you mean you think it's an issue with Microsoft Exchange?

I tried again and it went through this morning; I tried a second time and I have the same error again.
Seems that Microsoft have made changes to their Exchange Server mail policies: 

"Additional throttling limits for the SMTP Authentication protocol are:

30 messages per minute"

If I wait a while; it sends fine.

https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements#new-throttling-limit-for-concurrent-connections-that-submitmessages

It's not Outlook; since Ombi does not use Outlook to send the emails; and Outlook does not even need to be open for that to function. 

The article you sent was for Outlook in an corporate Environment where the administrators have access to their own Exchange servers; because this is not a corporate environment; the issue happens all the same with http://mail.office365.com/ as it does with the Outlook application.

I'll have to wait 30 minutes to test again; but so far the one test that did work included the correct Alias; but I still need to confirm it actually sent to other people and not just myself.

Will follow up shortly when I run a few more tests.

**Comment by twanariens** [comment]
You are correct. The limitations are from office365. Meaning you are sending too many e-mails in a window of 30 minutes. To be blunt, this is not an Ombi issue but a problem with your E-Mail provider setting those limitations.

**Comment by Firetop** [comment]
> You are correct. The limitations are from office365. Meaning you are sending too many e-mails in a window of 30 minutes. To be blunt, this is not an Ombi issue but a problem with your E-Mail provider setting those limitations.

To be blunt; as I mentioned this was not the original issue; so once I get to test it a bit more I'll advise if the Alias issue is resolved.

As I mentioned I cannot test any faster due to Exchange policies.
Thanks..

**Comment by Firetop** [comment]
> You are correct. The limitations are from office365. Meaning you are sending too many e-mails in a window of 30 minutes. To be blunt, this is not an Ombi issue but a problem with your E-Mail provider setting those limitations.

Also I just changed my number of users and the amount of test emails I sent and it never broke 30 emails a minute. I only have 13 users. I only select a few of them. So probably half was to get an email.. No way it could of broken 30 emails a minute unless it's doing something funky in the background.

Thanks.

**Comment by Firetop** [comment]
> You are correct. The limitations are from office365. Meaning you are sending too many e-mails in a window of 30 minutes. To be blunt, this is not an Ombi issue but a problem with your E-Mail provider setting those limitations.

Just tried to send a single email and it also didn't go through with the same error,

So not sure what the restriction is when using Ombi but Microsoft hates it.

**Comment by Firetop** [comment]
Waited over 10 hours; updated to 4.15.3 and tested again.

First email went through; second never made it... Below are the settings I select before sending:

![image](https://user-images.githubusercontent.com/1971404/160046325-7a9f3fcd-53da-40a8-ade9-fe7abfbab80b.png)

I am not even sending to more than 4 people and somehow connections limits are exceeded now which was not a problem before lol; I could send them as much as I wanted while testing so something did change but I'm not sure it's for the better...


```
2022-03-24 22:55:55.628 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:56:41.934 -04:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2022-03-24 22:56:41.971 -04:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2022-03-24 22:56:41.974 -04:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2022-03-24 22:56:41.975 -04:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2022-03-24 22:56:41.976 -04:00 [Information] RAMJobStore initialized.
2022-03-24 22:56:41.977 -04:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2022-03-24 22:56:41.977 -04:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2022-03-24 22:56:41.977 -04:00 [Information] Quartz scheduler version: 3.1.0.0
2022-03-24 22:56:41.978 -04:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2022-03-24 22:56:42.018 -04:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-03-24 22:56:42.022 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:57:06.068 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:57:33.009 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:58:02.284 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:58:29.450 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:58:57.094 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:59:22.106 -04:00 [Debug] Batch acquisition of 0 triggers
2022-03-24 22:59:26.866 -04:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
2022-03-24 22:59:27.160 -04:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
2022-03-24 22:59:27.180 -04:00 [Error] Exception when attempting to send an email
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
2022-03-24 22:59:27.362 -04:00 [Error] Something bad happened, ErrorMiddleware caught this
MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 112
   at Ombi.Core.Senders.MassEmailSender.DelayEmail(NotificationMessage msg, EmailNotificationSettings email) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MassEmailSender.cs:line 155
   at Ombi.Core.Senders.MassEmailSender.SendMassEmail(MassEmailModel model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MassEmailSender.cs:line 78
   at Ombi.Controllers.V1.NotificationsController.SendMassEmail(MassEmailModel model) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/NotificationsController.cs:line 52
   at lambda_method2131(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2022-03-24 22:59:46.828 -04:00 [Debug] Batch acquisition of 1 triggers
2022-03-24 23:00:00.011 -04:00 [Debug] Batch acquisition of 0 triggers
```

As for the issue at hand for the Alias; I can confirm that appears to be resolved for me using MassEmail functions.

Had to wait forever to be able to test successfully; and once I could the email for me has my Alias and my test account had the test account Alias. Sadly while we fixed one we broke another; we may need to open a separate issue or that though.

Thanks
Joel S.

**Comment by sephrat** [comment]
Please stay on topic. As other people said, your issue is related to your email provider and not Ombi. Let's not hijack OP's thread.
Also, this issue is specific to issues comment notifications where the alias variable is incorrectly filled with the admin's alias instead of the user's alias. MassEmail is not impacted.

**Comment by Firetop** [comment]
> Please stay on topic. As other people said, your issue is related to your email provider and not Ombi. Let's not hijack OP's thread. Also, this issue is specific to issues comment notifications where the alias variable is incorrectly filled with the admin's alias instead of the user's alias. MassEmail is not impacted.

I agree. Let's not hijack the thread. As that last response as completely unrequired my last response clearly states my issue is resolved with Alias and that another issue would need to be opened for my specific mail provider issue.

If you have anything else actually value to contribute or test; let us know.
