### ISSUE TITLE
Windows MySQL migration: Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists

### ISSUE THREAD

**Issue by masterzxz** [Ombi-app/Ombi#4433]
**Describe the bug**
After migrating the Sqlite databases to MySQL on Windows, Ombi fails to start with the following error message:

`Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'applicationconfiguration' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 126
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 450
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 93
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Ombi.Store.Context.MySql.SettingsMySqlContext..ctor(DbContextOptions`1 options) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Context/MySql/SettingsMySqlContext.cs:line 13
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 74
   at Ombi.Program.<Main>(String[] args)`

**To Reproduce**
Steps to reproduce the behavior (commands used to migrate):
`C:\OMBI>python ombi_sqlite2mysql.py -c C:\OMBI --only_db_json --host 127.0.0.1 --db ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\OMBI\database.json)... [✓]

C:\OMBI>ombi --migrate
Hello, welcome to Ombi
Valid options are:
Ombi 4.7.7
Copyright (C) 2021 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
               URL prefixes to which the server should respond. For example,
               http://localhost:123. Use "localhost" to indicate that the server
               should listen for requests on any IP address or hostname using
               the specified port and protocol (for example,
               http://localhost:5000). The protocol (http:// or https://) must
               be included with each URL. Supported formats vary between
               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit
               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.

Migrate in progress...
Migrate complete.

C:\OMBI>python ombi_sqlite2mysql.py -c C:\OMBI --force --host 127.0.0.1 --db ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\OMBI\database.json)... [✓]

MySQL > Connecting... [✓]
Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 4023/4023
- SettingsDatabase  [############################################################] 33/33
- ExternalDatabase  [############################################################] 12848/12848

Start clean tables:
- [CLEAN ] -> __efmigrationshistory -> rows: 15

- Running   [############################################################] 1/1
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 16917/16917
- Running   [############################################################] 16809/16809
- [!!] -> __efmigrationshistory -> [SQLite (0) / MySQL (53)] = -53
- [!!] -> applicationconfiguration -> [SQLite (0) / MySQL (4)] = -4
- [!!] -> aspnetroles -> [SQLite (0) / MySQL (12)] = -12
- [!!] -> aspnetuserroles -> [SQLite (0) / MySQL (88)] = -88
- [!!] -> aspnetusers -> [SQLite (0) / MySQL (29)] = -29
- [!!] -> audit -> [SQLite (0) / MySQL (86)] = -86
- [!!] -> childrequests -> [SQLite (0) / MySQL (17)] = -17
- [!!] -> couchpotatocache -> [SQLite (0) / MySQL (29)] = -29
- [!!] -> episoderequests -> [SQLite (0) / MySQL (1999)] = -1999
- [!!] -> globalsettings -> [SQLite (0) / MySQL (17)] = -17
- [!!] -> issuecategory -> [SQLite (0) / MySQL (6)] = -6
- [!!] -> issuecomments -> [SQLite (0) / MySQL (3)] = -3
- [!!] -> issues -> [SQLite (0) / MySQL (7)] = -7
- [!!] -> mobiledevices -> [SQLite (0) / MySQL (2)] = -2
- [!!] -> movierequests -> [SQLite (0) / MySQL (88)] = -88
- [!!] -> notificationtemplates -> [SQLite (0) / MySQL (119)] = -119
- [!!] -> notificationuserid -> [SQLite (0) / MySQL (5)] = -5
- [!!] -> plexepisode -> [SQLite (0) / MySQL (2305)] = -2305
- [!!] -> plexseasonscontent -> [SQLite (0) / MySQL (128)] = -128
- [!!] -> plexservercontent -> [SQLite (0) / MySQL (66)] = -66
- [!!] -> radarrcache -> [SQLite (0) / MySQL (1680)] = -1680
- [!!] -> requestlog -> [SQLite (0) / MySQL (1149)] = -1149
- [!!] -> requestqueue -> [SQLite (0) / MySQL (2)] = -2
- [!!] -> seasonrequests -> [SQLite (0) / MySQL (81)] = -81
- [!!] -> sickragecache -> [SQLite (0) / MySQL (54)] = -54
- [!!] -> sonarrcache -> [SQLite (0) / MySQL (185)] = -185
- [!!] -> sonarrepisodecache -> [SQLite (0) / MySQL (8369)] = -8369
- [!!] -> tvrequests -> [SQLite (0) / MySQL (17)] = -17
- [!!] -> usernotificationpreferences -> [SQLite (0) / MySQL (185)] = -185
- [!!] -> userqualityprofiles -> [SQLite (0) / MySQL (24)] = -24
- Checking  [############################################################] 46/46

MySQL > Disconnecting... [✓]`

**Expected behavior**
I expect Ombi to start (obviously).

**Screenshots**

**Logs (Logs directory where Ombi is located)**
No log output in log directory.

**Desktop (please complete the following information):**
 - OS: Windows Server 2019

**Ombi Version (please complete the following information):**
- Version: 4.7.7
- Media Server: Plex
- Database Type: SQLite

**Additional context**
MySQL version: 8.0.27.1
Commands used to create the database:
`CREATE DATABASE IF NOT EXISTS `Ombi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE USER 'ombi'@'%' IDENTIFIED BY 'ombi';
GRANT ALL PRIVILEGES ON `Ombi`.* TO 'ombi'@'%' WITH GRANT OPTION;`

**Comment by masterzxz** [comment]
Referring to [https://github.com/vsc55/ombi_sqlite_mysql/issues/18](url), I tried the same commands with a MariaDB 10 database server. This still results in the same error.

**Comment by tidusjar** [comment]
Did you follow the guide on the docs site?

**Comment by masterzxz** [comment]
> Did you follow the guide on the docs site?

Yes. Hence why I included the entire output.

**Comment by masterzxz** [comment]
Fixed with the latest release from the migration script, as mentioned in https://github.com/vsc55/ombi_sqlite_mysql/issues/18#issuecomment-997238668.
