### ISSUE TITLE
Changing Plex username for admin user breaks search, details and requests for that user

### ISSUE THREAD

**Issue by hucknz** [Ombi-app/Ombi#4479]
**Describe the bug**
When the Plex username for an admin user is changed the user is unable to return search results, view details, or request new titles in Ombi.

This hasn't been tested with a non-admin user so unsure if it also affects them.

**To Reproduce**

1. Login to Ombi using Plex SSO
2. Navigate to the details for a title, details should be viewable
3. Login to Plex
4. Change Plex username
5. Open Ombi (re-login if required)
6. Run Plex importer to update user
7. Attempt to search or view details for a title
8. Logout of Ombi
9. Re-login to Ombi
10. Bug still occurs

**Expected behavior**
 Ombi should be able to handle username changes.

**Screenshots**
None

**Logs (Logs directory where Ombi is located)**
```
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
      System.ArgumentNullException: Value cannot be null. (Parameter 'user')
         at Microsoft.AspNetCore.Identity.UserManager`1.IsInRoleAsync(TUser user, String role)
         at Ombi.Core.Engine.Interfaces.BaseEngine.IsInRole(String roleName) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Engine/Interfaces/BaseEngine.cs:line 48
         at Ombi.Core.Engine.BaseMediaEngine.HideFromOtherUsers() in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Engine/BaseMediaEngine.cs:line 149
         at Ombi.Core.Engine.MovieRequestEngine.GetRequests(Int32 count, Int32 position, String sortProperty, String sortOrder) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Engine/MovieRequestEngine.cs:line 231
         at Ombi.Controllers.V2.RequestsController.GetRequests(Int32 count, Int32 position, String sort, String sortOrder) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V2/RequestsController.cs:line 48
         at lambda_method2159(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
         at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
```

**Desktop (please complete the following information):**
 - OS: LSIO Docker build v4.10.2-ls113 (tested back to v4.3.3-ls110)

**Ombi Version (please complete the following information):**

- Version 4.10.2 (tested back to v4.3.3)
- Media Plex
- Database Type: MySQL (also affects SQLite)

**Additional context**
None

**Comment by tidusjar** [comment]
So after you have changed the username. What happens if you log out and then back in?

**Comment by hucknz** [comment]
I had noted that in the steps to reproduce that if you log out and log back in it still errors out. The profile (top right of screen) shows blank and the profile details still show the old username, even though the user list has the new username. 

What I hadn't considered, and your question just prompted me to look at, was the SSO token. If I completely remove the active tokens from Organizr then log in again Ombi does accept the new username so it seems like it's less a bug and more a gotcha with SSO. 

I guess it'd be a good note for the docs instead. I have no idea to contribute but happy to give it a crack if you can point me in the right direction. Otherwise I'll close the ticket.

**Comment by tidusjar** [comment]
Yeah I'd welcome any updates to the docs! https://github.com/Ombi-app/Ombi.Docs
