### ISSUE TITLE
Bad API to Sonarr

### ISSUE THREAD

**Issue by refrivera** [Ombi-app/Ombi#4499]
Ombi is sending a bad API call to Sonarr for the root folder. Ombi detects the root folder correctly, but errors out when sending a TV series to it.

**Comment by tidusjar** [comment]
Logs?

please fill in the template because I have no idea what version you are running etc.

**Comment by refrivera** [comment]
I think this is the template you are referring to...

**Describe the bug
A clear and concise description of what the bug is.**
- 
When requesting a TV series, Ombi give the error "Something went wrong"

To Reproduce
Steps to reproduce the behavior:
- 
Request a TV series


Expected behavior
All Fonts and Pictures must be part of the local OMBI resources.
- 
Expected behavior is to have Ombi send the request to Sonarr


Desktop (please complete the following information):

OS: Docker
Ombi Version (please complete the following information):

Version 4.10.2
Media Server Plex
Database Type: Unknown

Logs:
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
fail: Ombi.Core.Senders.TvSender[0]
      Exception thrown when sending a movie to DVR app, added to the request queue
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
         at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
fail: Ombi.Core.Senders.TvSender[0]
      Exception thrown when sending a movie to DVR app, added to the request queue
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
         at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
fail: Ombi.Core.Senders.TvSender[0]
      Exception thrown when sending a movie to DVR app, added to the request queue
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
         at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.22.55:8989/sonarr/api/series/
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
fail: Ombi.Core.Senders.TvSender[0]
      Exception thrown when sending a movie to DVR app, added to the request queue
      System.Exception: Invalid Path,Invalid Path
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 284
         at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60

**Comment by tidusjar** [comment]
Ok it seems that Ombi and sonarr has mismatching paths. This is usually when you reinstall sonarr and don’t reset up Ombi with sonarr or you change the sonarr root folders. 

What I’d recommend is to reset the root folders in the sonarr settings in Ombi. 

Also check under user management, if the user has any sonarr root folders set and possibly remove it and try again?

**Comment by refrivera** [comment]
Looks like Ombi lost the folders for each user. Once I set them up again, I'm back in action! Thanks!
