### ISSUE TITLE
Can't connect to radarr using latest ombi version

### ISSUE THREAD

**Issue by sellersmd** [Ombi-app/Ombi#4545]
**Describe the bug**
I am unable to connect to radarr using the latest version of Ombi. I have connected previously, none of my radarr settings (api, ip, base url, etc.) have changed, and nearly identical setup with sonarr connects fine. I can access radarr fine via https://mydomain.com/radarr. After entering my IP, port, API, and base url, the options to test connection and submit are still greyed out. If I manually click all the options on the right (quality profiles, root folders, minimum availability), the Test Connection and Submit boxes are activated, but the test fails every time.

**To Reproduce**
1. Go to Settings > Movie > Radarr
2. Click Enable3. 
3. Enter ip, port, API key, base url, etc.4. 
4. Click 'Test Connectivity' (but it is greyed out) 

**Expected behavior**
Ombi should test the connection to radarr, show available root folders and quality profiles, etc.

**Logs (Logs directory where Ombi is located)**
After attempting to test the radarr connection several times:
`2022-03-12 20:32:22.272 -06:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394
2022-03-12 20:32:22.942 -06:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394
2022-03-12 20:32:23.421 -06:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394
2022-03-12 20:32:23.745 -06:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394
2022-03-12 20:32:23.924 -06:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394
2022-03-12 20:32:24.090 -06:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394
`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Ombi Version: 4.14.4
 - Radarr Version: 4.0.5.5981
- Media Server: Plex
- Database Type: SQLite 

**Additional context**

**Comment by sellersmd** [comment]
A clean install of ombi fixed the issue. closing.
