### ISSUE TITLE
OMBI cannot connect to RADARR

### ISSUE THREAD

**Issue by JReich2609** [Ombi-app/Ombi#4586]
**Describe the bug**
Recently updated the OMBI software to the latest developer release of 4.16.5 to try and resolve this issue was on 4.06 (I think) prior to the update. When attempting to connect to the API on Radarr it returns with a **cannot connect** error. However I know the API into Radarr is working fine as other applications are utilizing it. Sonarr also works without any issue.

**To Reproduce**
1. Go to settings, movies, radarr
2. Enter in the normal connection information and API key (I even refreshed key just in case)
3. When attempting to load profile an error **check your values occurs**.
4. Eventually, it returns with cannot contact Radarr. I have tried with v3 toggled on/off looking for an alternative outcome.

**Expected behavior**
Connectivity to Radarr to complete successfully.

**Screenshots**
![ErrorOMBI_02](https://user-images.githubusercontent.com/16614934/162550914-0147ea75-0722-4f11-8de9-b5ec587b8a65.png)
![ErrorOMBI_01](https://user-images.githubusercontent.com/16614934/162550915-afc87ccf-5569-4023-bdb5-fbdfc8b8ac00.png)

**Logs (Logs directory where Ombi is located)**
`2022-04-08 18:03:31.471 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:32.359 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:32.844 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:33.333 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:33.560 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:33.743 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:33.960 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:03:34.179 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:15:00.076 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://10.0.0.11:7878/api/v3/movie
2022-04-08 18:15:00.092 -07:00 [Error] Failed caching queued items from Radarr
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Radarr.RadarrV3Api.GetMovies(String apiKey, String baseUrl) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Radarr/RadarrV3Api.cs:line 55
   at Ombi.Schedule.Jobs.Radarr.RadarrSync.Process(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Radarr/RadarrSync.cs:line 69
2022-04-08 18:16:47.764 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 382
2022-04-08 18:16:52.083 -07:00 [Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.External.TesterController.Radarr(RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 394`

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 - 10.0.14393

**Ombi Version (please complete the following information):**
 - Version 4.16.5
- Media Server is PLEX
- Database Type: SQLite 

**Additional context**
N/A

**Comment by sephrat** [comment]
What's your Radarr version?

**Comment by JReich2609** [comment]
4.0.5.5981

On Apr 8, 2022 10:53 PM, sephrat ***@***.***> wrote:

What's your Radarr version?

**Comment by tidusjar** [comment]
Your screenshots are from Ombi v3. You sure you are running the latest Ombi version

**Comment by JReich2609** [comment]
[cid:7b23c96e-ca25-42e1-8f5e-11bc2aa28e8f]

________________________________

**Comment by JReich2609** [comment]
![ErrorOMBI_03](https://user-images.githubusercontent.com/16614934/162587061-0b3eccdb-1170-4a92-97f4-d140888937a1.png)

**Comment by tidusjar** [comment]
Can you refresh your browsers cache?
It looks like v3 ombi, unless you have custom CSS?

**Comment by JReich2609** [comment]
Interesting. You are correct I went ahead and loaded it in an Incognito window. Unfortunately, I am receiving these same exact errors as I was before the cache clearing. See screenshot.

![OMBIv4error](https://user-images.githubusercontent.com/16614934/162587861-8b639968-7a06-46d3-8ca4-8a720eb84f27.jpg)

**Comment by JReich2609** [comment]
Cancel that! Just notice the API key was incorrect after cache clear updated key and everything appears to be good. Thanks again!
