### ISSUE TITLE
[Error] Exception thrown when attempting to check if something is available

### ISSUE THREAD

**Issue by vsc55** [Ombi-app/Ombi#4587]
**Describe the bug**
Errors are recorded in the log file, although it seems that they do not affect the normal functioning of the web.

**Logs (Logs directory where Ombi is located)**
```
[Error] Exception thrown when attempting to check if something is available
System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at MySqlConnector.MySqlDataReader.GetString(Int32 ordinal) in /_/src/MySqlConnector/MySqlDataReader.cs:line 283
   at lambda_method2944(Closure , DbDataReader , Int32[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadObject(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Ombi.Core.Rule.Rules.Search.AvailabilityRuleHelper.SingleEpisodeCheck(Boolean useImdb, IQueryable`1 allEpisodes, EpisodeRequests episode, SeasonRequests season, IMediaServerContent item, Boolean useTheMovieDb, Boolean useTvDb, ILogger log) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Rule/Rules/Search/AvailabilityRuleHelper.cs:line 86
```

**Desktop (please complete the following information):**
 - OS: Docker

**Ombi Version (please complete the following information):**
 - Version 4.16.5
- Media Server 1.25.9.5721
- Database Type: Docker mariadb:10.6

**Comment by tidusjar** [comment]
What’s the collation on your Key column in the PlexServerContent table?

**Comment by vsc55** [comment]
![imagen](https://user-images.githubusercontent.com/13438676/162586514-39ca7e12-4380-4dc0-9c66-88a18416ca32.png)
I have checked the Key column and they are all numbers, there are no letters or any blank records.
Can this table be regenerated by giving it a full resync with plex?

**Comment by tidusjar** [comment]
For some reason the collation on that column is different. What’s the default collation for the table and database?

**Comment by vsc55** [comment]
![imagen](https://user-images.githubusercontent.com/13438676/162586783-0d86ad26-6b49-4ff2-b8ff-4896b6816527.png)

**Comment by tidusjar** [comment]
That’s odd. I’ll take a look at the migration code to see if I can do anything here. But everything should be utf8mb4_bin. That’s the problem

**Comment by vsc55** [comment]
Ok, it seems that the problem has been solved.
I have modified all the tables and now no errors are logged.
Thank you very much @tidusjar.
