### ISSUE TITLE
Artist not monitored in Lidarr when requeststed in Ombi

### ISSUE THREAD

**Issue by mad-tunes** [Ombi-app/Ombi#4608]
**Describe the bug**
When requesting music through Ombi, artist isn't set to monitored in lidarr so it never searches.

**To Reproduce**
1. Create a request for an album/artist that aren't already in Lidarr (Briteny Spears ...Baby one more time, as an example)
2. Check Lidarr
Artist (Britney Spears) has been added but is not monitored, album (…Baby One More Time) is Monitored
3. Lidarr will never search for it, as the artist isn't monitored

**Expected behavior**
1. Create a request for an album/artist that aren't already in Lidarr (Briteny Spears One more time, as an example-NOT in my collection!)
2. Check Lidarr
Artist (Britney Spears) should be both added and monitored, album (One More Time) should be monitored

**Screenshots**

**Logs (Logs directory where Ombi is located)**
I don't see anything telling added to either Ombi or Lidarrs logs
Can't see how to increase logging level in ombi though-pls do let me know if this is possible and I'll check again.

**Desktop (please complete the following information):**
Windows Server 2022 (20348.643), both Ombi and Lidarr on the same machine

**Ombi Version (please complete the following information):**
Ombi 4.16.10
Lidarr 0.8.1.2135
Database Type: SQLite

**Comment by warlordattack** [comment]
same problem here :

-search "bobby mcferrin" in music
-click first result : diplays all albums
-click albums
-click request selected
-check docker log for OMBI container and Lidarr container

![2022-12-19_151137](https://user-images.githubusercontent.com/3226486/208448294-9413e760-a163-4270-86dc-552ebd4df785.png)
![2022-12-19_151517](https://user-images.githubusercontent.com/3226486/208448296-3f9b4282-0441-48ab-9608-08fd35784fa4.png)
![2022-12-19_152340](https://user-images.githubusercontent.com/3226486/208448297-7035f031-39be-4b93-b85f-755a4d32c275.png)
![2022-12-19_152502](https://user-images.githubusercontent.com/3226486/208448298-3bd330ea-dc2f-4ed0-90ec-3ea1b4cc7f04.png)
![2022-12-19_152738](https://user-images.githubusercontent.com/3226486/208448299-ad00a076-87b9-4d7f-826a-0a72bf069728.png)
![2022-12-19_153105](https://user-images.githubusercontent.com/3226486/208448841-eaaaf2b7-6ba9-4e2b-bdfd-4295e77ecb8a.png)


logs on Ombi side : 
```
12/19/2022 3:20:17 PM
fail: Ombi.ErrorHandlingMiddleware[0]
12/19/2022 3:20:17 PM
      Something bad happened, ErrorMiddleware caught this
12/19/2022 3:20:17 PM
      System.Net.Http.HttpRequestException: Name or service not known (ia601700.us.archive.org:80)
12/19/2022 3:20:17 PM
       ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
12/19/2022 3:20:17 PM
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
12/19/2022 3:20:17 PM
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         --- End of inner exception stack trace ---
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
12/19/2022 3:20:17 PM
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
12/19/2022 3:20:17 PM
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
12/19/2022 3:20:17 PM
         at Ombi.Api.Api.Request(Request request, CancellationToken token) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 139
12/19/2022 3:20:17 PM
         at Ombi.Api.MusicBrainz.MusicBrainzApi.GetCoverArtForReleaseGroup(String musicBrainzId, CancellationToken token) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.MusicBrainz/MusicBrainzApi.cs:line 67
12/19/2022 3:20:17 PM
         at Ombi.Core.Engine.V2.MusicSearchEngineV2.GetReleaseGroupArt(String musicBrainzId, CancellationToken token) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs:line 124
12/19/2022 3:20:17 PM
         at Ombi.Controllers.V2.SearchController.GetReleaseGroupARt(String musicBrainzId) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V2/SearchController.cs:line 464
12/19/2022 3:20:17 PM
         at lambda_method6188(Closure , Object )
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
12/19/2022 3:20:17 PM
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
12/19/2022 3:20:17 PM
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
12/19/2022 3:20:17 PM
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
12/19/2022 3:20:17 PM
         at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
12/19/2022 3:20:17 PM
         at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
12/19/2022 3:20:49 PM
fail: Ombi.Api.Api[1000]
12/19/2022 3:20:49 PM
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://glu:8686/api/v1/artist
12/19/2022 3:20:49 PM
warn: Ombi.Core.Engine.MusicRequestEngine[0]
12/19/2022 3:20:49 PM
      Tried auto sending album but failed. Message: Album is already monitored
12/19/2022 3:20:49 PM
warn: Ombi.Core.Engine.MusicRequestEngine[0]
12/19/2022 3:20:49 PM
      Tried auto sending Album but failed. Message: Album is already monitored
12/19/2022 3:21:32 PM
fail: Ombi.Api.Api[1000]
12/19/2022 3:21:32 PM
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://glu:8686/api/v1/artist
12/19/2022 3:21:32 PM
warn: Ombi.Core.Engine.MusicRequestEngine[0]
12/19/2022 3:21:32 PM
      Tried auto sending album but failed. Message: Album is already monitored
12/19/2022 3:21:32 PM
warn: Ombi.Core.Engine.MusicRequestEngine[0]
12/19/2022 3:21:32 PM
      Tried auto sending Album but failed. Message: Album is already monitored
12/19/2022 3:25:04 PM
warn: Ombi.Core.Engine.MovieRequestEngine[0]
12/19/2022 3:25:04 PM
      Tried auto sending movie but failed. Message: Movie is already monitored
12/19/2022 3:25:04 PM
warn: Ombi.Core.Engine.MovieRequestEngine[0]
12/19/2022 3:25:04 PM
      Tried auto sending movie but failed. Message: Movie is already monitored
```

Logs on Lidarr side : 
```

12/19/2022 2:56:36 PM
[Error] Lidarr.Api.V1.Artist.ArtistController.AddArtist (Lidarr.Api.V1): {
12/19/2022 2:56:36 PM
  "$.status": {
12/19/2022 2:56:36 PM
    "errors": [
12/19/2022 2:56:36 PM
      {
12/19/2022 2:56:36 PM
        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Music.ArtistStatusType. Path: $.status | LineNumber: 0 | BytePositionInLine: 14."
12/19/2022 2:56:36 PM
      }
12/19/2022 2:56:36 PM
    ],
12/19/2022 2:56:36 PM
    "validationState": "invalid",
12/19/2022 2:56:36 PM
    "isContainerNode": false
12/19/2022 2:56:36 PM
  }
12/19/2022 2:56:36 PM
} 
12/19/2022 3:01:25 PM
[Error] Lidarr.Api.V1.Artist.ArtistController.AddArtist (Lidarr.Api.V1): {
12/19/2022 3:01:25 PM
  "$.status": {
12/19/2022 3:01:25 PM
    "errors": [
12/19/2022 3:01:25 PM
      {
12/19/2022 3:01:25 PM
        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Music.ArtistStatusType. Path: $.status | LineNumber: 0 | BytePositionInLine: 14."
12/19/2022 3:01:25 PM
      }
12/19/2022 3:01:25 PM
    ],
12/19/2022 3:01:25 PM
    "validationState": "invalid",
12/19/2022 3:01:25 PM
    "isContainerNode": false
12/19/2022 3:01:25 PM
  }
12/19/2022 3:01:25 PM
} 
12/19/2022 3:20:49 PM
[Error] Lidarr.Api.V1.Artist.ArtistController.AddArtist (Lidarr.Api.V1): {
12/19/2022 3:20:49 PM
  "$.status": {
12/19/2022 3:20:49 PM
    "errors": [
12/19/2022 3:20:49 PM
      {
12/19/2022 3:20:49 PM
        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Music.ArtistStatusType. Path: $.status | LineNumber: 0 | BytePositionInLine: 14."
12/19/2022 3:20:49 PM
      }
12/19/2022 3:20:49 PM
    ],
12/19/2022 3:20:49 PM
    "validationState": "invalid",
12/19/2022 3:20:49 PM
    "isContainerNode": false
12/19/2022 3:20:49 PM
  }
12/19/2022 3:20:49 PM
} 
12/19/2022 3:21:32 PM
[Error] Lidarr.Api.V1.Artist.ArtistController.AddArtist (Lidarr.Api.V1): {
12/19/2022 3:21:32 PM
  "$.status": {
12/19/2022 3:21:32 PM
    "errors": [
12/19/2022 3:21:32 PM
      {
12/19/2022 3:21:32 PM
        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Music.ArtistStatusType. Path: $.status | LineNumber: 0 | BytePositionInLine: 14."
12/19/2022 3:21:32 PM
      }
12/19/2022 3:21:32 PM
    ],
12/19/2022 3:21:32 PM
    "validationState": "invalid",
12/19/2022 3:21:32 PM
    "isContainerNode": false
12/19/2022 3:21:32 PM
  }
12/19/2022 3:21:32 PM
} 

```

**Comment by Grygon** [comment]
Replaying the API, I found that this line is what changes the behavior. If I add the addOptions.monitor = 6 data, it adds w/o monitoring. If I remove it, it adds as expected.
https://github.com/Ombi-app/Ombi/blob/48111827bdf9230639eda77c1747d1dc0bce7b3b/src/Ombi.Core/Senders/MusicSender.cs#L103
