### ISSUE TITLE
Ombi won't start: Failed to create CoreCLR, HRESULT: 0x80070008

### ISSUE THREAD

**Issue by sbrudenell** [Ombi-app/Ombi#4672]
**Describe the bug**
After an upgrade to 4.16.12, ombi won't start up.

I get only the following message at the console:
```
Failed to create CoreCLR, HRESULT: 0x80070008
```

**To Reproduce**
* Happens every time at startup

**Expected behavior**
Should start up.

**Logs (Logs directory where Ombi is located)**
No logs are produced.

**Desktop (please complete the following information):**
 - OS: [linuxserver/ombi:1a9e265877ba](https://quay.io/repository/linuxserver.io/ombi/manifest/sha256:1a9e265877ba76221ee6d0b7c23f70be57801a0f17d9dffba0b4fc4a6ea490d6) on x86_64

**Ombi Version (please complete the following information):**
- Version: 4.16.12
- Media Server: plex
- Database Type: SQLite

**Additional context**
This was working fine until my latest docker image pull. I'm not sure what version I was using previously. I've only used stable releases (the `:latest` tag, not `:development` tag)

I assume this must have something to do with my local state. Please let me know what I can do to debug.

**Comment by tidusjar** [comment]
Please include the full log

**Comment by sbrudenell** [comment]
I did :(

Running the service manually in the container, using its typical setup environment:

```
root@e3e1debc635d:/# s6-setuidgid abc /opt/ombi/Ombi --storage /config/ --host http://*:3579
Failed to create CoreCLR, HRESULT: 0x80070008
root@e3e1debc635d:/# 
```

I have some logs from the previous version in `<storage>/Logs/log-*.txt`. They all look like this.
```
2022-06-10 23:00:04.093 -07:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "..."
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges() in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 96
   at Ombi.Store.Repository.BaseRepository`2.AddRange(IEnumerable`1 content, Boolean save) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 54
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 280
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 155
```

Under suspicion that my `OmbiExternal.db` was corrupt, I renamed it, but I still can't get ombi to start.

**Comment by tidusjar** [comment]
It's a container issue: https://docs.linuxserver.io/faq#jammy

See here
https://github.com/linuxserver/docker-ombi/issues/92

**Comment by sbrudenell** [comment]
Thanks, great find!
