### ISSUE TITLE
Ombi unable to sync with Plex (MySQL) - Stuck on "Processing Request"

### ISSUE THREAD

**Issue by Lucane** [Ombi-app/Ombi#4674]
**Describe the bug**
For some reason Ombi is unable to sync with Plex to update TV shows. Tried a manual full sync as well, but it's throwing errors.
Though some TV shows sync fine and movies don't seem to be affected at all. Full log file attached.

**To Reproduce**
1. Go to 'Ombi > Settings > Media Server > Plex'
2. Click on 'Manually Run Full Sync'
3. Throws the following error:
```
2022-06-13 02:58:55.696 +03:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "[redacted]"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`ombi`.`plexepisode`, CONSTRAINT `FK_PlexEpisode_PlexServerContent_GrandparentKey` FOREIGN KEY (`GrandparentKey`) REFERENCES `plexservercontent` (`Key`))
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 910
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 107
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 450
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 313
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 305
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges() in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 94
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 66
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 475
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 241
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 155
```

**Expected behavior**
Expected behaviour is for Ombi to sync with Plex to update TV show listings.
Currently I have many TV shows that are stuck on "Processing Request" even though they've finished airing and are fully available. See attached screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/7999446/173259927-f731708f-a2a5-4cb0-ac5a-65195348d3a5.png)

**Logs (Logs directory where Ombi is located)**
[log-20220613 - Copy.txt](https://github.com/Ombi-app/Ombi/files/8887085/log-20220613.-.Copy.txt)

**Desktop**
 - OS: Windows 10 Pro x64 19044.1706

**Ombi Version**
 - Version: 4.20.3 (previously used 4.9.0 and experienced the same issue)
- Media Server: Plex
- Database Type: MySQL

**Comment by tidusjar** [comment]
Looks like your database has gone into an odd shape, try a clear data and resync

**Comment by Lucane** [comment]
> Looks like your database has gone into an odd shape, try a clear data and resync

Hey, that seemed to work and the exceptions are gone too. Not sure why I didn't notice that command before. Thank you!
