### ISSUE TITLE
Gmail Mass Email Not Supported

### ISSUE THREAD

**Issue by Firetop** [Ombi-app/Ombi#4689]
**Describe the bug**
Gmail no longer supports "less secure apps" since May 30th and due to this no longer works with Ombi.
https://support.google.com/accounts/answer/6010255?hl=en
Mass email does not work with Microsoft accounts either (which still supports unsecure apps) I can only send 2 emails at a time. Anymore fails.

**To Reproduce**
Attempt to Send a Mass Email or a regular email using Gmail. Will fail.
Attempt to Send a Mass Email to More than 2 users with Microsoft Account. Will Fail.

**Expected behavior**
For the mass emails to go through to each user. Using Gmail or Hotmail/live/Outlook. None work.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/S48szAPu

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.1826

**Ombi Version (please complete the following information):**
 - Version 4.21.1
- Media Server [e.g. Plex]
- Database Type: SQLite

**Additional context**

**Comment by Firetop** [comment]
I was hoping a solution to make Ombi work on a fresh Gmail account with less secure app disabled; or some kind of queuing method for the spam filtering around Microsoft's 2 emails limit. But if you say there is no way to implement backoff's you would know more; but any ideas on the Gmail front?

**Comment by Firetop** [comment]
> Not sure what the solution is here...
> 
> FYI Gmail still works for me.
> 
> Regarding mass email, that provider you are using has a email concurrency limit.
> 
> > 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=BL0PR02MB6499.namprd02.prod.outlook.com]
> 
> This is usually to prevent any sort of 'mass spam'. That's also outside of my control. There could be things like backoff's that I could implement, but again there are spam control measures in place to prevent that sort of use.

this is the log with Gmail:

```
2022-07-20 10:19:10.340 -04:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2022-07-20 10:19:10.381 -04:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2022-07-20 10:19:10.382 -04:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2022-07-20 10:19:10.383 -04:00 [Information] RAMJobStore initialized.
2022-07-20 10:19:10.384 -04:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2022-07-20 10:19:10.385 -04:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2022-07-20 10:19:10.385 -04:00 [Information] Quartz scheduler version: 3.1.0.0
2022-07-20 10:19:10.385 -04:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2022-07-20 10:19:10.429 -04:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-07-20 10:19:35.840 -04:00 [Error] Exception when attempting to send an email
MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials t23-20020a37ea17000000b006b5840f3eefsm15708195qkj.130 - gsmtp
 ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials t23-20020a37ea17000000b006b5840f3eefsm15708195qkj.130 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 109
2022-07-20 10:19:35.842 -04:00 [Warning] Exception when testing Email Notifications
MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials t23-20020a37ea17000000b006b5840f3eefsm15708195qkj.130 - gsmtp
 ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials t23-20020a37ea17000000b006b5840f3eefsm15708195qkj.130 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 109
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 300
```

**Comment by Firetop** [comment]
And Yes; I validated "copy and pasted" the password and username are correct. 
It worked before; I didn't change anything until it stopped working.

**Comment by tidusjar** [comment]
I still can add and create App Passwords on my google account. 

Other than that is for me to setup some sort of Google OAuth authentication to access the email, but I'm sure that's going to mean a lot of setup on the users end (you) to create a new google app etc

**Comment by Firetop** [comment]
> I still can add and create App Passwords on my google account.
> 
> Other than that is for me to setup some sort of Google OAuth authentication to access the email, but I'm sure that's going to mean a lot of setup on the users end (you) to create a new google app etc

So if I'm understanding correctly; the ideal solution is to enable 2FA, and then create an app password specific to Ombi?
I currently do not have the option to create an app password in Gmail 2FA is a requirement for App passwords.

If that the ideal solution I rather do that then move back to Microsoft myself.

**Comment by Firetop** [comment]
> I still can add and create App Passwords on my google account.
> 
> Other than that is for me to setup some sort of Google OAuth authentication to access the email, but I'm sure that's going to mean a lot of setup on the users end (you) to create a new google app etc

I tried to enable 2FA and app passwords and it worked perfectly.
I also noticed the Wiki was updated a month ago with Known Issues: https://docs.ombi.app/settings/notifications/email/#common-mail-settings

That is my bad; this is case closed. I had not reviewed that page again since the first time I had setup mail.
