### ISSUE TITLE
Odd MySQL and Watchlist errors in logs

### ISSUE THREAD

**Issue by Firetop** [Ombi-app/Ombi#4726]
**Describe the bug**
Odd MySQL and watchlist errors in logs

**To Reproduce**
Unknown when this started. However I did recently migrate to MySQL if it makes a difference.

**Expected behavior**
No Errors and for watchlist to function even after my Plex user (Not local user) signs out and back in.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
2022-08-09 15:21:13.674 -04:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2022-08-09 15:21:13.713 -04:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2022-08-09 15:21:13.715 -04:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2022-08-09 15:21:13.716 -04:00 [Information] RAMJobStore initialized.
2022-08-09 15:21:13.717 -04:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2022-08-09 15:21:13.717 -04:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2022-08-09 15:21:13.717 -04:00 [Information] Quartz scheduler version: 3.1.0.0
2022-08-09 15:21:13.718 -04:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2022-08-09 15:21:13.760 -04:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.

2022-08-09 15:21:25.431 -04:00 [Warning] Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.
2022-08-09 15:21:35.405 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://metadata.provider.plex.tv/library/sections/watchlist/all
2022-08-09 15:21:35.551 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://metadata.provider.plex.tv/library/sections/watchlist/all
2022-08-09 15:21:35.693 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://metadata.provider.plex.tv/library/sections/watchlist/all
2022-08-09 15:21:35.843 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://metadata.provider.plex.tv/library/sections/watchlist/all
2022-08-09 15:21:36.711 -04:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://metadata.provider.plex.tv/library/sections/watchlist/all
2022-08-09 15:21:46.634 -04:00 [Warning] The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
2022-08-09 15:30:00.047 -04:00 [Error] An exception occurred while iterating over the results of a query for context type '"Ombi.Store.Context.MySql.SettingsMySqlContext"'."
""System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()"
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 (19044.165)

**Ombi Version (please complete the following information):**
 - Version 4.23.0 Dev Branch
- Media Server Plex Version: 1.28.0.5999
- Database Type: MySQL

**Additional context**

**Comment by Firetop** [comment]
Any assistance or input would be appreciated on this one :)

**Comment by tidusjar** [comment]
So the error looks to be transient and nothing to worry about, what's your issue with the Plex watchlist? 

Can you please update the original post to include what's the actual problem with that?

**Comment by Firetop** [comment]
> So the error looks to be transient and nothing to worry about, what's your issue with the Plex watchlist?
> 
> Can you please update the original post to include what's the actual problem with that?

Hey there!

Thanks for the quick reply! As long as the errors are not impacting I am happy for now.

I did not poke at Plex Watchlist much at the moment which is why the bug report above is so bare on that part.
I'll close this for now and if I find an issue I'll be sure to open a new more specific issue in relation to that :)

Thanks again for the feedback. 
I may have just gotten caught off guard by the last update/migration to MySQL and didn't notice those logs before.

Joel S.
