### ISSUE TITLE
Cannot add movies to Radarr from Ombi

### ISSUE THREAD

**Issue by tm9k1** [Ombi-app/Ombi#4750]
**Describe the bug**
Cannot add movies to Radarr from Ombi

**To Reproduce**
1. Request a movie (auto-approval enabled)
2. See error in notification - (movie could not be added, will keep retrying)

**Expected behavior**
Movie gets added in radarr as TV shows in sonarr (yes, Sonarr connection works perfectly fine for me with v3 switch enabled)

**Logs (Logs directory where Ombi is located)**
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://sonarr:8989/api/v3/movie
fail: Ombi.Core.Senders.MovieSender[0]
      Error when sending movie to DVR app, added to the request queue
      Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Radarr.Models.MovieResponse]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
      To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
      Path 'message', line 2, position 12.
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
         at Ombi.Api.Radarr.RadarrV3Api.GetMovies(String apiKey, String baseUrl) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Radarr/RadarrV3Api.cs:line 55
         at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, Boolean is4K, RadarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 170
         at Ombi.Core.Senders.MovieSender.Send(MovieRequests model, Boolean is4K) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 70
```

**Desktop (please complete the following information):**
 - OS: Rapberry Pi4 with Ubuntu 22.04
 - 

**Ombi Version (please complete the following information):**
 - Version 4.22.5
- Media Server : Jellyfin
- Database Type: SQLite 
 
**Additional context**
- Sonarr version: 3.0.9.1549-ls154 by [linuxserver.io](https://linuxserver.io/) (working)
- Radarr version: 4.1.0.6175-ls150 by [linuxserver.io](https://linuxserver.io/)

**Comment by tidusjar** [comment]
What’s in the radarr log? Looks like they are sending an error message back

**Comment by Baltimorepc** [comment]
i have been having this issue for about a month or 2 now. Anye ideas how to fix it
