### ISSUE TITLE
Login breaks if user uses old email with password reset link

### ISSUE THREAD

**Issue by almulder** [Ombi-app/Ombi#4759]
**Describe the bug**
User lost password again, and instead of generating a new email, they reused there old email like for lost password. they tried to update password and it said check email once they hit save. No email ever arrived

Now I try to log in as add admin and its just sits there and does nothing.

**To Reproduce**
user1 lost password, used forgot password to get email, used email to link to reset password, they logged in, realized they had am in privilege's, they logged out. I changed user1 to requesting movies/tv and saved. they then tried to log in again, password not working, they used their old email from password reset from before, tried to reset, says check email. they never get email. I try to now log in as the admin and it just sits there and does nothing. restarted docker, same issue

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
**_Log at startup:_**
```
2022-09-16 10:19:09.126 -06:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2022-09-16 10:19:09.166 -06:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2022-09-16 10:19:09.168 -06:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2022-09-16 10:19:09.169 -06:00 [Information] RAMJobStore initialized.
2022-09-16 10:19:09.171 -06:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.
```

**_Log after trying to sign in_**
```
2022-09-16 10:19:09.171 -06:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2022-09-16 10:19:09.171 -06:00 [Information] Quartz scheduler version: 3.1.0.0
2022-09-16 10:19:09.171 -06:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2022-09-16 10:19:09.223 -06:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-09-16 10:19:50.504 -06:00 [Error] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: Sequence contains more than one element.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Ombi.Controllers.V1.TokenController.DoesUserRequireAPassword(UserAuthModel model) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/TokenController.cs:line 251
   at lambda_method806(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
```

**Desktop (please complete the following information):**
 - OS: Unraid 6.10.3

**Ombi Version (please complete the following information):**
Version 4.25.1
Media Server: Plex Version 4.87.2
Database Type: SQLite)

**Additional context**

**Comment by tidusjar** [comment]
Can you please send your Ombi.db to tidusjar@gmail.com

**Comment by almulder** [comment]
sent referencing this case. Also just luckily I saved it as I just nuked the docker. since I was unable to do anything.
