### ISSUE TITLE
Unable to get past plex connection errors - Unsure what to do or where to go to resolve it.

### ISSUE THREAD

**Issue by andsoitgoes** [Ombi-app/Ombi#4765]
**Describe the bug**
Unable to connect to my plex server, load libraries, etc.

**To Reproduce**
1. Go to ombi --> Settings
2. Click on Media server
3. Scroll down to plex configuration
4. Constant and a multitude of errors

**Expected behavior**
A straightforward connection to Plex

**Screenshots**
Logs below

**Logs (Logs directory where Ombi is located)**
```
2022-10-01T21:57:18.469983432Z fail: Ombi.ErrorHandlingMiddleware[0]
2022-10-01T21:57:18.470105206Z       Something bad happened, ErrorMiddleware caught this
2022-10-01T21:57:18.470128261Z       Octokit.RateLimitExceededException: API rate limit exceeded for XXXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-10-01T21:57:18.470146761Z          at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 634
2022-10-01T21:57:18.470164260Z          at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 615
2022-10-01T21:57:18.470182538Z          at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 600
2022-10-01T21:57:18.470200445Z          at Octokit.Internal.ReadOnlyPagedCollection`1.GetNextPage() in C:\projects\octokit-net\Octokit\Http\ReadOnlyPagedCollection.cs:line 38
2022-10-01T21:57:18.470218129Z          at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri)
2022-10-01T21:57:18.470234388Z          at Ombi.Schedule.Processor.ChangeLogProcessor.GetGitubRelease(Release release, Task`1 settingsTask) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Processor/ChangeLogProcessor.cs:line 69
2022-10-01T21:57:18.470251517Z          at Ombi.Schedule.Processor.ChangeLogProcessor.Process() in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Processor/ChangeLogProcessor.cs:line 36
2022-10-01T21:57:18.470268091Z          at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
2022-10-01T21:57:18.470335607Z          at Ombi.Helpers.CacheService.GetOrAddAsync[T](String cacheKey, Func`1 factory, DateTimeOffset absoluteExpiration) in /home/runner/work/Ombi/Ombi/src/Ombi.Helpers/CacheService.cs:line 24
2022-10-01T21:57:18.470357051Z          at Ombi.Controllers.V1.UpdateController.UpdateAvailable() in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/UpdateController.cs:line 27
2022-10-01T21:57:18.470374699Z          at lambda_method1225(Closure , Object )
2022-10-01T21:57:18.470395032Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2022-10-01T21:57:18.470412920Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2022-10-01T21:57:18.470430549Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-10-01T21:57:18.470470641Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2022-10-01T21:57:18.470487473Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-10-01T21:57:18.470504491Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-10-01T21:57:18.470522102Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-10-01T21:57:18.470540139Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2022-10-01T21:57:18.470556157Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-10-01T21:57:18.470572804Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-10-01T21:57:18.470590285Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-10-01T21:57:18.470607007Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-10-01T21:57:18.470625988Z          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-10-01T21:57:18.470644247Z          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2022-10-01T21:57:18.470696671Z          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2022-10-01T21:57:18.470715671Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2022-10-01T21:57:18.470731578Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2022-10-01T21:57:18.470747392Z          at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
2022-10-01T21:57:18.470763595Z          at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
2022-10-01T21:57:18.470781983Z       {"message":"API rate limit exceeded for XXXXXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
2022-10-01T21:57:18.470800039Z       
2022-10-01T22:01:40.556325708Z warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
2022-10-01T22:01:40.556438335Z       Exception thrown when attempting to cache the Plex Content in server plex-desktop
2022-10-01T22:01:40.556458241Z       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2022-10-01T22:01:40.556475778Z        ---> System.TimeoutException: A task was canceled.
2022-10-01T22:01:40.556492481Z        ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
2022-10-01T22:01:40.556509184Z          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2022-10-01T22:01:40.556526999Z          at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-10-01T22:01:40.556543776Z          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2022-10-01T22:01:40.556560887Z          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-10-01T22:01:40.556577516Z          at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2022-10-01T22:01:40.556593904Z          at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2022-10-01T22:01:40.556610182Z          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2022-10-01T22:01:40.556627681Z          --- End of inner exception stack trace ---
2022-10-01T22:01:40.556643384Z          --- End of inner exception stack trace ---
2022-10-01T22:01:40.556693383Z          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
2022-10-01T22:01:40.556715290Z          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2022-10-01T22:01:40.556733956Z          at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 40
2022-10-01T22:01:40.556750641Z          at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 122
2022-10-01T22:01:40.556766788Z          at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 698
2022-10-01T22:01:40.556783362Z          at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 173
2022-10-01T22:01:40.556800250Z          at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 151
```

also:

```
2022-10-01 15:09:07.596 -07:00 [Error] Caching Episodes Failed
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 122
   at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.Cache(PlexServers settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 83
   at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 55
```

**Desktop (please complete the following information):**
 - OS: Raspbian - Docker

**Ombi Version (please complete the following information):**
 - Version4.22.5
- Media Server Plex
- Database Type: Unknown

**Additional context**
This wasn't an issue previously that I was aware of, I've done everything appropriately according to the docs, and yet still there's errors.  The Octokit.RateLimitExceededException error showed ZERO results past 2016.

I have 2fa with Plex and I've appended the code to the password which allowed me to log in, but I can't load libraries (error) or get much else to work.

I have no clue what else to try here.

**Comment by JoshuaGarrison27** [comment]
I am also having a similar issue with confirming my Plex setup.

I will try to be as detailed as I can...

## The issue:

My instance is running in Kubernetes (k3s to be precise). I have set up the connection to plex exactly how I did for other things so I know my method should work.

Upon putting in all the values I need for my plex instance, I try to run a test...

![image](https://user-images.githubusercontent.com/1706923/201491015-86a1983e-adc2-4097-a49d-f9f9eae2cbc6.png)

Upon submitting and then testing the connection, here are the logs....

```log
fail: Ombi.Api.Api[1000]
      StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://10.5.0.21:32400/library/sections
warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception thrown when attempting to cache the Plex Content in server UNSC Spirit Of Fire
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
         at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 123
         at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 698
         at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 173
         at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 155
fail: Ombi.Api.Api[1000]
      StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://10.5.0.21:32400/library/sections
fail: Ombi.Schedule.Jobs.Plex.PlexEpisodeSync[2000]
      Caching Episodes Failed
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
         at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 123
         at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.Cache(PlexServers settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 83
         at Ombi.Schedule.Jobs.Plex.PlexEpisodeSync.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs:line 55
fail: Ombi.Api.Api[1000]
      StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: https://10.5.0.21:32400/
fail: Ombi.Controllers.V1.External.TesterController[1000]
      Could not test Plex
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
         at Ombi.Api.Plex.PlexApi.GetStatus(String authToken, String uri) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 99
         at Ombi.Controllers.V1.External.TesterController.Plex(PlexServers settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 326
```

## My thoughts on the issue:

Interesting things to consider:
- Im 95% sure that I have configured everything properly.
- sqlite database
- I was still able to import all of my users even though the test connectivity failed.
- From the UI, you get the `Unexpected character encountered while parsing value: <. Path '', line 0, position 0.` error.
- Checking Web Tools in Firefox, I see a call to `POST | https://subdomain.example.com/api/v1/tester/plex`

My best guess is that there is an issue with the API call and it cannot properly process the results (or lack there of).

**Comment by tidusjar** [comment]
The first error which seems to be causing more is that we cannot load the Plex libraries. Do you have any libraries in your Plex instance?

**Comment by JoshuaGarrison27** [comment]
I have two active plex instances right now. Both have libraries. The instance in question has 4 libraries. Here is a screenshot...

![image](https://user-images.githubusercontent.com/1706923/201491892-f78b5daf-a86a-4bae-9a6b-72c1b3457257.png)

**Comment by tidusjar** [comment]
What happens if there’s only one instance in ombi with that server?

**Comment by JoshuaGarrison27** [comment]
Sorry, I should have been more clear. My fault. I am only setting up one instance of plex inside of Ombi in this example.

**Comment by andsoitgoes** [comment]
So just as an update I've got my side all working now, I'll just remove notifications but can someone close this once Joshua's issue is resolved?

**Comment by JoshuaGarrison27** [comment]
Mine is a kubernetes storage issue I think. So @tidusjar (or whomever) if you want to close this issue, i can open a new issue if needed.
