### ISSUE TITLE
Ombi.Store.Context.MySql.SettingsMySqlContext triggered by Radarr sync

### ISSUE THREAD

**Issue by sephrat** [Ombi-app/Ombi#4766]
**Describe the bug**
Radarr sync systematically fails with an error.
Changing the cron settings in hope of solving a lock issue doesn't help.

**To Reproduce**
Save Radarr settings without changing anything.

**Logs (Logs directory where Ombi is located)**
```
2022-10-03 01:16:00.013 +02:00 [Error] An exception occurred while iterating over the results of a query for context type '"Ombi.Store.Context.MySql.SettingsMySqlContext"'."
""System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()"
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

**Ombi Version (please complete the following information):**
- Database Type: Maria DB

**Additional context**
This seems to be caused by the following instructions:
https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi.Schedule/Jobs/Radarr/RadarrSync.cs#L52-L53
The 2nd GetSettingsAsync triggers the exception. I suppose this method doesn't allow 2 concurrent calls despite it being a read-only operation.

**Comment by tidusjar** [comment]
Should be fixed in develop as part of https://github.com/Ombi-app/Ombi/commit/de4baade9f87248d77106ff1a313a498870f4fb3
