### ISSUE TITLE
Exception when refreshing the Metadata Refresh

### ISSUE THREAD

**Issue by squeaky369** [Ombi-app/Ombi#4783]
**Describe the bug**
Ombi server was working fine until today. Requests would be completed and added to Plex, they'd show up on Plex, but not showing as available in Ombi. Went on the server and tested the connection and attempted to do a full resync and received the following error:

```
2022-10-23 17:55:30.142 -04:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.1.252:32400/library/metadata/24932
2022-10-23 17:55:30.142 -04:00 [Error] Exception when refreshing the Metadata Refresh
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetMetadata(String authToken, String plexFullHost, String itemId) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 162
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartPlexMovies(List`1 allMovies, PlexSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 293
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartPlex(PlexSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 124
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 82
```

**To Reproduce**
1. Go to Settings
2. Click on Media Server
3. Scroll down to Plex
4. Click on 'Manually Run Full Sync'

**Expected behavior**
A sync runs!

**Logs (Logs directory where Ombi is located)**
See above error

**Desktop (please complete the following information):**
 - OS: Docker

**Ombi Version (please complete the following information):**
 - Version - 4.22.5
- Media Server - Plex 1.29.1.6316 
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Restarted the Ombi Server and the Plex server. Restarted Docker completely. Removed the Plex server and re-added it, used the Plex login method to get the account / server information (which matched what it was before). 

No other changes since the server was setup and installed.

**Comment by JackTorrance1** [comment]
I have the same error but on Jellyfin.

**Comment by sephrat** [comment]
Are you sure you're using the correct IP? If you're running Docker, you can't use a local IP address because of how Docker networking works.
See https://docs.ombi.app/info/common-errors/#docker-issues and Docker documentation.
