### ISSUE TITLE
Unable to use .cloud domains in Application URL

### ISSUE THREAD

**Issue by ZeroFux78** [Ombi-app/Ombi#4807]
**Describe the bug**
When completing the Application URL, Ombi says the URL is not valid. It will accept ombi.domain.cloud:3443, but per [Issue #3677](https://github.com/Ombi-app/Ombi/issues/3677), the port should not be used.  (My AT&T Fiber blocks 443, so I have a port forward for 3443 to 443 for external requests) 

**To Reproduce**
1. Go to Configuration
2. Click on Customization
3. Scroll down to Application URL
4. Enter in a ombi.<anything>.cloud domain
5. Click Submit
6. See error **The URL "ombi.domain.cloud" is not valid. Please format it correctly e.g. http://www.google.com/**

**Expected behavior**
Ombi should accept the .cloud domain so that I can use it. This also affects being able to set up email notifications (see log error message below)

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
2022-11-19 17:56:55.213 +00:00 [Warning] Exception when testing Email Notifications
System.ArgumentException: The domain is invalid. (Parameter 'domain')
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 47
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 300
```

**Desktop (please complete the following information):**
 - OS: 18.04 LTS

**Ombi Version (please complete the following information):**
 - Version [4.0.991.0]
- Media Server [Plex]
- Database Type: SQLite 

**Additional context**

**Comment by sephrat** [comment]
I could not reproduce. I typed `https://ombi.domain.cloud:3443` in the application URL and hit submit, it saved successfully. 
Ran a test email, it was sent successfully.
Triggered a real email, the link in the email is correct.

Are you still facing the issue?
