### ISSUE TITLE
Newsletter Not Sending / Triggering

### ISSUE THREAD

**Issue by bombz88** [Ombi-app/Ombi#4824]
**Describe the bug**
Newsletter no longer triggering
> Test newsletter operational
> Request emails operational
> Manual newsletter trigger from OMBI GUI operational

**To Reproduce**
1. None - Cron job is operational

**Expected behavior**
Newsletter to trigger and send to ombi users

**Screenshots**

**Logs (Logs directory where Ombi is located)**
```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Ombi.Store.Context.MySql.SettingsMySqlContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Ombi.Store.Context.MySql.SettingsMySqlContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Ombi.Store.Context.MySql.SettingsMySqlContext'.
      System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
```

**Desktop (please complete the following information):**
Docker
Linux 5.19.14-Unraid #1 SMP PREEMPT_DYNAMIC Thu Oct 6 09:15:00 PDT 2022
lscr.io/linuxserver/ombi:development

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.33.0]
- Media Server [Plex
- Database Type: mariadb

**Additional context**
Please let me know if you require further logs
[log20221203.txt](https://github.com/Ombi-app/Ombi/files/10149255/log20221203.txt)

**Comment by scottcase** [comment]
Don't feel alone.  For me the newsletter sending has not worked in months.

Last time I had any issue with the newsletter,  I reconfigured OMBI to use a mysql database and everything worked fine for about a month,  then it stopped working again and it has been about 5 months since the newsletter has sent anything from my install.

**Comment by davexre** [comment]
Seem to have same issue.

**Comment by scottcase** [comment]
I have resolved my issue by completely unlinking my plex server then link it again and did a full sync and now it is sending the newsletter correctly for me.

**Comment by sephrat** [comment]
Please hit the "Clear Data And Resync" button from your media server settings and test again. 
Get back to us if you're still facing the issue with your logs.
