### ISSUE TITLE
Ombi does not sync with Plex anymore

### ISSUE THREAD

**Issue by sfreek76** [Ombi-app/Ombi#4828]
**Describe the bug**
All of a sudden Ombi does not show new movies or tv-shows as available

**To Reproduce**
1. Go to Settings / Plex
2. Click on Manually run full sync

**Expected behavior**
Now all new movies and TV-Shows should show up after a while but they don't.

**Screenshots**
![plex new additions](https://user-images.githubusercontent.com/110930155/207847235-a7a44d7f-0ca6-4d63-ad90-e6cb3651f498.png)
![ombi search](https://user-images.githubusercontent.com/110930155/207847243-4b417d10-f8fb-4a42-abb7-2ef663a7cb76.png)

**Logs (Logs directory where Ombi is located)**
[ombi log.pdf](https://github.com/Ombi-app/Ombi/files/10236481/ombi.log.pdf)

**Desktop:**
 - OS: MacOS Monterey, Ombi runs as a package (not docker) on Synology NAS DSM 7.1.1-42962 Update 2

**Ombi Version:**
 - Version 4.22.5
- Media Server Plex 1.30.1.6483
- Database Type: SQLite

**Comment by tidusjar** [comment]
Run a clear and resync and report back please

**Comment by sfreek76** [comment]
Thanks a lot, seem to work again. How can I prevent this issue in the future and what could be the cause? Do I have to do a "clear and resync" regularely?

**Comment by sfreek76** [comment]
OK; have to do a "clear and resync" every time I add a movie or TV-Show to Plex, otherwise it won't show up in ombi. Connection to Plex is fine although... What to do about it?

**Comment by tidusjar** [comment]
It seems that looking at your logs there's duplicate keys in your Plex library. Is it possible to refresh the metadata in Plex?

**Comment by sfreek76** [comment]
I've never done that before because I'm scared to loose all my matches I did by hand and they were a lot... Wouldn't I loose them too if I do a complete refresh of metadata?

**Comment by tidusjar** [comment]
Refreshing the metadata doesn't do anything with Matches, all it just does is refresh the metadata e.g. IMDB information and ID's

**Comment by sfreek76** [comment]
OK, thanks for the clarification. Sorry for asking but I never did a refresh of metadata in Plex, do I have to do a "Scan Library Files" under "Librarys" or is there  another way to force refresh of metadata? I've seen there's a setting in "Scheduled Tasks" to refresh metadata every 3 days, this is ticket off in my settings... Thanks!

**Comment by sfreek76** [comment]
So i've managed to refresh metadata on all libraries that I want to have represented in ombi. Is there something I should do next?

**Comment by tidusjar** [comment]
Do a clean and resync a last time. If still no success upload a new set of logs

**Comment by sfreek76** [comment]
Will do, thanks! Would it be a good idea to tick "refresh metadata every 3 days" in Settings / library?

**Comment by sfreek76** [comment]
Situation gets worse, As implied in last post I got massive DB errors all of a sudden! Did not do or change anything. What can I do? Thanks!
[ombi-log2.pdf](https://github.com/Ombi-app/Ombi/files/10304714/ombi-log2.pdf)

**Comment by tidusjar** [comment]
Apologies. I’m on vacation with limited signal so not able to look at the
moment

**Comment by sfreek76** [comment]
oh, OK, enjoy your vacation! Glad if you could take a look into this after you are back! Thanks!

**Comment by sfreek76** [comment]
Hope you had fine vacations and wish you all the best for new year!

Did you had a chance to take a look? I've managed to reschedule Plex Sync but from time to time I get SQLite Error 19 regarding Plex Server Content Key and I don't know why because it runs for days without problem then all of a sunnden the error occurs although nothing changed. You can see error in Log at the top: 

[ombi-log3.pdf](https://github.com/Ombi-app/Ombi/files/10417035/ombi-log3.pdf)

Thanks for any advice!

**Comment by sfreek76** [comment]
Would be grateful for any help here, issue happened again today...

**Comment by sfreek76** [comment]
Hello? Anyone? I still have the issue, in the meantime I tried to reconnect the server to see if it works then but getting cryptic URL (https://app.plex.tv/web/app#!/server//details?key=myKey%2flibrary%2Fmetadata%2F53334). I think the last part with the metadata is wrong? would be great if someone could help, thanks a lot in advance!

**Comment by twanariens** [comment]
The issue lies in your OmbiExternal.db. Stop Ombi, delete OmbiExternal.db, start Ombi and wait for 5 minutes. This should let Ombi recreate your OmbiExternal.db and the issue should no longer be there anymore

**Comment by sfreek76** [comment]
OK, did that, thanks! Let's hope the issue is resolved now. I'll keep you posted...

**Comment by sfreek76** [comment]
Error re-apeared today:

  2023-02-08 08:19:00.250 +01:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "myPlexServer"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges() in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 96
   at Ombi.Store.Repository.BaseRepository`2.Delete(T request) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 66
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessTvShow(PlexServers servers, Metadata show, HashSet`1 contentToAdd, Dictionary`2 contentProcessed) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 475
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 241
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 155

**Comment by tidusjar** [comment]
Out of curiosity, not sure how running as a package works, but can you edit the `appsettings.json` file and change the log levels to `Debug`. Once you have done that restart Ombi and do a normal sync and then upload the logs again? 

It's easier if you upload the logs to something like pastebin rather than PDF's.

After that remember to put the log levels back in the appsettings.json

**Comment by sfreek76** [comment]
Thanks for your reply. How do I do that since I have a Synology packet installed?

Still get the error after a while: 

Exception thrown when attempting to cache the Plex Content in server "myServer"
SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'
