### ISSUE TITLE
Plex user unauthorized to login

### ISSUE THREAD

**Issue by brodonalds** [Ombi-app/Ombi#4838]
**Describe the bug**
Attempted to login as the admin user which is a plex user but get an incorrect password or username error.
**To Reproduce**
1. Go to login page
2. Type Credentials
3. Hit Sign-in

**Expected behavior**
I would expect to be able to login

**Screenshots**
![ombi](https://user-images.githubusercontent.com/17820611/210107243-2334628e-567d-4a36-bc60-4e206e8d7646.png)

**Logs (Logs directory where Ombi is located)**
2022-12-30 20:36:55.256 +01:00 [Warning] Failed login attempt by IP: 50.47.210.42
2022-12-30 20:36:58.136 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json

**Desktop (please complete the following information):**
 - OS: Debian 5.10.106-1

**Ombi Version (please complete the following information):**
 - Version 4.22.5
- Media Server Plex
- Database Type: SQLite 

**Additional context**
Local users are able to login.

**Comment by tidusjar** [comment]
That’s coming back from Plex, we send the information off to the Plex api
and it’s telling Ombi that you don’t have authorisation.

**Comment by brodonalds** [comment]
Just confirmed the login works. Is there a way to force a new token to be issued? I'm also seeing issues in the logs that say 


2022-12-30 23:00:05.469 +01:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://localhost:32400/library/sections
2022-12-30 23:00:05.474 +01:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "walker"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 123
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 698
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 173
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 151



Unsure if related.

**Comment by tidusjar** [comment]
Looks like you sever is also rejecting Ombi. I’d remove the sever in the
settings and re set it up in Ombi

**Comment by brodonalds** [comment]
So for whatever reason, it is able to load the server configs and libraries when i use a token but is unable to complete the auth with plex. I reinstalled, it redirected to plex where it said login successful and the login auth shows in plex but then is rejected by ombi.

**Comment by tidusjar** [comment]
Logs around the time you login?

**Comment by iBigOne** [comment]
So I had similar problem when adding users through Plex and got the same error. Turns out they did not have any Roles.
If they have no Roles they can not log in. 
Turned out I had not setup a default role in Configuration --> User Management 

Check in the User page and make sure they have roles. If not you need to assign for example RequestTv, RequestMovie
