### ISSUE TITLE
Misconfigured cron prevents startup; Quartz.SchedulerException: "Based on configured schedule, the given trigger 'Plex.IPlexContentSyncTrigger' will never fire."

### ISSUE THREAD

**Issue by noctacode** [Ombi-app/Ombi#4842]
**Describe the bug**
Ombi does not finish starting up due to misconfigured cron jobs.

**To Reproduce**
1. Navigate to Scheduled Tasks in Settings to where the cron jobs are listed.
2. Set one of the crons to trigger in a very distant year. I don't know where the threshold is, but the cron that broke my Ombi was 0 0 0 1 * ? 9999.
3. Clicking on button to verify cron will report it as valid.
4. Save settings.
5. Restart Ombi.
6. It is now looping; the startup won't complete.

**Expected behavior**
I'd expect Ombi to be okay with crons that never trigger.
The expected behaviour is for the Ombi to start up without errors.
Such cron configuration could warrant a warning though, but not a looping error.

**Logs**
This is the part of log that keeps looping indefinitely:
```
ombi  | Hello, welcome to Ombi
ombi  | Valid options are:
ombi  | Ombi 4.22.5
ombi  | Copyright (C) 2023 Ombi
ombi  | 
ombi  |   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of
ombi  |                URL prefixes to which the server should respond. For example,
ombi  |                http://localhost:123. Use "localhost" to indicate that the server
ombi  |                should listen for requests on any IP address or hostname using
ombi  |                the specified port and protocol (for example,
ombi  |                http://localhost:5000). The protocol (http:// or https://) must
ombi  |                be included with each URL. Supported formats vary between
ombi  |                servers.
ombi  | 
ombi  |   --storage    Storage path, where we save the logs and database
ombi  | 
ombi  |   --baseurl    The base URL for reverse proxy scenarios
ombi  | 
ombi  |   --demo       Demo mode, you will never need to use this, fuck that fruit
ombi  |                company...
ombi  | 
ombi  |   --migrate    Will run the migrations then exit the application
ombi  | 
ombi  |   --help       Display this help screen.
ombi  | 
ombi  |   --version    Display version information.
ombi  | 
ombi  | 
ombi  | 
ombi  | Wrote new baseurl at /app/ombi/ClientApp/dist/index.html
ombi  | We are running on http://*:3579
ombi  | /app/ombi
ombi  | Unhandled exception. Quartz.SchedulerException: Based on configured schedule, the given trigger 'Plex.IPlexContentSyncTrigger' will never fire.
ombi  |    at Quartz.Core.QuartzScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger, CancellationToken cancellationToken)
ombi  |    at Ombi.Helpers.OmbiQuartz.AddJob[T](String name, String group, String cronExpression, Dictionary`2 jobData) in /home/runner/work/Ombi/Ombi/src/Ombi.Helpers/OmbiQuartz.cs:line 79
ombi  |    at Ombi.Schedule.OmbiScheduler.AddPlex(JobSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/OmbiScheduler.cs:line 89
ombi  |    at Ombi.Schedule.OmbiScheduler.UseQuartz(IServiceProvider app) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/OmbiScheduler.cs:line 53
ombi  |    at Ombi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IServiceProvider serviceProvider) in /home/runner/work/Ombi/Ombi/src/Ombi/Startup.cs:line 126
ombi  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
ombi  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
ombi  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
ombi  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
ombi  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
ombi  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
ombi  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
ombi  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
ombi  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
ombi  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
ombi  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
ombi  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
ombi  |    at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 142
ombi  |    at Ombi.Program.<Main>(String[] args)
```

**Desktop:**
 - OS: Ubuntu 22.04.1 LTS

**Ombi Version:**
- Version 4.22.5
- it's a Docker container
- Database Type: SQLite

**Additional:**
I'm looking for a temporary solution to get my instance working asap.
Can anyone instruct me on how to open and modify the database files to manually edit the crons? (I've been told the crons are in the database.)

Cheers!

**Comment by noctacode** [comment]
**Fix To Get Your Instance Working Again**

0. Stop Ombi
1. Open the OmbiSettings.db (It's an SQLite)
2. Access the GlobalSettings table and modify the Content at the correct id (id was 8 in my case)
3. Start Ombi

Here's the database query to do it:
```sql
UPDATE GlobalSettings
SET Content = '{"EmbyContentSync":"0 0 0 1 * ? 2050","EmbyRecentlyAddedSync":"0 0 0 1 * ? 2050","JellyfinContentSync":"0 0/15 * 1/1 * ? *","SonarrSync":"0 0 0 1 * ? 2050","RadarrSync":"0 0 0 1 * ? 2050","PlexContentSync":"0 0 0 1 * ? 2050","PlexRecentlyAddedSync":"0 0 0 1 * ? 2050","CouchPotatoSync":"0 0 0 1 * ? 2050","AutomaticUpdater":"0 0 0/6 1/1 * ? *","UserImporter":"0 0/15 * 1/1 * ? *","SickRageSync":"0 0 0 1 * ? 2050","Newsletter":"0 0 12 ? 1/1 SAT#1 *","LidarrArtistSync":"0 0 0 1 * ? 2050","IssuesPurge":"0 0 0 1/1 * ? *","RetryRequests":"0 0 5 1/1 * ? *","MediaDatabaseRefresh":"0 0 5 1/1 * ? *","AutoDeleteRequests":"0 0 0 1/1 * ? *","PlexWatchlistImport":"0 0 0 1 * ? 2050","Id":8}'
WHERE id = 8
```
 
**A Thanks To ChatGPT**
I have no idea about databases, I just had a conversation with ChatGPT to craft the queries and navigate around the database! Thing is effing brilliant!😄

**Comment by noctacode** [comment]
**Observations and Ideas**
Since crons with year 9999 killed Ombi, but ones with 2050 didn't, I'm betting that both cron verification button and inner workings of Ombi (particularly those that caused a loop at startup) dismiss the first two characters of year part of cron and only evaluate the last two. Reminiscent of the Y2K.

**Comment by noctacode** [comment]
Maybe I can modify the validity check buttons to check for a sane number?
I understand that a thorough fix is much work, but I'm uncomfortable with leaving Ombi so easily breakable.
