### ISSUE TITLE
Plex Sync issues - even after testing/reauthentication

### ISSUE THREAD

**Issue by andsoitgoes** [Ombi-app/Ombi#4861]
**Describe the bug**
Every time Ombi tries to do a plex sync there's errors

**To Reproduce**

1. start ombi
2. wait a few minutes
3. see error
4. Expected behavior
5. Logs show constant errors trying to run Plex Sync

**Expected behavior**
No errors when running plex sync

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
[If applicable, a snippet of the logs that seems relevant to the bug if present.](https://pastebin.com/gYjp5vpQ)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - 
**Ombi Version (please complete the following information):**
 - Version 4.35.6 
- Media Server Plex
- Database Type: SQLite 

**Additional context**
just hoping someone can figure this out for me, thanks!

**Comment by andsoitgoes** [comment]
anyone? :(

**Comment by SickProdigy** [comment]
I'm also having this pop up in logs, not my reason for coming here, but figured I'd share.

```
2023-02-04 00:01:40.028 -05:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "RCS-Server"
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetLibrarySections(String authToken, String plexFullHost) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 122
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.GetAllContent(PlexServers plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 698
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 173
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.StartTheCache(PlexSettings plexSettings, Boolean recentlyAddedSearch) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 151
2023-02-04 00:10:09.217 -05:00 [Error] StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: http://sonarr:8989/api/Episode?seriesId=292
2023-02-04 00:10:09.218 -05:00 [Error] Exception when trying to cache Sonarr
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Sonarr.Models.Episode]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'message', line 2, position 12.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Sonarr.SonarrApi.GetEpisodes(Int32 seriesId, String apiKey, String baseUrl) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Sonarr/SonarrApi.cs:line 127
   at Ombi.Schedule.Jobs.Sonarr.SonarrSync.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Sonarr/SonarrSync.cs:line 117
```
 Like consistently, so I assume it's from a cron.

**Comment by andsoitgoes** [comment]
Man I'm sorry you're having the issue too, but I can't tell you how glad I am that it's not just me. 

Im feeling pretty down about fixing it though. 

Are you the same where a manual sync works just fine?

**Comment by SickProdigy** [comment]
> Man I'm sorry you're having the issue too, but I can't tell you how glad I am that it's not just me.
> 
> Im feeling pretty down about fixing it though.
> 
> Are you the same where a manual sync works just fine?

Yes, when I run a manual sync everything connects. Everything appears to be working fine. Like seeing the movies available on my server vs which are not.

**Comment by andsoitgoes** [comment]
> 

It's a bit frustrating that this is just sitting here with no one able to help us with this issue, I know it's not URGENT, but it's getting really frustrating. I just want the errors gone :(

**Comment by tidusjar** [comment]
Sorry about the lack of replies.

Unfortunately, many personal issues have happened in the past 3 weeks of my life. I have mentioned this on the Ombi discord, but understandably, if you are not on there, you wouldn't be aware.


The logs that have been provided so far indicate there's a connection issue. It seems that when Ombi is attempting to talk to Plex it's taking over 100 seconds to get a response and then timing out.

**Comment by andsoitgoes** [comment]
Thanks for replying! I'm so sorry things have been challenging for you, I can imagine how difficult that must be and I'll make sure to join the discord. 

As for the issues, it's very odd. When I run the sync manually it works fine. I've gone through to entering my plex credentials (along with the 2fa code appended as instructed) and when I manually sync, there are no errors in the log. 

It only happens in the scheduled sync. The devices are on the same network and I've had no issues with anything connecting through to the device it's running on, is there anything else I can do? I can try to upload more logs (I had to redact some info but I didn't want to put the whole thing in). 

Thanks in advance and best wishes to getting everything taken care of, truly.

**Comment by tidusjar** [comment]
Does the same thing happen when you do a clear and resync?

**Comment by jermflix** [comment]
> Does the same thing happen when you do a clear and resync?

I'm having very similar issues as OP, and using the option for clear and resync does not work unfortunately. One thing I did check was in the program's folder, I opened OmbiSettings.db and viewed it with a SQL viewer. When I view the global settings, it is showing the wrong IP & port number. Whenever I add the correct server and go to sync my media, it fails, even though the Test connect worked fine. It even is able to retrieve my libraries. However, when I save it, it reverts back to the wrong server information in the database. I tried to manually change the DB to the correct IP and port but then Ombi failed to load completely. One other thing I tried was to delete the "Server 1" that is showing in Ombi as default. However, whenever Ombi is restarted or reloaded, it loads up that deleted "Server 1" with the incorrect information again. I can't speak on whether this is exactly what OP is experiencing, but is what I discovered while I have been trying to figure out what the heck is going on.

**Comment by andsoitgoes** [comment]
> > Does the same thing happen when you do a clear and resync?
> 
> I'm having very similar issues as OP, and using the option for clear and resync does not work unfortunately. One thing I did check was in the program's folder, I opened OmbiSettings.db and viewed it with a SQL viewer. When I view the global settings, it is showing the wrong IP & port number. Whenever I add the correct server and go to sync my media, it fails, even though the Test connect worked fine. It even is able to retrieve my libraries. However, when I save it, it reverts back to the wrong server information in the database. I tried to manually change the DB to the correct IP and port but then Ombi failed to load completely. One other thing I tried was to delete the "Server 1" that is showing in Ombi as default. However, whenever Ombi is restarted or reloaded, it loads up that deleted "Server 1" with the incorrect information again. I can't speak on whether this is exactly what OP is experiencing, but is what I discovered while I have been trying to figure out what the heck is going on.

To confirm I also tried to clear and resync, still happening ALTHOUGH there are no errors.

I was going to attempt switching databases, but this seems much more difficult with Docker, and I have no clue how best to do it.

**Comment by tidusjar** [comment]
@jermflix you seem to have a different issue where the data is not being saved.

**Comment by tidusjar** [comment]
Are you pressing submit and then save?
![image](https://user-images.githubusercontent.com/6642220/218981312-45c0a4e4-8f5d-4444-b150-b3dd795f59fa.png)

**Comment by andsoitgoes** [comment]
Yes I've manually changed and saved it and it still doesn't work sadly.

**Comment by tidusjar** [comment]
Sorry that was for @jermflix as I think we have two different issues in this thread

**Comment by jermflix** [comment]
> Sorry that was for @jermflix as I think we have two different issues in this thread

My apologies, I ended up getting it to work. I can delete my previous reply to prevent confusion if you’d like.

**Comment by andsoitgoes** [comment]
oh good lord - I think that was it, I thought I was hitting submit, I just tried again, went through the whole manual entry and while it kept redoing the old WRONG port, once I hit submit it refreshed the new port. 

I think one of the issues is the fact that there's a "Save" button but THEN you have to submit afterwards. It's now working and boy do I feel like a complete and UTTER idiot. I could have sworn I changed the port. I'm now having database issues, BUT I can work on that. Unless @SickProdigy is still having the same issues? Try manually adjusting the port and making sure to submit it afterwards!
