### ISSUE TITLE
Conole Errors Not Detailing Specific Show/Movie Causing Error Exception Adding to Queue

### ISSUE THREAD

**Issue by gold007eye** [Ombi-app/Ombi#4880]
**Describe the bug**
I keep seeing 'FAIL' errors when the schedule Plex sync runs stating TVDBID is missing, but it doesn't show what show/movie is throwing the error so I can investigate and fix or remove the request as applicable.

Also in the error it also refers to "...when sending a **movie** to DVR app".  This verbiage should be updated to say "...when sending a **show** to the DVR app" as this is error referring to Sonarr.

When I look under the Web GUI under I do see 2 TV shows (JANET JACKSON [tvdbid=414707] & Alone: Frozen [tvdbid=422357]) under Settings --> System --> Failed Requests and can only assume that is what these errors are referring to since it's missing that information.

**To Reproduce**
1. I'm not sure how to reproduce these errors.  Maybe try and add a TV Series that is missing a TVDBID?

**Expected behavior**
To detail in the Console Error window what Show is throwing the error when Sending series over to Sonarr so that the user can investigate and work to clear the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/4365462/224100328-61b9ab15-d39f-44a4-b2de-b9ef77213301.png)

![image](https://user-images.githubusercontent.com/4365462/224101757-176862d3-d43d-4388-ac90-95bfa9926fa0.png)

**Logs (Logs directory where Ombi is located)**
```
2023-03-09 02:00:40.438 -06:00 [WRN] Episode Episode 0 has no episode number. Skipping.
2023-03-09 06:00:05.851 -06:00 [ERR] Exception thrown when attempting to send series over to Sonarr
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 294
2023-03-09 06:00:05.853 -06:00 [ERR] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 294
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
2023-03-09 06:00:06.637 -06:00 [ERR] Exception thrown when attempting to send series over to Sonarr
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 294
2023-03-09 06:00:06.638 -06:00 [ERR] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: TVDBID is missing

   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 294
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
```

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by sephrat** [comment]
Isn't it easier to read the error from the GUI rather than the console?

**Comment by gold007eye** [comment]
Not when Console windows is up.  I would have to be looking at the logs in the GUI/text editor to actually have noticed an issue.  With the console window I see any errors right away.
