### ISSUE TITLE
Odd PlexContentSync error in logs - "The instance of entity type 'PlexServerContent' cannot be tracked because another instance with the same key value for {'Key'} is already being tracked"

### ISSUE THREAD

**Issue by andsoitgoes** [Ombi-app/Ombi#4882]
**Describe the bug**
2023-03-11T20:00:01.114158460Z warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
2023-03-11T20:00:01.137142784Z       Exception thrown when attempting to cache the Plex Content in server plex-desktop

these are showing up regularly in the logs for some unknown reason

**To Reproduce**
1. Go to 'Ombi Logs'
2. Click on 'The logs'
3. Scroll down to 'The logs'
4. error appears

**Expected behavior**

**Screenshots**
none nneeded
**Logs (Logs directory where Ombi is located)**

`2023-03-11T20:00:01.114158460Z warn: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
2023-03-11T20:00:01.137142784Z       Exception thrown when attempting to cache the Plex Content in server plex-desktop
2023-03-11T20:00:01.137288817Z       System.InvalidOperationException: The instance of entity type 'PlexServerContent' cannot be tracked because another instance with the same key value for {'Key'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
2023-03-11T20:00:01.137355816Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
2023-03-11T20:00:01.137374148Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
2023-03-11T20:00:01.137431443Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
`

**Desktop (please complete the following information):**
 - OS: Raspberry Pi

**Ombi Version (please complete the following information):**
 - Version 4.35.8   
- Media Server Plex
- Database Type: SQLite 

**Additional context**
I'm not sure what's happening here, nor am I sure what to do to fix it. Thanks!

**Comment by KoenBoone** [comment]
I have the same problem also
