### ISSUE TITLE
Ombi can not add foreign show to sonarr: TVDBID is missing

### ISSUE THREAD

**Issue by kylaris** [Ombi-app/Ombi#4890]
**Describe the bug**
Trying to add a Korean TV show. Sonarr does not add the show.

**To Reproduce**
1. Request a Korean show

**Expected behavior**
Add the requested show on Sonarr

**Logs (Logs directory where Ombi is located)**
at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 318
2023-03-29 06:00:00.430 +00:00 [ERR] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: TVDBID is missing

at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 318
at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
2023-03-29 06:00:01.046 +00:00 [ERR] Exception thrown when attempting to send series over to Sonarr
System.Exception: TVDBID is missing

**Desktop (please complete the following information):**
 - OS: Synology docker

**Ombi Version (please complete the following information):**
 - Version: 4.35.10
- Media Server: plex
- Database Type: Unknown. using LinuxServer docker image.

**Additional context**
Ombi sends me the e-mail stating that the show could not be added and is added to the requests queue and will retry later.
I've tried with an American TV show and it was added without any problem.

Sonarr is enabled and connected.

Check the requested show @ https://thetvdb.com/ and was able to locate it on the site.

**Comment by sephrat** [comment]
What's the show? Does it have a corresponding TVDB id in TMDB? For example https://www.themoviedb.org/tv/1396-breaking-bad/edit?active_nav_item=external_ids

**Comment by kylaris** [comment]
The show is called The Genius Paik.
https://www.themoviedb.org/tv/219880
https://thetvdb.com/series/430596-series

There were other shows prior to this, that I added to Sonarr manually.

**Comment by sephrat** [comment]
This shows works fine for me today. Its tvdb_id was added to TMDB 3rd April so it's normal that it failed when you posted your issue. 
If if happens again, check the tvdb ID set for the show in TMDB.

**Comment by kylaris** [comment]
I did not know that Ombi uses themoviedb.org. for data.
I will cross-check for the IDs next time. 

Thanks for the help.
