### ISSUE TITLE
Not sure why users (or myself) can't request TV shows

### ISSUE THREAD

**Issue by Kryptide** [Ombi-app/Ombi#4899]
**Describe the bug**
Anytime I or a user tries to request a TV show I get this error. Movie requests work fine.

**To Reproduce**
1. Request a TV Show

**Expected behavior**
The request to be sent to Sonarr as usual.

**Logs (Logs directory where Ombi is located)**
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.184:8989/api/v3/series/
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.184:8989/api/v3/series/
fail: Ombi.Core.Senders.TvSender[5001]
      Exception thrown when attempting to send series over to Sonarr
      System.Exception: Language profile does not exist
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 294
fail: Ombi.Core.Senders.TvSender[0]
      Exception thrown when sending a movie to DVR app, added to the request queue
      System.Exception: Language profile does not exist
         at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 294
         at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 60
fail: Ombi.Notifications.GenericEmailProvider[0]
      Exception when attempting to send email
      MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. Learn more at
      5.7.8  https://support.google.com/mail/?p=BadCredentials r17-20020a92ac11000000b0032867b9427esm3033057ilh.38 - gsmtp
       ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
      5.7.8  https://support.google.com/mail/?p=BadCredentials r17-20020a92ac11000000b0032867b9427esm3033057ilh.38 - gsmtp
         --- End of inner exception stack trace ---
         at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
         at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
         at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 180
fail: Ombi.Notifications.NotificationService[4000]
      Failed to notify for notification: Ombi.Notifications.Agents.EmailNotification
      MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. Learn more at
      5.7.8  https://support.google.com/mail/?p=BadCredentials r17-20020a92ac11000000b0032867b9427esm3033057ilh.38 - gsmtp
       ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
      5.7.8  https://support.google.com/mail/?p=BadCredentials r17-20020a92ac11000000b0032867b9427esm3033057ilh.38 - gsmtp
         --- End of inner exception stack trace ---
         at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
         at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
         at Ombi.Notifications.GenericEmailProvider.Send(MimeMessage message, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 180
         at Ombi.Notifications.GenericEmailProvider.Send(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 148
         at Ombi.Notifications.Agents.EmailNotification.Send(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/Agents/EmailNotification.cs:line 280
         at Ombi.Notifications.Agents.EmailNotification.SendToAdmins(NotificationMessage message, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/Agents/EmailNotification.cs:line 292
         at Ombi.Notifications.Agents.EmailNotification.AddedToRequestQueue(NotificationOptions model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/Agents/EmailNotification.cs:line 183
         at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model, Settings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/BaseNotification.cs:line 113
         at Ombi.Notifications.BaseNotification`1.NotifyAsync(NotificationOptions model) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/BaseNotification.cs:line 62
         at Ombi.Notifications.NotificationService.NotifyAsync(INotification notification, NotificationOptions model) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/NotificationService.cs:line 49
**Desktop (please complete the following information):**
 - OS: Ubuntu64

**Ombi Version (please complete the following information):**
 - Version 4.35.15
- Media Server Plex

**Comment by Kryptide** [comment]
> Go into your sonarr settings and press the test button. It seems you are using the older version of sonarr and haven’t got a language profile.

Awesome! Thank you so much! That fixed it. Updated Sonarr and selected English as the Language Profile and it works!
