### ISSUE TITLE
Middleware could not return default page

### ISSUE THREAD

**Issue by somerandomguy24** [Ombi-app/Ombi#4911]
**Describe the bug**
When trying to access Ombi (on localhost:5000), the following message is shown:
```
{
  "error":"The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.\nYour application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.\n"
}
```

**To Reproduce**
1. Build the Ombi latest beta (4.36.1) (using `dotnet publish` and `yarn build`)
2. Run Ombi
3. Go to `localhost:5000`

**Expected behavior**
Show the default Ombi page.

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
```
2023-04-23 17:51:14.688 +01:00 [INF] Default Quartz.NET properties loaded from embedded resource file
2023-04-23 17:51:14.728 +01:00 [INF] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2023-04-23 17:51:14.728 +01:00 [INF] Quartz Scheduler created
2023-04-23 17:51:14.728 +01:00 [INF] RAMJobStore initialized.
2023-04-23 17:51:14.729 +01:00 [INF] Quartz Scheduler 3.5.0.0 - 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED' initialized
2023-04-23 17:51:14.729 +01:00 [INF] Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10
2023-04-23 17:51:14.729 +01:00 [INF] Using job store 'Quartz.Simpl.RAMJobStore', supports persistence: False, clustered: False
2023-04-23 17:51:14.729 +01:00 [INF] JobFactory set to: Ombi.Schedule.IoCJobFactory
2023-04-23 17:51:14.766 +01:00 [INF] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2023-04-23 17:51:19.749 +01:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass1_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass1_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/alpha/.local/src/aports/testing/ombi/src/Ombi-4.36.1/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 56
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/alpha/.local/src/aports/testing/ombi/src/Ombi-4.36.1/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
2023-04-23 17:51:53.639 +01:00 [INF] Request starting HTTP/1.1 GET http://localhost:5000/ - -
2023-04-23 17:51:53.641 +01:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass1_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass1_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/alpha/.local/src/aports/testing/ombi/src/Ombi-4.36.1/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 56
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/alpha/.local/src/aports/testing/ombi/src/Ombi-4.36.1/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
2023-04-23 17:51:53.642 +01:00 [INF] Request finished HTTP/1.1 GET http://localhost:5000/ - - - 500 - application/json 4.8277ms
2023-04-23 17:52:01.966 +01:00 [INF] Application is shutting down...
```

**Desktop (please complete the following information):**
 - OS: Alpine Linux Edge

**Ombi Version (please complete the following information):**
 - Version 4.36.1
- Media Server N/A
- Database Type: SQLite

**Additional context**
I checked against the distributed zip file provided on github releases, and the archive and the directory Ombi is ran in contains everything in that archive (+ additional directories for languages and more). There is an `index.html` file at `$RUNDIR/ClientApp/dist/index.html`.

**Comment by tidusjar** [comment]
Please read this: https://docs.ombi.app/development/building-ombi/

if you follow this you can build Ombi locally

**Comment by somerandomguy24** [comment]
> Please read this: https://docs.ombi.app/development/building-ombi/
> 
> if you follow this you can build Ombi locally

As mentioned in https://github.com/Ombi-app/Ombi/issues/4897#issuecomment-1519098222, this leads to a segmentation fault.

**Comment by somerandomguy24** [comment]
I solved the issue! Turns out it is because `ClientApp` is expected to be in the directory the user is when Ombi is ran, rather than the directory where the `Ombi` binary is.
