### ISSUE TITLE
Ombi doesn't properly handle a failed request to Sonarr when language is not specified 

### ISSUE THREAD

**Issue by AbeKline** [Ombi-app/Ombi#4925]
Might be a Sonarr bug. Not techy enough to find

**Describe the bug**
For the past few months my users' requests for TV Shows would be recorded in Ombi as successfully submitted but in the Sonarr logs I see 
```
2023-05-09 19:30:16.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- LanguageProfileId: Language profile does not exist
2023-05-09 19:30:17.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- LanguageProfileId: Language profile does not exist
2023-05-09 19:31:19.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- LanguageProfileId: Language profile does not exist
2023-05-09 19:31:19.3|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- LanguageProfileId: Language profile does not exist
```

**To Reproduce**
1. Ensure Sonarr connection doesn't have a language profile selected (even if you Test Connection and it comes through as properly connected)
2. Request any show
3. Fail to see show pop up on Sonarr tracked shows even though it is in Processing Request and incapable of being re requested
3a. See error in Sonarr logs

**Expected behavior**
The show should be added to tracked shows in Sonarr

**Logs**
See above log from Sonarr

**Desktop (please complete the following information):**
 - OS: Unraid Dockers from the App Store

**Ombi Version (please complete the following information):**
 - Ombi Version 4.35.10
- Sonarr Version 3.0.10.1567-ls190
- Database Type: SQLite (I think)

**Comment by tidusjar** [comment]
So the problem here is that your version of Sonarr **requires** a language profile to be present when sending a TV show over. It needs to be filled in in the Ombi settings (Press the test button if it's not there).

There's nothing I can do here other than ensure you have a language profile. In the newer versions of sonarr (beta) they have removed language from the API spec.

**Comment by AbeKline** [comment]
Fair. I just assumed that given that Sonarr kicks back an error and Ombi sees it (see logs below, I did find them), Ombi wouldn't list it as a successfully processed request. 

Ombi log:
```
2023-05-09 19:30:16.562 -05:00 [ERR] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://shirt:8989/api/v3/series/
2023-05-09 19:30:17.030 -05:00 [ERR] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://shirt:8989/api/v3/series/
2023-05-09 19:30:17.145 -05:00 [ERR] Exception thrown when attempting to send series over to Sonarr
System.Exception: Language profile does not exist
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 318
2023-05-09 19:30:17.245 -05:00 [ERR] Exception thrown when sending a movie to DVR app, added to the request queue
System.Exception: Language profile does not exist
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 318
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 138
```
