### ISSUE TITLE
Error when adding movie to DOGnzb watchlist

### ISSUE THREAD

**Issue by cxhamilton** [Ombi-app/Ombi#4967]
I've set up Ombi in a Docker container using LinuxServer.io's fleet and docker-compose. I'm getting an error when Ombi tries to add a movie to DOGnzb's watchlist. 

I've confirmed that the DOGnzb API key is correct and I can see the API count increment on my DOGnzb profile when Ombi makes the request.

Thoughts?

```
stdout
06/19/2023 8:03:39 AM
fail: Ombi.Api.DogNzb.DogNzbApi[0]
stdout
06/19/2023 8:03:39 AM
      Error when adding TV Shows to DogNzb
stdout
06/19/2023 8:03:39 AM
      System.InvalidOperationException: There is an error in XML document (2, 8).
stdout
06/19/2023 8:03:39 AM
       ---> System.InvalidOperationException: <error xmlns=''> was not expected.
stdout
06/19/2023 8:03:39 AM
         at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDogNzbAddResult.Read3_uuid()
stdout
06/19/2023 8:03:39 AM
         --- End of inner exception stack trace ---
stdout
06/19/2023 8:03:39 AM
         at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
stdout
06/19/2023 8:03:39 AM
         at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
stdout
06/19/2023 8:03:39 AM
         at Ombi.Api.DogNzb.DogNzbApi.AddTvShow(String apiKey, String tvdbId) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.DogNzb/DogNzbApi.cs:line 56
```

**Comment by tidusjar** [comment]
DogNzb is not going to be supported going forward. I’m actually going to remove the integration.
