### ISSUE TITLE
Ombi Using 9GB+ RAM

### ISSUE THREAD

**Issue by jktikka** [Ombi-app/Ombi#4988]
### Summary

![image](https://github.com/Ombi-app/Ombi/assets/37353302/2f396a50-2490-491e-847a-13ce3dd8352e)

I have Ombi installed on a Windows 11 PC and noticed Plex was slowing down. Upon inspection, Ombi was using a lot of RAM. I read around and thought it may be SQLLite which I knew had limitations. (I did try updating to 4.43.2 from 4.39.1 but no luck)

So after a successful migration to MySQL on the same PC, I hoped the problem would go away, but it still persists. 

I attach the log file and the MySQL workbench dashboard screenshot 

![image](https://github.com/Ombi-app/Ombi/assets/37353302/0ecb5b94-11b4-4748-82a9-0c3bcf541616)

If I restart the service in nssm, it will quickly reach the same RAM usage, it does fluctuate though, from between 3GB-4GB to 8GB-9GB.

[cleanlog-ombi.txt](https://github.com/Ombi-app/Ombi/files/12140065/cleanlog-ombi.txt)

### Ombi Version

v4.39.1

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2023-07-23 22:03:30.027 +01:00 [INF] Default Quartz.NET properties loaded from embedded resource file
2023-07-23 22:03:30.075 +01:00 [INF] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2023-07-23 22:03:30.075 +01:00 [INF] Quartz Scheduler created
2023-07-23 22:03:30.076 +01:00 [INF] RAMJobStore initialized.
2023-07-23 22:03:30.076 +01:00 [INF] Quartz Scheduler 3.5.0.0 - 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED' initialized
2023-07-23 22:03:30.076 +01:00 [INF] Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10
2023-07-23 22:03:30.076 +01:00 [INF] Using job store 'Quartz.Simpl.RAMJobStore', supports persistence: False, clustered: False
2023-07-23 22:03:30.080 +01:00 [INF] JobFactory set to: Ombi.Schedule.IoCJobFactory
2023-07-23 22:03:30.127 +01:00 [INF] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2023-07-23 22:03:42.015 +01:00 [ERR] An error occurred using the connection to database '' on server '].168.0.213'.
2023-07-23 22:03:48.695 +01:00 [ERR] Something bad happened, ErrorMiddleware caught this
Octokit.RateLimitExceededException: API rate limit exceeded for "MY HOME IP ADDRESS". (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
   at Octokit.ApiConnection.GetPage[TU](Uri uri, IDictionary`2 parameters, String accepts, ApiOptions options) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 628
   at Octokit.ApiConnection.<>c__DisplayClass18_0`1.<<GetAll>b__0>d.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 212
--- End of stack trace from previous location ---
```

**Comment by tidusjar** [comment]
I would have not expected to see this. 

Can you give a bit more information about the memory usage e.g. how long does it take to get to that point, what does it start at, is there a specific time it’s jumping up and not releasing any memory?


I’ve been running mine for 37 days straight and I’m at around 400mb in a docker instance.

**Comment by jktikka** [comment]
I would not either - I've had it running for nearly 2 years rock solid.

I can't attribute it to my recent migration to MySQL either, since the issues were the reason I migrated from SQL Lite.

I timed it, took about 5 minutes to get my RAM to 60%, at which point I've now got a script which kills it and relaunches, as I'm writing this it's back to 4.9GB and about to be killed again. 

The GIF is 5 mins x6 speed, I do move up to the %s after a few secs.

![ombibug](https://github.com/Ombi-app/Ombi/assets/37353302/9c28b3ca-3ffd-4931-aea0-75f65d74cc38)

I can try with a fresh install but ideally I can still use my existing settings as I have a lot of notification customization etc. The library of requests is not important however, I auto delete these. Thanks for any help!

**Comment by tidusjar** [comment]
Can you do a fresh install just to see if it happens?

Don't nuke your existing installation. 

Do you still have your sqlite databases?

**Comment by jktikka** [comment]
Fresh install seems fine. 
I just have these 3 files which are kept when updating:
![image](https://github.com/Ombi-app/Ombi/assets/37353302/3cd2ce7b-aeac-4fb1-886e-cfc1f2550c20)
I guess ombi.db is the SQlite DB.

Is it worth going back to the previous config and deleting one of these files? Or paste in one or more into this working install? Cheers

**Comment by tidusjar** [comment]
Can you send me those 3 .db files to tidusjar@gmail.com so I can see what's going on?
