### ISSUE TITLE
Can't submit Radarr settings. `normalForm` undefined. 

### ISSUE THREAD

**Issue by steezeburger** [Ombi-app/Ombi#4994]
### Summary

`normalForm` is undefined on the Radarr settings page. `Submit` button always greyed out. Can't change settings. Nothing relevant in the logs that I could see.

The first time I set the Radarr settings, I did try testing the connection but never got any feedback, then I clicked submit. So I think I submitted in the middle of a pending request. Did this throw off the app state in a way that causes the `normalForm` value to be undefined on subsequent loads?

https://github.com/Ombi-app/Ombi/blob/500b65ea7e67abb8a184f21de7c0c37ebafe8f3c/src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.ts#L69

<img width="1047" alt="Screenshot 2023-08-02 at 2 39 22 AM" src="https://github.com/Ombi-app/Ombi/assets/5599073/8622350a-21d4-42b2-95d5-c5e93efec046">

### Ombi Version

4.39.1

### What platform(s) does this occur on?

Linux

### What database are you using?

SQLite (Default)

### Relevant log output (browser console)

```shell
main.2f123838503b8dd3.js:11 ERROR TypeError: Cannot read properties of undefined (reading 'changes')
    at Object.next (943.114b5c43c90542ed.js:1:371057)
    at q.next (main.2f123838503b8dd3.js:11:501692)
    at le._next (main.2f123838503b8dd3.js:11:501371)
    at le.next (main.2f123838503b8dd3.js:11:501062)
    at main.2f123838503b8dd3.js:1:285142
    at Ge.runInsideAngular (main.2f123838503b8dd3.js:1:282413)
    at Ge.leave (main.2f123838503b8dd3.js:1:282340)
    at Ge.leave (main.2f123838503b8dd3.js:1:285391)
    at Object.next (main.2f123838503b8dd3.js:1:285129)
    at q.next (main.2f123838503b8dd3.js:11:501692)
```

**Comment by JakeMHughes** [comment]
I also have this issue on version 4.43.8

**Comment by steezeburger** [comment]
@JakeMHughes I unfortunately had to uninstall and reinstall Ombi and was very careful with how I input the Radarr settings, but I was able to get it working.

I actually ran into this issue again recently when setting up a new server. I had to uninstall/reinstall once again.

I can't remember my exact steps, but I believe I:
1. Input Radarr server configuration settings, but did not fill out Radarr interface settings yet
2. Click test connectivity button
3. Input the Radarr interface settings
4. Save

I think the javascript error I posted earlier is a red herring, as I still see this error when I load my currently working Radar settings page.

**Comment by JakeMHughes** [comment]
@steezeburger I actually ended up just using their API manually to update it. If you go to 'https://(deployment url)/swagger' it will load the API spec. Probably a lot easier than starting from scratch

**Comment by steezeburger** [comment]
@JakeMHughes oh nice, that's a much more optimal work around!

**Comment by pig0r** [comment]
Can confirm this is still an issue.  Ombi on windows.  Was able to set up ombi, but now can no longer change any settings because the submit and test connectivity buttons do not work.

**Comment by JeanThirion** [comment]
Still an issue - latest version to date... Any workaround ?
