### ISSUE TITLE
Authentication Errors (Emby Connect)

### ISSUE THREAD

**Issue by mellow129** [Ombi-app/Ombi#5021]
### Summary

This began a few weeks ago. I've attempted to fall back to an earlier docker container version, and have tried to completely reinstall from scratch. Only local user accounts can log in. All Emby connect accounts get "Incorrect username or password"
Container build version is: v4.43.5-ls167 Build-date:- 2023-09-16T22:30:08+00:00

Error in the log on authentication attempt below.

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker, Linux

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2023-10-06 14:53:06.411 +00:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: https://connect.emby.media/service/user/authenticate
2023-10-06 14:53:06.415 +00:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Authentication.OmbiUserManager.CheckEmbyPasswordAsync(OmbiUser user, String password, String clientIpAddress) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 180
   at Ombi.Core.Authentication.OmbiUserManager.CheckPasswordAsync(OmbiUser user, String password) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 93
   at Ombi.Controllers.V1.TokenController.GetToken(UserAuthModel model) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/TokenController.cs:line 87
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
```

**Comment by DMartelly** [comment]
Hey @mellow129,

In your Emby server under Settings -> Server -> Users, do the users that fail to login using Emby Connect have usernames or emails in the field `(Optional) Emby Connect email address:`?

**Comment by mellow129** [comment]
> Hey @mellow129,
> 
> In your Emby server under Settings -> Server -> Users, do the users that fail to login using Emby Connect have usernames or emails in the field `(Optional) Emby Connect email address:`?

Sigh, Yeah that was the problem.
Most of my 47 users (including me) were linked to Emby connect by user ID from a long time ago and not email address.
Switching my account over to email solved the issue. Thanks for that!
Now I have to run everyone down and convert them over from UID to email.
