### ISSUE TITLE
New linuxserver/ombi Docker Image(s) Not Working

### ISSUE THREAD

**Issue by ThePiombino** [Ombi-app/Ombi#5028]
### Summary

Expected behavior: Should be able to access web GUI after upgrading to latest version of Ombi

What's happening: Receiving the following error after upgrading and attempting to access web GUI: **_This site can’t be reached / 192.168.86.200 refused to connect._**

---
The long of the short:

Was running an older version of Ombi (4.16.11) without issue for several months, but recently noticed that user management was not working properly; ex:

- Unable to import new user(s)
- "Cleanup" option missing so when I delete users from Ombi (who no longer exist on my Plex server) and then run the user importer, Ombi would just re-create said Plex users

So I went to upgrade to the latest Ombi image (4.43.5-ls169); however, the web GUI is no longer accessible -- receiving the following error:

> This site can’t be reached
> 192.168.86.200 refused to connect.

I didn't change any other parameters other than the image. Any insight? Please let me know whatever other info I can provide.

Thanks!

### Ombi Version

4.43.5-ls169

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
$ cat log-20231023.txt 
2023-10-23 14:03:25.665 +00:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2023-10-23 14:03:25.729 +00:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2023-10-23 14:03:25.733 +00:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2023-10-23 14:03:25.735 +00:00 [Information] RAMJobStore initialized.
2023-10-23 14:03:25.739 +00:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2023-10-23 14:03:25.739 +00:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2023-10-23 14:03:25.739 +00:00 [Information] Quartz scheduler version: 3.1.0.0
2023-10-23 14:03:25.740 +00:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2023-10-23 14:03:25.825 +00:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2023-10-23 14:03:28.865 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.V1.IdentityController.GetUserAccessToken() in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/IdentityController.cs:line 899
   at lambda_method535(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
```

**Comment by ThePiombino** [comment]
> The jump between versions is very large. Can you try and run some versions between?

I forgot I had opened this issue -- it has been resolved! I currently have Ombi 4.43.5 working. Turned out the issue was I had an outdated Docker engine which was causing an issue with Ubuntu Jammy. Wasn't able to upgrade it (currently looking into that). But I was able to create the container using the following which fixed the issue:

--security-opt seccomp=unconfined
