### ISSUE TITLE
[ERR] Job System.INewsletterJob threw an exception.

### ISSUE THREAD

**Issue by N47H4N** [Ombi-app/Ombi#5037]
### Summary

The newsletter option is not working any more.

It was working 1 week ago.

What's changed since last week:
- upgraded to 4.43.5
- migrated from sqli to mysql

Step to reproduce:
Click on "Trigger now" into the Newsletter section

Quick info: Email notifications are still working fine

thx

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

MySQL

### Relevant log output

```shell
2023-11-10 12:01:24.192 +01:00 [ERR] Job System.INewsletterJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.TheMovieDb.TheMovieDbApi.Find(String externalId, ExternalSource source) in /home/runner/work/Ombi/Ombi/src/Ombi.TheMovieDbApi/TheMovieDbApi.cs:line 121
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.GetTheMovieDbId(Boolean hasTvDbId, Boolean hasImdb, String tvdbID, String imdbId, String title, Boolean movie) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 472
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetMoviesWithoutId[T](HashSet`1 addedMovieLogIds, HashSet`1 needsMovieDb, IMediaServerContentRepository`1 repository) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 369
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetMoviesContent[T](IMediaServerContentRepository`1 repository, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 296
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 124
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 232
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 401
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.TheMovieDb.TheMovieDbApi.Find(String externalId, ExternalSource source) in /home/runner/work/Ombi/Ombi/src/Ombi.TheMovieDbApi/TheMovieDbApi.cs:line 121
   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.GetTheMovieDbId(Boolean hasTvDbId, Boolean hasImdb, String tvdbID, String imdbId, String title, Boolean movie) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 472
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetMoviesWithoutId[T](HashSet`1 addedMovieLogIds, HashSet`1 needsMovieDb, IMediaServerContentRepository`1 repository) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 369
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetMoviesContent[T](IMediaServerContentRepository`1 repository, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 296
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 124
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 232
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 401
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2023-11-10 14:01:45.478 +01:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/find/?api_key=b8eabaf5608b88d0298aaXXXXXXXX&external_source=imdb_id
```

**Comment by N47H4N** [comment]
.
