### ISSUE TITLE
Won't process requests via Radarr

### ISSUE THREAD

**Issue by bmanturner** [Ombi-app/Ombi#5045]
### Summary

(Sonarr works fine)

Radarr Version: 5.1.3.8246

### Ombi Version

4.43.10

### What platform(s) does this occur on?

Linux

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2023-12-02 16:54:27.927 -06:00 [ERR] Error when sending movie to DVR app, added to the request queue
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.MovieSender.GetOrCreateTag(MovieRequests model, RadarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 249
   at Ombi.Core.Senders.MovieSender.SendToRadarr(MovieRequests model, RadarrSettings settings, Boolean is4k) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 184
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model, Boolean is4K) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 72
```

**Comment by tidusjar** [comment]
Have you set any tags against the user or in the Radarr settings?

**Comment by tidusjar** [comment]
Interesting, I’ll investigate. What version of radarr are you using?

**Comment by mike10010100** [comment]
I'd like to join in on this issue, I'm having similar problems:

Ombi version: 4.43.11
Sonarr version: 4.0.1.929
Radarr version: 5.2.6.8376

Error logs:

```
2024-01-19 10:45:01.482 -05:00 [WRN] No TheMovieDb Id found for Rankin-Bass Holiday Classics for user patmich7, could not import via Plex WatchList
2024-01-19 10:50:01.376 -05:00 [WRN] No TheMovieDb Id found for Rankin-Bass Holiday Classics for user patmich7, could not import via Plex WatchList
2024-01-19 10:50:22.381 -05:00 [ERR] Exception thrown when attempting to send series over to Sonarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s, SonarrSendOptions options) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 367
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 256
2024-01-19 10:50:22.382 -05:00 [ERR] Exception thrown when sending a movie to DVR app, added to the request queue
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSeries result, SonarrSettings s, SonarrSendOptions options) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 367
   at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 256
   at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 52
```

**Comment by Baltimorepc** [comment]
same here

**Comment by tidusjar** [comment]
This should now be fixed in the latest version (v4.48.2)
