### ISSUE TITLE
Item Added To Retry Queue

### ISSUE THREAD

**Issue by ThePiombino** [Ombi-app/Ombi#5052]
### Summary

Unable to add content to DVR (DogNZB) from Ombi. I have updated the API key and getting same results. Affects all users, any content. Requests get sent to the "Retry Queue" with a "Processing Request" status.

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2023-12-13 17:04:20.329 +00:00 [ERR] Error when sending movie to DVR app, added to the request queue
System.Net.Http.HttpRequestException: Connection timed out (api.dognzb.cr:443)
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.DogNzb.DogNzbApi.AddMovie(String apiKey, String imdbid) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.DogNzb/DogNzbApi.cs:line 81
   at Ombi.Core.Senders.MovieSender.SendToDogNzb(FullBaseRequest model, DogNzbSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 133
   at Ombi.Core.Senders.MovieSender.Send(MovieRequests model, Boolean is4K) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/MovieSender.cs:line 78
```

**Comment by ThePiombino** [comment]
Confirmed issue with Usenet site; now working
