### ISSUE TITLE
Plex User import failing

### ISSUE THREAD

**Issue by cpizzle1983** [Ombi-app/Ombi#5081]
### Summary

Plex Media server Version: 1.40.0.7998
Enviroment: Windows 10 x64

Plex User import is failing in Ombi.
Seems like an outdated xsd or parser config

### Ombi Version

4.43.11

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2024-03-03 00:00:01.551 -08:00 [ERR] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/api/users/

2024-03-03 00:00:01.552 -08:00 [ERR] Job Plex.IPlexUserImporter threw an unhandled Exception: 

System.InvalidOperationException: There is an error in XML document (2, 2).

 ---> System.InvalidOperationException: <errors xmlns=''> was not expected.

   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexUsers.Read4_MediaContainer()

   --- End of inner exception stack trace ---

   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)

   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)

   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95

   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90

   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203

   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportPlexUsers(UserManagementSettings userManagementSettings, List`1 allUsers, PlexServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 117

   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 78

   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 25

   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
```

**Comment by tidusjar** [comment]
We can’t authorize with Plex. Check your Plex settings as something is not right

**Comment by cpizzle1983** [comment]
![ombi-plex-conn](https://github.com/Ombi-app/Ombi/assets/16843502/f23c6055-d9a0-4cbd-93f6-9a54a0e3f6cb)

Uploading the Plex settings snip. 
It shows that Ombi was able to successfully connect. 
I would have imagined that if there was an issue with connecting with Plex, Ombi would have had an issue syncing movies/series?

Please let me know what else I can check to help you further debug this issue.
Regards.

**Comment by tidusjar** [comment]
And is there a problem syncing? 
Because that's why the importer is failing

> StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/api/users/

**Comment by cpizzle1983** [comment]
No, syncing is working fine. Which is what i was eluding to.
All communications with the Plex server is working as expected, it is just user import that is facing issues.

**Comment by cpizzle1983** [comment]
No, syncing is working fine. Which is what i was eluding to.
All communications with the Plex server is working as expected, it is just user import that is facing issues.

**Comment by cpizzle1983** [comment]
Just an update on this issue.
I deleted my Plex server config from Ombi and re-added it back into Ombi and the user import worked just fine.

Closing the issue
