### ISSUE TITLE
Can't suddenly not send email

### ISSUE THREAD

**Issue by Thedaggert** [Ombi-app/Ombi#5093]
### Summary

It will not send emails anymore and i have been using it for alsmost 2 years and i have never had this issue before.
I tried to upload a config backup from last week but it didnt help, i use the same email settings for other programs and the work fine.

### Ombi Version

 4.43.14 

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
fail: Ombi.Notifications.GenericEmailProvider[0]
      Exception when attempting to send an email
      System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/ombi/bin/Debug/net6.0/Templates/BasicTemplate.html'.
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
         at System.IO.File.InternalReadAllText(String path, Encoding encoding)
         at System.IO.File.ReadAllText(String path)
         at Ombi.Notifications.Templates.EmailBasicTemplate.LoadTemplate(String subject, String body, String imgsrc, String logo, String url) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications.Templates/EmailBasicTemplate.cs:line 36
         at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 40
warn: Ombi.Controllers.V1.External.TesterController[0]
      Exception when testing Email Notifications
      System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/ombi/bin/Debug/net6.0/Templates/BasicTemplate.html'.
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
         at System.IO.File.InternalReadAllText(String path, Encoding encoding)
         at System.IO.File.ReadAllText(String path)
         at Ombi.Notifications.Templates.EmailBasicTemplate.LoadTemplate(String subject, String body, String imgsrc, String logo, String url) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications.Templates/EmailBasicTemplate.cs:line 36
         at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 40
         at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 300
```

**Comment by ExtremeFiretop** [comment]
Duplicate of: 

https://github.com/Ombi-app/Ombi/issues/5088

and 

https://github.com/Ombi-app/Ombi/issues/5091

Both still open.

**Comment by Thedaggert** [comment]
I can see mine stopped working on the friday morning of 7 march.
My watchtower pulled the new docker release so i can 110% say it worked in v4.43.13

**Comment by mzemaita** [comment]
I am on a Windows 11 Pro. configured gmail for smtp and send email out using my account. Never had any issues. 

When I upgraded to 4.43.14 and restored all 3 ombi database files including ombisetting.db all of my setting were restored but email was completely broken. I had to revert back to the last working version which was 4.43.6. I double check gmail password everything is setup correctly. There is a problem with 4.43.14.

**Comment by TheOneOgre** [comment]
Also using 4.43.14. Just tried setting up email notifications and am receiving the same error. Have not used email on previous versions so can't add to the fact if downgrading helps, but it is not working on the latest dev version it seems.

**Comment by ExtremeFiretop** [comment]
Questions related to versions were answered already in the other threads mentioned. Thanks guys.

**Comment by bjornjorgensen** [comment]
fixed in [v4.43.16](https://github.com/Ombi-app/Ombi/releases/tag/v4.43.16) I tested it and it works :)

**Comment by harroguk** [comment]
> fixed in [v4.43.16](https://github.com/Ombi-app/Ombi/releases/tag/v4.43.16) I tested it and it works :)

Confirmed. This can be closed.

**Comment by Thedaggert** [comment]
Yes it's working now :-)

**Comment by Thedaggert** [comment]
Yes its working now :-)
