### ISSUE TITLE
Exception When Cacching Emby for Server

### ISSUE THREAD

**Issue by Tor-Brynjar** [Ombi-app/Ombi#5101]
### Summary

My Ombi log is full of repeated errors stating `[ERR] Exception when caching Emby for server server_name_was_here`.

I've tried removing my media server and readding it in Ombi, manually running a full sync, manually running a recently added sync, clearing data and resyncing, uninstall and reinstalling Ombi, and deleting all MySQL data and re-migrating to no effect.

I attempted to chase the error down and this is what I'd found:

As the error specifically references `EmbyPlayedSync.ProcessTv`, I believed the error to be thrown during TV episode processing due to episode-related metadata such as TMDB.

Looking at `ProcessTv` in `EmbyPlayedSync.cs`, I _think_ the error is originating from line 180 to 184:
`if (!int.TryParse(parent.TheMovieDbId, out var parentMovieDb))
{
    _logger.LogWarning($"Episode {episode.Name} for Tv Show {parent.Title} Doesn't have a valid TheMovieDbId. Skipping.");
    return;
}`

My assumption is that this code snippet is attempting to parse `TheMovieDbId` of a TV show obtained from `parent.TheMovieDbId` into an integer and failing to do so because the integer is either not a valid number or missing. What I don't understand though is that I'd expect to see `Episode {episode.Name} for Tv Show {parent.Title} Doesn't have a valid TheMovieDbId. Skipping.` in the log, but I don't.

Looking at `TheMovieDbId` column of the `EmbyEpisode` table, I can see that all 43,788 rows, **except one**, have `NULL` as their value. I'm under the impression that attempting to parse `NULL` into an integer is what's failing and  causing the error. _But why are all entries except one null?_

![image](https://github.com/Ombi-app/Ombi/assets/99004695/38c6b6b8-f65b-4077-9b3f-6216fa3d6173)

Emby `TheMovieDbId` metadata is complete for all shows, so the issue lay somewhere else with Ombi's ability to grab it from Emby.

![image](https://github.com/Ombi-app/Ombi/assets/99004695/42860439-9533-4b6c-b0bd-a5ec3b142b6b)

At this point I began looking at the second error stating `[ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/88329?api_key_was_here`

I searched my Ombi database for `88329` and can see that `88329` is **part of** the `Id` column of `EmbyEpisode`, but it's missing the first digit.

![image](https://github.com/Ombi-app/Ombi/assets/99004695/126c34f8-73ae-472b-a984-27c6adfbc1f3)

I then checked my metadata for Valentine's Day and can see that `TheMovieDbId` is entered, but it is entered as `NULL` in the Ombi database for some reason.

![image](https://github.com/Ombi-app/Ombi/assets/99004695/635e5e85-22bc-42b2-8282-858a015e4ba8)

At this point I'm at a loss and have no idea what's going on, any help would be appreciated!

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

MySQL

### Relevant log output

```shell
2024-03-18 07:30:06.124 -05:00 [ERR] Exception when caching Emby for server server_name_was_here
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyEpisodes episode, OmbiUser user, ICollection`1 content, EmbyServers server)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTvUser(EmbyServers server, OmbiUser user, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 149
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyServers server, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 48
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.StartServerCache(EmbyServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 92
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 57
2024-03-18 08:30:04.647 -05:00 [ERR] Exception when caching Emby for server server_name_was_here
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyEpisodes episode, OmbiUser user, ICollection`1 content, EmbyServers server)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTvUser(EmbyServers server, OmbiUser user, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 149
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyServers server, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 48
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.StartServerCache(EmbyServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 92
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 57
2024-03-18 09:30:06.030 -05:00 [ERR] Exception when caching Emby for server server_name_was_here
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyEpisodes episode, OmbiUser user, ICollection`1 content, EmbyServers server)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTvUser(EmbyServers server, OmbiUser user, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 149
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyServers server, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 48
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.StartServerCache(EmbyServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 92
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 57
2024-03-18 10:30:04.723 -05:00 [ERR] Exception when caching Emby for server server_name_was_here
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyEpisodes episode, OmbiUser user, ICollection`1 content, EmbyServers server)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTvUser(EmbyServers server, OmbiUser user, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 149
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyServers server, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 48
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.StartServerCache(EmbyServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 92
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 57
2024-03-18 11:30:05.842 -05:00 [ERR] Exception when caching Emby for server server_name_was_here
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyEpisodes episode, OmbiUser user, ICollection`1 content, EmbyServers server)
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTvUser(EmbyServers server, OmbiUser user, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 149
   at Ombi.Schedule.Jobs.Emby.EmbyPlayedSync.ProcessTv(EmbyServers server, String parentId) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs:line 48
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.StartServerCache(EmbyServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 92
   at Ombi.Schedule.Jobs.Emby.EmbyLibrarySync.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs:line 57
2024-03-18 14:01:34.054 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/66515?api_key_was_here
2024-03-18 14:01:34.406 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1399?api_key_was_here
2024-03-18 14:01:35.554 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1338?api_key_was_here
2024-03-18 14:01:35.811 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/95479?api_key_was_here
2024-03-18 14:01:36.043 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4604?api_key_was_here
2024-03-18 14:01:36.142 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/32798?api_key_was_here
2024-03-18 14:01:36.566 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/127532?api_key_was_here
2024-03-18 14:01:36.934 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/tv/0?api_key_was_here&language=en&append_to_response=videos%2Ccredits%2Csimilar%2Crecommendations%2Cexternal_ids%2Ckeywords%2Cimages
2024-03-18 14:01:49.524 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/45?api_key_was_here
2024-03-18 14:01:50.000 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4018?api_key_was_here
2024-03-18 14:01:50.000 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4018?api_key_was_here
2024-03-18 14:01:50.343 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/65334?api_key_was_here
2024-03-18 14:01:50.344 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/65334?api_key_was_here
2024-03-18 14:01:50.827 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/40561?api_key_was_here
2024-03-18 14:01:50.829 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/40561?api_key_was_here
2024-03-18 14:01:51.549 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2875?api_key_was_here
2024-03-18 14:01:51.549 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2875?api_key_was_here
2024-03-18 14:01:52.055 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/12971?api_key_was_here
2024-03-18 14:01:52.055 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/12971?api_key_was_here
2024-03-18 14:01:52.056 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/12971?api_key_was_here
2024-03-18 14:01:52.233 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/209867?api_key_was_here
2024-03-18 14:01:52.234 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/209867?api_key_was_here
2024-03-18 14:01:52.234 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/209867?api_key_was_here
2024-03-18 14:01:53.111 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1516?api_key_was_here
2024-03-18 14:01:53.111 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1516?api_key_was_here
2024-03-18 14:01:53.111 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1516?api_key_was_here
2024-03-18 14:01:53.111 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1516?api_key_was_here
2024-03-18 14:01:53.244 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4607?api_key_was_here
2024-03-18 14:01:53.244 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4607?api_key_was_here
2024-03-18 14:01:53.244 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4607?api_key_was_here
2024-03-18 14:01:53.244 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4607?api_key_was_here
2024-03-18 14:01:53.853 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/120089?api_key_was_here
2024-03-18 14:01:53.853 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/120089?api_key_was_here
2024-03-18 14:01:53.854 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/120089?api_key_was_here
2024-03-18 14:01:53.854 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/120089?api_key_was_here
2024-03-18 14:04:30.659 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/1973?api_key_was_here
2024-03-18 14:04:30.744 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/67133?api_key_was_here
2024-03-18 14:04:30.744 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/67133?api_key_was_here
2024-03-18 14:04:30.890 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/91555?api_key_was_here
2024-03-18 14:04:30.890 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/91555?api_key_was_here
2024-03-18 14:04:30.963 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/34891?api_key_was_here
2024-03-18 14:04:30.963 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/34891?api_key_was_here
2024-03-18 14:04:31.038 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4357?api_key_was_here
2024-03-18 14:04:31.038 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4357?api_key_was_here
2024-03-18 14:04:31.116 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4414?api_key_was_here
2024-03-18 14:04:31.116 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4414?api_key_was_here
2024-03-18 14:04:31.126 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/4414?api_key_was_here
2024-03-18 14:04:31.196 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/89393?api_key_was_here
2024-03-18 14:04:31.196 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/89393?api_key_was_here
2024-03-18 14:04:31.197 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/89393?api_key_was_here
2024-03-18 14:04:31.306 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/76773?api_key_was_here
2024-03-18 14:04:31.307 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/76773?api_key_was_here
2024-03-18 14:04:31.307 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/76773?api_key_was_here
2024-03-18 14:04:31.591 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/60572?api_key_was_here
2024-03-18 14:04:31.591 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/60572?api_key_was_here
2024-03-18 14:04:31.591 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/60572?api_key_was_here
2024-03-18 14:04:31.591 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/60572?api_key_was_here
2024-03-18 14:04:31.673 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2808?api_key_was_here
2024-03-18 14:04:31.673 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2808?api_key_was_here
2024-03-18 14:04:31.674 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2808?api_key_was_here
2024-03-18 14:04:31.675 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2808?api_key_was_here
2024-03-18 14:04:31.906 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/3382?api_key_was_here
2024-03-18 14:04:31.907 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/3382?api_key_was_here
2024-03-18 14:04:31.907 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/3382?api_key_was_here
2024-03-18 14:04:31.907 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/3382?api_key_was_here
2024-03-18 14:04:32.372 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2473?api_key_was_here
2024-03-18 14:04:32.372 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2473?api_key_was_here
2024-03-18 14:04:32.373 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2473?api_key_was_here
2024-03-18 14:04:32.374 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/2473?api_key_was_here
2024-03-18 14:04:32.516 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/31724?api_key_was_here
2024-03-18 14:04:32.516 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/31724?api_key_was_here
2024-03-18 14:04:32.517 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/31724?api_key_was_here
2024-03-18 14:04:32.517 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/31724?api_key_was_here
2024-03-18 14:04:32.760 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/62710?api_key_was_here
2024-03-18 14:04:32.760 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/62710?api_key_was_here
2024-03-18 14:04:32.761 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/62710?api_key_was_here
2024-03-18 14:04:32.761 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/62710?api_key_was_here
2024-03-18 14:05:01.672 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/19253?api_key_was_here
2024-03-18 14:05:02.699 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/114410?api_key_was_here
2024-03-18 14:05:02.811 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/34967?api_key_was_here
2024-03-18 14:05:02.909 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/60554?api_key_was_here
2024-03-18 14:05:02.998 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/35442?api_key_was_here
2024-03-18 14:05:03.572 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/5031?api_key_was_here
2024-03-18 14:05:03.576 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/5031?api_key_was_here
2024-03-18 14:05:03.651 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/95205?api_key_was_here
2024-03-18 14:05:03.653 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/95205?api_key_was_here
2024-03-18 14:05:03.728 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/474?api_key_was_here
2024-03-18 14:05:03.729 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/474?api_key_was_here
2024-03-18 14:05:04.053 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/97525?api_key_was_here
2024-03-18 14:05:04.053 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/97525?api_key_was_here
2024-03-18 14:05:04.425 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/88329?api_key_was_here
2024-03-18 14:05:04.429 -05:00 [ERR] StatusCode: NotFound, Reason: Not Found, RequestUri: http://api.themoviedb.org/3/movie/88329?api_key_was_here
```

**Comment by Tor-Brynjar** [comment]
I am still experiencing this issue.
