### ISSUE TITLE
Emby Login not working in 4.8.3

### ISSUE THREAD

**Issue by iamnague** [Ombi-app/Ombi#5106]
### Summary

I've just upgraded my emby server to the last 4.8.3.0 release, Emby authentication seems broken.

### Ombi Version

 4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
`
ombi    | fail: Ombi.Api.Api[1000]
ombi    |       StatusCode: InternalServerError, Reason: Internal Server Error, RequestUri: http://xx:xx:xx:xx:8096/emby/users/authenticatebyname
ombi    | fail: Microsoft.AspNetCore.Identity.UserManager[0]
ombi    |       Emby Login Failed
ombi    |       Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: G. Path '', line 0, position 0.
ombi    |          at Newtonsoft.Json.JsonTextReader.ParseValue()
ombi    |          at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
ombi    |          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
ombi    |          at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
ombi    |          at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
ombi    |          at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
ombi    |          at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
ombi    |          at Ombi.Api.Emby.EmbyApi.LogIn(String username, String password, String apiKey, String baseUri, String clientIpAddress) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Emby/EmbyApi.cs:line 79
ombi    |          at Ombi.Core.Authentication.OmbiUserManager.CheckEmbyPasswordAsync(OmbiUser user, String password, String clientIpAddress) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Authentication/OmbiUserManager.cs:line 201
ombi    | warn: Ombi.Controllers.V1.TokenController[0]
ombi    |       Failed login attempt by IP: xx:xx:xx:xx
`
```

**Comment by iamnague** [comment]
I guess this issue is not impacting anyone here... FYI same behavior with emby 4.8.8.0 and ombi 4.43.5.

**Comment by Tuumke** [comment]
+1

Also seeing these, not sure if related:

`2024-10-04 16:04:05.702 +02:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null. (Parameter 'user')
   at System.ArgumentNullException.Throw(String paramName)
   at Microsoft.AspNetCore.Identity.UserManager`1.GetRolesAsync(TUser user)
   at Ombi.Controllers.V1.IdentityController.GetUserWithRoles(OmbiUser user) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/IdentityController.cs:line 360
   at Ombi.Controllers.V1.IdentityController.GetUser(String id) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/IdentityController.cs:line 355
   at lambda_method1159(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24`

**Comment by iamnague** [comment]
Still present in Ombi 4.447.1.
Any hope someone fix this issue ?
