### ISSUE TITLE
After update docker shows ombi running but unable to load the page

### ISSUE THREAD

**Issue by mayoko185** [Ombi-app/Ombi#5132]
### Summary

After updating docker to the latest image I'm unable to access ombi. Looking at the logs looks like like ombi can no longer connect to mysql maybe? rolling back to the previous img development-v4.44.0-ls399 fixes the issue

### Ombi Version

v4.44.0

### What platform(s) does this occur on?

Docker

### What database are you using?

MySQL

### Relevant log output

```shell
2024-07-16T00:41:44.271431991Z Unhandled exception. MySqlConnector.MySqlException (0x80004005): SSL Authentication Error
2024-07-16T00:41:44.271446659Z  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
2024-07-16T00:41:44.271450035Z  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
2024-07-16T00:41:44.271452600Z  ---> Interop+Crypto+OpenSslCryptographicException: error:0A000410:SSL routines::sslv3 alert handshake failure
2024-07-16T00:41:44.271454584Z    --- End of inner exception stack trace ---
2024-07-16T00:41:44.271456507Z    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
2024-07-16T00:41:44.271458671Z    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
2024-07-16T00:41:44.271460846Z    --- End of inner exception stack trace ---
2024-07-16T00:41:44.271462549Z    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
2024-07-16T00:41:44.271464513Z    at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
2024-07-16T00:41:44.271466566Z    at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, MySqlConnection connection, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1445
2024-07-16T00:41:44.271468861Z    at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, MySqlConnection connection, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1472
2024-07-16T00:41:44.271471095Z    at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 523
2024-07-16T00:41:44.271480292Z    at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 932
2024-07-16T00:41:44.271482927Z    at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 938
2024-07-16T00:41:44.271484991Z    at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
2024-07-16T00:41:44.271486915Z    at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 381
2024-07-16T00:41:44.271488918Z    at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
2024-07-16T00:41:44.271490762Z    at Ombi.Extensions.DatabaseExtensions.<>c__DisplayClass11_0.<GetServerVersion>b__2() in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 193
2024-07-16T00:41:44.271493006Z    at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context _, CancellationToken _)
2024-07-16T00:41:44.271495120Z    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
2024-07-16T00:41:44.271497414Z    at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
2024-07-16T00:41:44.271499238Z    at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
2024-07-16T00:41:44.271501071Z    at Polly.Policy.Execute[TResult](Func`1 action)
2024-07-16T00:41:44.271502805Z    at Ombi.Extensions.DatabaseExtensions.GetServerVersion(String connectionString) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 193
2024-07-16T00:41:44.271504759Z    at Ombi.Extensions.DatabaseExtensions.ConfigureMySql(DbContextOptionsBuilder options, PerDatabaseConfiguration config) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 161
2024-07-16T00:41:44.271506943Z    at Ombi.Extensions.DatabaseExtensions.<>c__DisplayClass3_0.<ConfigureDatabases>b__7(DbContextOptionsBuilder x) in /home/runner/work/Ombi/Ombi/src/Ombi/Extensions/DatabaseExtensions.cs:line 73
2024-07-16T00:41:44.271509147Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider _, DbContextOptionsBuilder b)
2024-07-16T00:41:44.271511231Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
2024-07-16T00:41:44.271513205Z    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
2024-07-16T00:41:44.271517353Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-07-16T00:41:44.271519316Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-07-16T00:41:44.271521230Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-07-16T00:41:44.271523193Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-07-16T00:41:44.271525087Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2024-07-16T00:41:44.271527041Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-07-16T00:41:44.271528954Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-07-16T00:41:44.271530838Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-07-16T00:41:44.271532751Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-07-16T00:41:44.271534825Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2024-07-16T00:41:44.271536779Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2024-07-16T00:41:44.271538843Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
2024-07-16T00:41:44.271540777Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2024-07-16T00:41:44.271542600Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2024-07-16T00:41:44.271544504Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2024-07-16T00:41:44.271546457Z    at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 74
2024-07-16T00:41:44.271548260Z    at Ombi.Program.<Main>(String[] args)
```

**Comment by tidusjar** [comment]
The fact that you are rolling back to another image but running the same Ombi version (4.44.0) implies this has not been cause by Ombi?

I'm not sure what the problem would be here as it's complaining about a SSL error with your MySQL database.

**Comment by lumbermetal** [comment]
You may need to update  your version of mysql.  This fixed it for me.  I am using the linuxserver.io ombi container and the example from the ombi website.  Make a backup of your data and change the image for mysql to mariadb.  Worked without a hitch for me.  I am assuming the issue was probably outdated openssl version on mysql container.  Hope this helps.

OpenSSL 1.0.2k-fips  26 Jan 2017 - mysql:5.7 container

OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022) - ombi container

**Comment by borger** [comment]
This exact same issue was happening to me, switching to a mariadb container, did solve the problem.

**Comment by mayoko185** [comment]
Thanks for the reply's I think youre right the mysql 5.7 img is using an older version of openssl thats causing the issue, I originally followed the guide at https://docs.ombi.app/info/docker-containers/#docker-compose. 

I'm still a bit green messing with docker sorry if im missing something simple, I tried to change out the line in my docker-compose from     image: "mysql:5.7" to image: lscr.io/linuxserver/mariadb:latest but now im getting a different error in the logs and ombi doesnt load in the browser:

Unhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'AspNetRoles' already exists
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 108
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Ombi.Store.Context.MySql.OmbiMySqlContext..ctor(DbContextOptions`1 options) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Context/MySql/OmbiMySqlContext.cs:line 14
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 75
   at Ombi.Program.<Main>(String[] args)

**Comment by tidusjar** [comment]
That error indicates that Ombi is attempting to run a migration on your database now. That means that it’s either missing data or tables so it’s on a bit of a corrupted state…

**Comment by lumbermetal** [comment]
I changed my image to:
 image: mariadb

**Comment by Darkassassin07** [comment]
I also had this error due to mysql:5.7 in my compose file from the example docs.

Upgrading it straight to 'latest' threw errors about not being able to upgrade this version, so I backed off to mysql:8.2
That got me up and running again, with ombi:latest loading and functioning properly. So I upgraded again -> 8.3. Also successful.

I finally tried 8.4.0, but that also errored saying unable to upgrade from this version (8.3). That's where I've left it for the time being.

**Comment by mayoko185** [comment]
> I also had this error due to mysql:5.7 in my compose file from the example docs.
> 
> Upgrading it straight to 'latest' threw errors about not being able to upgrade this version, so I backed off to mysql:8.2 That got me up and running again, with ombi:latest loading and functioning properly. So I upgraded again -> 8.3. Also successful.
> 
> I finally tried 8.4.0, but that also errored saying unable to upgrade from this version (8.3). That's where I've left it for the time being.

Thanks, this ended up being my fix for now as well. I tried to get mariadb to work but some reason had issues with root password not working.

Changing out mysql:5.7 to mysql:8.2 and everything working on the latest ombi img.

**Comment by jaydenthorup** [comment]
This worked for me as well in my docker-compose file except my version was 5.1 or something.
"Changing out mysql:5.7 to mysql:8.2 and everything working on the latest ombi img."

**Comment by lt-schall** [comment]
How can I update mysql? Isn't it inqluded with the docker image and should be updated in the provided image? For me It's a first time setup, and I'm getting similar errors.

**Comment by Darkassassin07** [comment]
In your docer compose file, replace the line:

image: mysql:5.7

With

image: mysql:8.3
