### ISSUE TITLE
Importing PLEX Users

### ISSUE THREAD

**Issue by ChewyChop** [Ombi-app/Ombi#5144]
### Summary

When attempting to import PLEX users, it appears that Ombi is using the endpoint "https://plex.tv/pms/friends/all/" which gets a response from plex.tv as "<Response code="410" status="This endpoint was deprecated and removed"/>".

### Ombi Version

4.39.1

### What platform(s) does this occur on?

Linux

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2024-07-25 17:40:10.841 +00:00 [ERR] StatusCode: Gone, Reason: Gone, RequestUri: https://plex.tv/pms/friends/all/
2024-07-25 17:40:10.842 +00:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203
   at Ombi.Controllers.V1.External.PlexController.GetFriends() in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/PlexController.cs:line 263
   at lambda_method1149(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2024-07-25 17:40:13.142 +00:00 [ERR] StatusCode: Gone, Reason: Gone, RequestUri: https://plex.tv/pms/friends/all/
2024-07-25 17:40:13.142 +00:00 [ERR] Job Plex.IPlexUserImporter threw an unhandled Exception: 
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportPlexUsers(UserManagementSettings userManagementSettings, List`1 allUsers, PlexServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 104
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 79
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-07-25 17:40:13.142 +00:00 [ERR] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportPlexUsers(UserManagementSettings userManagementSettings, List`1 allUsers, PlexServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 104
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 79
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportPlexUsers(UserManagementSettings userManagementSettings, List`1 allUsers, PlexServers server) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 104
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 79
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2024-07-25 17:43:36.163 +00:00 [ERR] StatusCode: Gone, Reason: Gone, RequestUri: https://plex.tv/pms/friends/all/
2024-07-25 17:43:36.164 +00:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203
   at Ombi.Controllers.V1.External.PlexController.GetFriends() in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/PlexController.cs:line 263
   at lambda_method1149(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2024-07-25 17:45:52.513 +00:00 [ERR] StatusCode: Gone, Reason: Gone, RequestUri: https://plex.tv/pms/friends/all/
2024-07-25 17:45:52.514 +00:00 [ERR] Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 203
   at Ombi.Controllers.V1.External.PlexController.GetFriends() in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/PlexController.cs:line 263
   at lambda_method1149(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 58
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 30
2024-07-25 17:54:08.863 +00:00 [INF] Default Quartz.NET properties loaded from embedded resource file
2024-07-25 17:54:08.902 +00:00 [INF] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2024-07-25 17:54:08.902 +00:00 [INF] Quartz Scheduler created
2024-07-25 17:54:08.902 +00:00 [INF] RAMJobStore initialized.
2024-07-25 17:54:08.903 +00:00 [INF] Quartz Scheduler 3.5.0.0 - 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED' initialized
2024-07-25 17:54:08.903 +00:00 [INF] Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10
2024-07-25 17:54:08.903 +00:00 [INF] Using job store 'Quartz.Simpl.RAMJobStore', supports persistence: False, clustered: False
2024-07-25 17:54:08.903 +00:00 [INF] JobFactory set to: Ombi.Schedule.IoCJobFactory
2024-07-25 17:54:08.941 +00:00 [INF] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
```

**Comment by tidusjar** [comment]
Please use the latest version. You are a few versions behind
