### ISSUE TITLE
Email notification invalid domain

### ISSUE THREAD

**Issue by Thom0145** [Ombi-app/Ombi#5161]
### Summary

My test email will not send, when I check the logs I get invalid domain

[log20240816.txt](https://github.com/user-attachments/files/16642936/log20240816.txt)

### Ombi Version

 4.44.1

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
System.ArgumentException: The domain is invalid. (Parameter 'domain')
   at MimeKit.Utils.MimeUtils.GenerateMessageId(String domain)
   at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 47
   at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 300
```

**Comment by tidusjar** [comment]
What’s your domain in the application url under the ombi settings? Like the
general settings?
