### ISSUE TITLE
Postgres as database throws exception

### ISSUE THREAD

**Issue by gen2fish** [Ombi-app/Ombi#5162]
### Summary

Running 4.44.1 docker image from linuxserver on kubernetes with the following database.json causes an unhandled exception

```json
{
    "OmbiDatabase": {
        "Type": "Postgres",
        "ConnectionString": "Host=ombi-rw;Port=5432;Database=ombi;Username=ombi;Password=XXXX"
    },
    "SettingsDatabase": {
        "Type": "Postgres",
        "ConnectionString": "Host=ombi-rw;Port=5432;Database=ombi;Username=obmi;Password=XXXX"
    },
    "ExternalDatabase": {
        "Type": "Postgres",
        "ConnectionString": "Host=ombi-rw;Port=5432;Database=ombi;Username=ombi;Password=XXXX"
    }
}
```

This is the same in the 4.45 development version

### Ombi Version

4.44.1

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Storage.IRelationalValueBufferFactoryFactory' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=8.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.Extensions.DependencyInjection.NpgsqlServiceCollectionExtensions.AddEntityFrameworkNpgsql(IServiceCollection serviceCollection)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal.NpgsqlOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Ombi.Store.Context.SettingsContext..ctor(DbContextOptions options) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Context/SettingsContext.cs:line 22
   at Ombi.Store.Context.Postgres.SettingsPostgresContext..ctor(DbContextOptions`1 options) in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Context/Postgres/SettingsPostgresContext.cs:line 8
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Ombi.Program.Main(String[] args) in /home/runner/work/Ombi/Ombi/src/Ombi/Program.cs:line 74
   at Ombi.Program.<Main>(String[] args)
```

**Comment by D0cR3d** [comment]
I'm having the same issue. I posted on the [Pull Request](https://github.com/Ombi-app/Ombi/pull/5050#issuecomment-2265558932) but got no response.

**Comment by tidusjar** [comment]
Can you try https://github.com/Ombi-app/Ombi/releases/tag/v4.46.0? 

I just connected PostgreSQL 16.4 (Just using the [postgres:latest](https://hub.docker.com/_/postgres)) and I'm not seeing this issue

**Comment by tidusjar** [comment]
Reverting to an older version of Ombi before the connector updates I can reproduce the issue. So I'm confident it's now been resolved

**Comment by gen2fish** [comment]
Yup, working on 4.46, thank you!
