### ISSUE TITLE
Settings changes do not persist

### ISSUE THREAD

**Issue by pig0r** [Ombi-app/Ombi#5163]
### Summary

Attempting to change a setting all of a sudden does nothing.   For instance, enabling mobile notifications and hitting submit will cause the mobile notifications to be turned off on the next refresh of the page.  Settings can't be saved for Sonarr, as both the test connectivity and submit buttons are greyed out on that specific page.   

While the system is up and working after initial configuration, it seems that no new settings changes are processed.   I have verified file permissions and everything there looks good.   From the logs, it looks like the database is locked for some reason, even though no other tasks are being run at the same time as I'm trying to save changes.   

This behavior seems to persist after a complete reinstall, and the database locks itself forever after just a few initial settings changes.

### Ombi Version

4.46.0

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.

 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

   at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()

   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

   at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)

--- End of stack trace from previous location ---

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

   at Ombi.Store.Repository.BaseRepository`2.InternalSaveChanges() in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 94

   at Ombi.Store.Repository.BaseRepository`2.SaveChangesAsync() in /home/runner/work/Ombi/Ombi/src/Ombi.Store/Repository/BaseRepository.cs:line 77

   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartPlexMovies(List`1 allMovies, PlexSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 330

   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.StartPlex(PlexSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 121

   at Ombi.Schedule.Jobs.Ombi.RefreshMetadata.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs:line 81
```

**Comment by tidusjar** [comment]
It's a limitation with SQLite, see here: https://docs.ombi.app/info/alternate-databases/#why-mysql
