### ISSUE TITLE
Ombi on Linux has stopped importing any new Plex users (UnprocessableEntity)

### ISSUE THREAD

**Issue by cthierman** [Ombi-app/Ombi#5169]
### Summary

New Plex Users no longer being imported when trying to manually import, or allowing for regular scheduled imports.

To Reproduce: 
1. Go to Ombi settings
2. Click on Configuration
3. finally click on "Run Importer" at bottom of screen. 

Message comes back saying "Plex Users import started" but nothing happens.

Expected Behavior:
Any new plex users added my plex server since last import should be added to Ombi.

Logs:

2024-09-07 23:26:46.970 -06:00 [ERR] StatusCode: UnprocessableEntity, Reason: Unprocessable Entity, RequestUri: https://plex.tv/users/account.json
2024-09-07 23:26:46.973 -06:00 [ERR] Job Plex.IPlexUserImporter threw an unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass10_0.<ImportAdmin>b__0(OmbiUser x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 202
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportAdmin(UserManagementSettings settings, PlexServers server, List`1 allUsers) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 201
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 74
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-09-07 23:26:46.974 -06:00 [ERR] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass10_0.<ImportAdmin>b__0(OmbiUser x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 202
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportAdmin(UserManagementSettings settings, PlexServers server, List`1 allUsers) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 201
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 74
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass10_0.<ImportAdmin>b__0(OmbiUser x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 202
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportAdmin(UserManagementSettings settings, PlexServers server, List`1 allUsers) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 201
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 74
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]

### Ombi Version

4.46.3

### What platform(s) does this occur on?

Linux

### What database are you using?

MySQL

### Relevant log output

```shell
2024-09-07 23:26:46.970 -06:00 [ERR] StatusCode: UnprocessableEntity, Reason: Unprocessable Entity, RequestUri: https://plex.tv/users/account.json
2024-09-07 23:26:46.973 -06:00 [ERR] Job Plex.IPlexUserImporter threw an unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass10_0.<ImportAdmin>b__0(OmbiUser x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 202
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportAdmin(UserManagementSettings settings, PlexServers server, List`1 allUsers) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 201
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 74
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-09-07 23:26:46.974 -06:00 [ERR] Job Plex.IPlexUserImporter threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass10_0.<ImportAdmin>b__0(OmbiUser x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 202
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportAdmin(UserManagementSettings settings, PlexServers server, List`1 allUsers) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 201
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 74
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.<>c__DisplayClass10_0.<ImportAdmin>b__0(OmbiUser x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 202
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.ImportAdmin(UserManagementSettings settings, PlexServers server, List`1 allUsers) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 201
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 74
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
```

**Comment by BJWTech** [comment]
Same thing is happening here. I had a user reach out stating they don't use their old email any longer. So I removed the friend in Plex and added him with his new email. He accepted and is working in Plex. 

So I went to ombi to check and he had not been imported yet. I went ahead and did the "run importer" manually. Ombi stated it would do so. 

I get the same ERR in my logs.

**Comment by josh-vin** [comment]
I'm getting a slightly different error, but my User Importer also seems to not be working

``` 
2025-02-04 00:00:02.202 -07:00 [Error] Job Plex.IPlexUserImporter threw an unhandled Exception: 
System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <Response xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexFriends.Read5_MediaContainer()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Ombi.Api.Api.DeserializeXml[T](String receivedString) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 95
   at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 90
   at Ombi.Api.Plex.PlexApi.GetUsers(String authToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api.Plex/PlexApi.cs:line 200
   at Ombi.Schedule.Jobs.Plex.PlexUserImporter.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs:line 69
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 25
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
```

**Comment by RulerOf** [comment]
Had the same problem. Appears to have been caused by me updating my account credentials. This invalidates the token Ombi uses to talk to the server.

* Go to ombi Settings > Media Server > Plex
* Click on your plex server
* Update the plex authentication token 
  * [see doc for how to grab](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)
* Validate the machine identifier and update if necessary
  * Visit `/identity` on your server's web ui, it's in the XML that displays
* Test and save if it works
