### ISSUE TITLE
Lidarr submit setting not working

### ISSUE THREAD

**Issue by mattman73** [Ombi-app/Ombi#5172]
### Summary

I enabled Lidarr, but after entering the settings, I could not click the submit button as it was greyed out.

### Ombi Version

 4.44.1

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2024-09-16T08:48:15.492603000Z fail: Ombi.Api.Api[1000]
2024-09-16T08:48:15.493316000Z       StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.0.105:8686/http://andersoninc.duckdns.org/api/v1/qualityprofile
2024-09-16T08:48:15.511832000Z fail: Ombi.ErrorHandlingMiddleware[0]
2024-09-16T08:48:15.512032000Z       Something bad happened, ErrorMiddleware caught this
2024-09-16T08:48:15.512166000Z       Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Lidarr.Models.LidarrProfile]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
2024-09-16T08:48:15.512302000Z       To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
2024-09-16T08:48:15.512443000Z       Path 'type', line 2, position 9.
2024-09-16T08:48:15.512574000Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2024-09-16T08:48:15.512698000Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2024-09-16T08:48:15.512858000Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2024-09-16T08:48:15.512996000Z          at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2024-09-16T08:48:15.513125000Z          at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
2024-09-16T08:48:15.513265000Z          at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2024-09-16T08:48:15.513389000Z          at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2024-09-16T08:48:15.513518000Z          at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 81
2024-09-16T08:48:15.513653000Z          at Ombi.Controllers.V1.External.LidarrController.GetProfiles(LidarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/LidarrController.cs:line 46
2024-09-16T08:48:15.513798000Z          at lambda_method1508(Closure, Object)
2024-09-16T08:48:15.513913000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2024-09-16T08:48:15.514022000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2024-09-16T08:48:15.514140000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:15.514249000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2024-09-16T08:48:15.514373000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-09-16T08:48:15.514526000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:15.514677000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:15.514863000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-09-16T08:48:15.515010000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-09-16T08:48:15.515156000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:15.515320000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-09-16T08:48:15.515482000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-09-16T08:48:15.515622000Z          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2024-09-16T08:48:15.515801000Z          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2024-09-16T08:48:15.515953000Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-09-16T08:48:15.516103000Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-09-16T08:48:15.516267000Z          at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
2024-09-16T08:48:15.516420000Z          at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
2024-09-16T08:48:16.844931000Z fail: Ombi.Api.Api[1000]
2024-09-16T08:48:16.845679000Z       StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.0.105:8686/http://andersoninc.duckdns.org/api/v1/rootfolder
2024-09-16T08:48:16.851830000Z fail: Ombi.ErrorHandlingMiddleware[0]
2024-09-16T08:48:16.851956000Z       Something bad happened, ErrorMiddleware caught this
2024-09-16T08:48:16.852062000Z       Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Ombi.Api.Lidarr.Models.LidarrRootFolder]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
2024-09-16T08:48:16.852175000Z       To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
2024-09-16T08:48:16.852294000Z       Path 'type', line 2, position 9.
2024-09-16T08:48:16.852399000Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2024-09-16T08:48:16.852501000Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2024-09-16T08:48:16.852605000Z          at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2024-09-16T08:48:16.852711000Z          at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2024-09-16T08:48:16.852843000Z          at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
2024-09-16T08:48:16.852938000Z          at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2024-09-16T08:48:16.853022000Z          at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2024-09-16T08:48:16.853120000Z          at Ombi.Api.Api.Request[T](Request request, CancellationToken cancellationToken) in /home/runner/work/Ombi/Ombi/src/Ombi.Api/Api.cs:line 81
2024-09-16T08:48:16.853220000Z          at Ombi.Controllers.V1.External.LidarrController.GetRootFolders(LidarrSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/LidarrController.cs:line 58
2024-09-16T08:48:16.853332000Z          at lambda_method1527(Closure, Object)
2024-09-16T08:48:16.853436000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2024-09-16T08:48:16.853536000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2024-09-16T08:48:16.853634000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:16.853729000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2024-09-16T08:48:16.853868000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-09-16T08:48:16.853970000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:16.854066000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:16.854162000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-09-16T08:48:16.854267000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-09-16T08:48:16.854365000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-09-16T08:48:16.854460000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-09-16T08:48:16.854562000Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-09-16T08:48:16.854660000Z          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2024-09-16T08:48:16.854759000Z          at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2024-09-16T08:48:16.854894000Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-09-16T08:48:16.855047000Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-09-16T08:48:16.855197000Z          at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ApiKeyMiddlewear.cs:line 51
2024-09-16T08:48:16.855355000Z          at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in /home/runner/work/Ombi/Ombi/src/Ombi/Middleware/ErrorHandlingMiddlewear.cs:line 24
```

**Comment by tidusjar** [comment]
Have you selected a profile?
