### ISSUE TITLE
Ombi Email Notifications Failing Due to Deprecation of Basic Authentication

### ISSUE THREAD

**Issue by Tor-Brynjar** [Ombi-app/Ombi#5175]
### Summary of the Issue:

The error reported relates to the recent deprecation of **Basic Authentication** by Microsoft in Exchange Online, particularly affecting applications that use SMTP, IMAP, or POP protocols. The Ombi application is attempting to authenticate using **Basic Authentication** while sending an email, which is now disabled by default, leading to the error:

`MailKit.Security.AuthenticationException: 535: 5.7.139 Authentication unsuccessful, basic authentication is disabled.`

Microsoft deprecated Basic Authentication as it is a security risk. It does not support multi-factor authentication (MFA) and is vulnerable to attacks where credentials could be intercepted and reused. Modern Authentication, based on OAuth 2.0, offers improved security by using tokens that expire and are specific to the application, preventing misuse.

### Resolution:

1. **Switch to OAuth 2.0**: Ombi needs to be updated to support **Modern Authentication** using OAuth 2.0 for email notifications.

### Ombi Version

4.41.1

### What platform(s) does this occur on?

Docker

### What database are you using?

MySQL

### Relevant log output

```shell
fail: Ombi.Notifications.GenericEmailProvider[0]
      Exception when attempting to send an email
      MailKit.Security.AuthenticationException: 535: 5.7.139 Authentication unsuccessful, basic authentication is disabled. [CH2PR15CA0017.namprd15.prod.outlook.com 2024-10-11T15:15:00.294Z 08DCE9CE417FBB7C]
       ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.139 Authentication unsuccessful, basic authentication is disabled. [CH2PR15CA0017.namprd15.prod.outlook.com 2024-10-11T15:15:00.294Z 08DCE9CE417FBB7C]
         --- End of inner exception stack trace ---
         at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
         at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 109
warn: Ombi.Controllers.V1.External.TesterController[0]
      Exception when testing Email Notifications
      MailKit.Security.AuthenticationException: 535: 5.7.139 Authentication unsuccessful, basic authentication is disabled. [CH2PR15CA0017.namprd15.prod.outlook.com 2024-10-11T15:15:00.294Z 08DCE9CE417FBB7C]
       ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.139 Authentication unsuccessful, basic authentication is disabled. [CH2PR15CA0017.namprd15.prod.outlook.com 2024-10-11T15:15:00.294Z 08DCE9CE417FBB7C]
         --- End of inner exception stack trace ---
         at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
         at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
         at Ombi.Notifications.GenericEmailProvider.SendAdHoc(NotificationMessage model, EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi.Notifications/GenericEmailProvider.cs:line 109
         at Ombi.Controllers.V1.External.TesterController.Email(EmailNotificationSettings settings) in /home/runner/work/Ombi/Ombi/src/Ombi/Controllers/V1/External/TesterController.cs:line 300
```

**Comment by Dan-613** [comment]
@Tor-Brynjar How would you suggest resolving this without requiring every admin to create an Azure App Registration to support OAuth 2.0 for their installation ?

**Comment by Tor-Brynjar** [comment]
> How would you suggest resolving this without requiring every admin to create an Azure App Registration to support OAuth 2.0 for their installation ?
> 
> @Tor-Brynjar

You could avoid that by implementing a built-in option for OAuth 2.0, where admins configure their email credentials directly in the application, and Ombi handles the token generation and renewal process internally.

**Comment by Dan-613** [comment]
>You could avoid that by implementing a built-in option for OAuth 2.0, where admins configure their email credentials directly in the application, and Ombi handles the token generation and renewal process internally.

As far as I'm aware (correct me if I'm wrong), OAuth 2.0 still requires details such as ClientID etc which can only be created by performing an App Registration on Azure, Google Cloud etc. 

> Ultimately, the easier solution for Ombi would be to explicitly not support Microsoft email addresses and advocate for users to instead use a different email provider that still accepts basic auth.

As time progresses, more and more providers will stop offering basic auth. I wonder how other Open Source projects similar to Ombi are handling this issue.

**Comment by JDA88** [comment]
> As time progresses, more and more providers will stop offering basic auth. I wonder how other Open Source projects similar to Ombi are handling this issue.

I agree on this one, basic auth will disapear at some point

**Comment by Groodles** [comment]
Google have now removed basic authentication for SMTP also.  

All their instuctions indicate that OAUTH should be the minimum standard now.  So anyone using a GMail account will also run into issues sending notifications.
