### ISSUE TITLE
Ombi Stopped Sending Newsletters

### ISSUE THREAD

**Issue by shonj** [Ombi-app/Ombi#5194]
### Summary

Issue:
Ombi recently stopped sending weekly newsletters. It successfully sent newsletters on 11/15 and 11/22, but it did not send the scheduled email this past Friday, 11/29.

Steps Taken:

Tested with the "Test" Newsletter button:
Test newsletters are sent successfully when the button is clicked.

Attempted to manually trigger the newsletter:
Ombi does not send the newsletter when the "Trigger" button is clicked.

Verified the issue started on version 4.46.4:
Upgraded to 4.46.6, but the problem persists.

### Ombi Version

4.46.6

### What platform(s) does this occur on?

Windows

### What database are you using?

MySQL

### Relevant log output

```shell
2024-11-30 11:34:02.947 -05:00 [ERR] Error when attempting to create newsletter
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<>c.<FilterEpisodes>b__33_0(IMediaServerEpisode x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.FilterEpisodes(IEnumerable`1 source, IEnumerable`1 recentlyAdded) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetSeriesContent[T](IMediaServerContentRepository`1 repository, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 319
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 125
2024-11-30 11:34:02.947 -05:00 [ERR] Job System.INewsletterJob threw an unhandled Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<>c.<FilterEpisodes>b__33_0(IMediaServerEpisode x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.FilterEpisodes(IEnumerable`1 source, IEnumerable`1 recentlyAdded) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetSeriesContent[T](IMediaServerContentRepository`1 repository, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 319
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 125
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 232
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 401
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-11-30 11:34:02.948 -05:00 [ERR] Job System.INewsletterJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<>c.<FilterEpisodes>b__33_0(IMediaServerEpisode x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.FilterEpisodes(IEnumerable`1 source, IEnumerable`1 recentlyAdded) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetSeriesContent[T](IMediaServerContentRepository`1 repository, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 319
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 125
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 232
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 401
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<>c.<FilterEpisodes>b__33_0(IMediaServerEpisode x) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.FilterEpisodes(IEnumerable`1 source, IEnumerable`1 recentlyAdded) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 407
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.GetSeriesContent[T](IMediaServerContentRepository`1 repository, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 319
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 125
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 232
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Execute(IJobExecutionContext job) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 401
   at Ombi.Schedule.QuartzJobRunner.Execute(IJobExecutionContext context) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/QuartzJobRunner.cs:line 23
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
```

**Comment by K9Sports** [comment]
Any help with this at all? I've been having this exact same problem but I'm running 4.47.1.  This hasn't worked for months now and my users are really missing it.  This is the main reason I use OMBI instead of Overseerr.
I've tried disconnecting Jellyfin and reconnecting.  I tried flushing cache.  I uninstalled Ombi and reinstalled. I tried everything I can find on this issue.  Nothing works.
PLEASE help.
