### ISSUE TITLE
TVDBID is missing

### ISSUE THREAD

**Issue by jsd9s2un3s3** [Ombi-app/Ombi#5203]
### Summary

When requesting a show I get the "Something went wrong" message and the logs report "TVDBID is missing"

URLs:

- https://someserver/details/tv/204486
- https://www.themoviedb.org/tv/204486
>>redirects to>>
https://www.themoviedb.org/tv/204486-stoner-cats
- https://www.imdb.com/title/tt15139516

From sonar:
- https://www.thetvdb.com/?tab=series&id=421930

I am not sure why the linuxserver version is so old (open to switching of course), but I don't see anything in the change logs from that version to current that would suggest upgrade will resolve the issue.

### Ombi Version

4.44.1 (docker: lscr.io/linuxserver/ombi:latest newest avalible)

### What platform(s) does this occur on?

Linux

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
2024-12-25T04:14:51.008317926Z fail: Ombi.Core.Senders.TvSender[5001]
2024-12-25T04:14:51.008750674Z       Exception thrown when attempting to send series over to Sonarr
2024-12-25T04:14:51.009073872Z       System.Exception: TVDBID is missing
2024-12-25T04:14:51.009415510Z       
2024-12-25T04:14:51.009758368Z          at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 53
2024-12-25T04:14:51.018847495Z fail: Ombi.Core.Senders.TvSender[0]
2024-12-25T04:14:51.023137360Z       Exception thrown when sending a movie to DVR app, added to the request queue
2024-12-25T04:14:51.023756547Z       System.Exception: TVDBID is missing

2024-12-25T04:14:51.024126135Z       
2024-12-25T04:14:51.024304264Z          at Ombi.Core.Senders.TvSender.SendToSonarr(ChildRequests model, SonarrSettings s) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 253
2024-12-25T04:14:51.024510842Z          at Ombi.Core.Senders.TvSender.Send(ChildRequests model) in /home/runner/work/Ombi/Ombi/src/Ombi.Core/Senders/TvSender.cs:line 52
```

**Comment by jsd9s2un3s3** [comment]
This might be a feature add, but including some information about what was requested in the error would be nice.
