### ISSUE TITLE
macos can only connect on localhost

### ISSUE THREAD

**Issue by notsolowki** [Ombi-app/Ombi#5206]
### Summary

no matter what ive tried i can only use localhost to connect if i try lan ip address it result in the error

### Ombi Version

Ombi 4.44.1+1e3bd6377ce64c5d79f8b267f0f190b7b141d8af

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
Unhandled exception. System.ArgumentException: The supplied System.Net.SocketAddress is an invalid size for the System.Net.IPEndPoint end point. (Parameter 'socketAddress')
   at System.Net.IPEndPoint.Create(SocketAddress socketAddress)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(SocketAddress remoteSocketAddress)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.AcceptCompletionCallback(IntPtr acceptedFileDescriptor, Memory`1 socketAddress, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by tidusjar** [comment]
Do you have any launch arguments?

**Comment by notsolowki** [comment]
i tried 

--host http://localhost:5000
--host http://192.168.1.4:5000
--host http://*:5000
--host http://all:5000


they all resulted in the same thing, except 192.168.1.4:500 when try to reach i get no error but also dont work on localhost. only localhost,* and 127.0.0.1 work, and if i try to access from 192.168.1.4 while using any 3 of the locahl host parameters i get the error

**Comment by tidusjar** [comment]
When you access from the IP, is that on a separate machine? Is there a firewall blocking access? 

Using the ‘*’ one should bind ombi to all of the available address spaces. --host http://*:5000

See here https://docs.ombi.app/info/startup-parameters/#parameters

**Comment by notsolowki** [comment]
yes We are running on http://*:5000

and yes its all being done from the host machine, ive tried from other machines too.
